### ISSUE TITLE
Inconsistency with Zap channel balance visual representation. 

### ISSUE THREAD

**Issue by johnpaulkiser** [lightninglabs/lightning-terminal#101]
### In Zap wallet local balance is on the left in the channel balance visualizer:  
![image](https://user-images.githubusercontent.com/15898511/90466678-603b0c00-e0e0-11ea-8494-2b92120382b3.png)

### However, in lighting-terminal the local balance is on the right:
![image](https://user-images.githubusercontent.com/15898511/90466850-bc9e2b80-e0e0-11ea-82e0-fc0559d35a24.png)

Since both of these visual representations express the same idea the orientation should be standardized across wallets and other tools to create a consistent UX across Lightning products.

**Comment by paboset** [comment]
Do all channel management product features have the same end user goals? It's not clear to that this is an issue with LiT, necessarily, as much as the greenfield nature of the beast.

My thoughts: I like LiT design better than Zap. Would prefer to see Zap conform to this. Lots of unused white space in the Zap design. LiT's is so clean & clear from the single bars to the copy 'Can receive' and 'Can send'.

What do you think about closing this and opening an issue on Zap?

**Comment by jamaljsr** [comment]
Hi @johnpaulkiser, thanks for the feedback. There are many Lightning apps/wallets/dashboards that all display channel balances differently based on the design of their UI. We reviewed this internally and felt it better suited for LiT to have the local balance on the right-hand side. I understand how this inconsistency across apps can be a bit annoying, but it really is not feasible to enforce this cosmetic consistency throughout the whole ecosystem. Each dev team has the authority to display the channel balances based on what they feel is a best fit in their UI. 

We do appreciate the feedback, and maybe this is something to consider in a future iteration of the overall UI design, but for the immediate future we are not likely to make this change. I'm going to close this issue out now. Thanks again for the feedback.

**Comment by johnpaulkiser** [comment]
> We reviewed this internally and felt it better suited for LiT to have the local balance on the right-hand side.

Can you elaborate on this? Is it something specific about Loop or something that makes (remote -> local) more user friendly than how every other wallet or lightning tool lists balances, (local -> remote)?  


### Lightning Labs Desktop:
![image](https://user-images.githubusercontent.com/15898511/90704883-a66aa980-e25f-11ea-8abd-17b570fdabbe.png)


### RTL
![image](https://user-images.githubusercontent.com/15898511/90705039-019c9c00-e260-11ea-8480-1c53322257cf.png)


### Polar
![image](https://user-images.githubusercontent.com/15898511/90705374-ce0e4180-e260-11ea-9417-4421420a5230.png)
