### ISSUE TITLE
UNABLE TO PERFORM LOOP IN error says use 'listauth'

### ISSUE THREAD

**Issue by pfergi42** [lightninglabs/lightning-terminal#117]
I have litd up and running and my first channel opened. I only have receiving capacity so I'm trying to do a LOOP IN, but I get this error:

<img width="329" alt="listauth" src="https://user-images.githubusercontent.com/4021240/92980590-b125f200-f44b-11ea-94fc-68acb2374855.png">

It suggests to use 'listauth' to find the token file name. Is listauth a lncli or litd command?

What token file is this referring to?

Thank you in advance.

**Comment by jamaljsr** [comment]
Hey @pfergi42, `listauth` is a `loop` command. 

Try this (change the paths to the cert and macaroon if necessary)
```
loop listauth --rpcserver=localhost:10009 --tlscertpath=$HOME/.lnd/tls.cert --macaroonpath=$HOME/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
```

It is safe to delete or rename the LSAT file. A new one will be regenerated.

**Comment by pfergi42** [comment]
Thank you. When I run that command (after changing path to cert) I get this
error:

Incorrect Usage: flag provided but not defined: -rpcserver

**Comment by jamaljsr** [comment]
> Incorrect Usage: flag provided but not defined: -rpcserver

This could be one of two things:
- the `--rpcserver` flag requires two dashes `--`. You only show one in the output.
- the loop cli you are using is an older version. Are you using the `loop v0.8.5-beta` binary that is packaged in the downloadable release from github or do you compile from source? If you compile, be sure to also clone & compile the latest `v0.9.0-beta` loop CLI or download it from the [loop](https://github.com/lightninglabs/loop/releases/tag/v0.9.0-beta) repo.

**Comment by jamaljsr** [comment]
Also, you can also just look in the `.loop` dir manually. This is where the pending LSAT token files are stored.

Depending on your OS, it'll be in one of these locations:
- Mac: ~/Library/Application Support/Loop/
- Linux: ~/.loop/
- Windows: ~/AppData/Roaming/loop/

**Comment by pfergi42** [comment]
> the --rpcserver flag requires two dashes --. You only show one in the output.

I was using two dashes, it's just the error message only shows one.

> Also, you can also just look in the .loop dir manually. This is where the pending LSAT token files are stored.

Thank you, I was able to find it on my Ubuntu machine in the ~/.loop/ directory. I deleted the LSAT token and tried again, but then I get this "insufficient balance" error, however, I do have sufficient on-chain balance:

![Screen Shot 2020-09-14 at 12 29 22 PM](https://user-images.githubusercontent.com/4021240/93129657-40b6e500-f686-11ea-9919-a0c38fea3c6e.png)

![Screen Shot 2020-09-14 at 12 32 03 PM](https://user-images.githubusercontent.com/4021240/93129697-51fff180-f686-11ea-87a2-ab6db7abab3a.png)

Perhaps I'm misunderstanding something fundamental here? This channel already exists and has only receiving capacity. Can the "loop in" actually increase the overall size of the channel capacity?

**Comment by guggero** [comment]
The problem is not the loop in itself but the LSAT authentication that is required to access the loop service in general. You have to be able to pay 1 satoshi to get access to the service (this is a one-time payment, the token will not expire). So in a situation like yours where you only have outbound capacity and "can send" of 0, you cannot pay for the token. This is an edge case that we somehow have to solve.

You can contact me on Slack and I'll pay you an invoice of a few Satoshis so you can use the loop service.

**Comment by pfergi42** [comment]
Thanks for you help @guggero. With a little sending capacity I was able to get this going.

Perhaps a suggestion or possible feature request: with the LSAT token, because it's regenerated every time it's needed, perhaps the Loop binary can delete it for the user and regenerate it so that error doesn't occur for future users?
