### ISSUE TITLE
Fee Settings in the UI (Time Preference)

### ISSUE THREAD

**Issue by pfergi42** [lightninglabs/lightning-terminal#118]
I would like to use the LiT UI to indicate my time preference for Loops, in an effort to minimize fees paid.

I can see two ways I would want to indicate this:

1. A maximum fee I want to pay:

e.g. I will pay max 5000 sats and I don't care how long it takes.

2. A speed which I am comfortable.

e.g. I can wait 24 hours.
e.g. I can wait until the weekend.
e.g. Next block please.

**Comment by jamaljsr** [comment]
Hi @pfergi42,

We just recently added the `--conftarget` option when performing loops in the UI. See PR https://github.com/lightninglabs/lightning-terminal/pull/112. This allows you to adjust your time preference in regards to the on-chain fees. Setting this value to a higher number reduces the fees that will be paid.

**Comment by pfergi42** [comment]
Looks great!
