### ISSUE TITLE
Lightninglabs offical docker repo

### ISSUE THREAD

**Issue by stefanlsd** [lightninglabs/lightning-terminal#150]
I currently build LiT and push it to a docker.io repo so I can deploy it via docker / kubernetes. I think it would be preferable and create more trust if the build was automated and maintained by the lightninglabs docker profile.

This can be set up easily within docker.io automated build on release tag to ensure the latest release is always built

I currently build with no modifications

**Comment by guggero** [comment]
Yes, we are planning on doing this for all our projects. Should hopefully be ready some time this year.

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/lightning-terminal/pull/153.
