### ISSUE TITLE
Allow disabling SSL

### ISSUE THREAD

**Issue by lukechilds** [lightninglabs/lightning-terminal#162]
We want to package LiT as an Umbrel app and to do this each app registers a port which the user can access over the local network or via a Tor hidden service.

You can read more about our app design here for context: https://github.com/getumbrel/umbrel/blob/master/apps/README.md

It would be great if we could disable SSL on LiT, it doesn't provide any extra security in the context of Umbrel and is a UX nightmare for users.

All remote connections are handled by exposing the app as a Tor hidden service which handles encryption too. Using SSL on top of Tor is redundant.

For local connections we can't generate CA signed certs, so we'd need to use self signed certs. This is a UX nightmare for users to enable, they get all sorts of scary browser warnings that make it look like it's not working.

It's also full of security footguns, if users don't correctly pin the certificate (most have no idea how to do this) then SSL is providing no security, despite the fact it appears to be working.

It would be great if LiT supported a config parameter to allow serving the web UI over plain HTTP and not requiring SSL. Would you be interested in implementing that?

**Comment by jamaljsr** [comment]
Yes, I think we all would be interested in seeing LiT packaged with Umbrel. 

I'll do an investigation to see what needs to be done to accomplish this. My immediate worry is that we currently use `grpc-web` on the client with `grpc-webproxy` + `http2` on the backend. I believe that most, if not all, browsers that support `http2` require TLS. I'm sure there is a way to work around this limitation, it just probably isn't as simple as changing a config option. I imagine that this will be a bit more involved to get working.

I'll follow up as soon as I can, once I gather more info and do some testing.

**Comment by lukechilds** [comment]
Awesome, thanks @jamaljsr!

Yeah I hadn't considered HTTP2 issues. Specter are facing similar issues due to camera APIs used for scanning QR codes not being available without HTTPS.

Let me know if there's anything we can do to help from our end.

**Comment by jamaljsr** [comment]
Good news. I've tested locally and confirmed that the `grpc-webproxy` will work with a relatively small amount of changes to the backend. The only thing we have to figure out now is what config flags to expose. It is possible to run both `https` and `http` servers simultaneously, or we could only allow one at a time.

I suppose that you want to run the `http` server only, not both. So a simple `--insecure-http=true` flag would probably work for your specific use case. Is that correct?

**Comment by lukechilds** [comment]
Amazing!

> So a simple --insecure-http=true flag would probably work for your specific use case. Is that correct?

That would be perfect, yes!

**Comment by jamaljsr** [comment]
@guggero reminded me that the CLIs (`lncli`, etc) require TLS for the gRPC communication with the server. So the `--insecure-http=true` will not work. Instead, we'll need to listen for both `http` & `https`. We'll add a `--httplisten` flag which is disabled by default. To enable it, you would need to set its value to a `host:port` such as `0.0.0.0:8000`.

Do you foresee an issues with this approach instead?

**Comment by lukechilds** [comment]
No that sounds perfect.

So you're saying that the gRPC server will listen for both HTTP and HTTPS traffic, HTTPS will be used by the CLIs clients and HTTP can be used by the web client, is that correct?

**Comment by guggero** [comment]
Exactly, everything will be available on both HTTP and HTTPS but you won't be able to use the CLIs against the non-TLS port because there's no flag to disable TLS (because the underlying gRPC library will refuse to send macaroons over a non-TLS connection).

**Comment by lukechilds** [comment]
Perfect, sounds great.

**Comment by lukechilds** [comment]
Thanks for getting this done so quickly guys!

We're planning on doing a new Umbrel release today or tomorrow with third party app support. Do you know when we can expect to see the new flag out in a LiT release?

**Comment by louneskmt** [comment]
Thanks a lot! Going to test and check if everything is ok.

**Comment by guggero** [comment]
Okay, cool. Thank you! I can do a release as soon as I get confirmation from you.

**Comment by louneskmt** [comment]
> Okay, cool. Thank you! I can do a release as soon as I get confirmation from you.

Seems all good to me, the new flag works great. Can you confirm @lukechilds?

Quick question: can the `lightning-terminal` docker container be run as a non-root user?

**Comment by guggero** [comment]
Great, thanks for the feedback. The new release is out: https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.3.4-alpha
The docker image is still building but should be ready soon: https://github.com/lightninglabs/lightning-terminal/runs/1591892939?check_suite_focus=true

> Quick question: can the lightning-terminal docker container be run as a non-root user?

I've never tried this myself but can't think of any reason why it shouldn't run as a non-privileged user. As long as no listening ports are below 1024, nothing should require root permissions.

**Comment by lukechilds** [comment]
Great, thanks so much for shipping this so quickly guys!

I'll be testing this out today.

**Comment by lukechilds** [comment]
Working great, thanks again for your help guys!
