### ISSUE TITLE
LiT crashes after LND has changed wallet password

### ISSUE THREAD

**Issue by lukechilds** [lightninglabs/lightning-terminal#167]
If you change the wallet password in LND then LiT will display the error `oops, that password is incorrect` when trying to log in with a password and then the LiT daemon will crash.

It doesn't seem to be any sort of issue with password authentication since the config has not changed and the same password is being entered. It seems like something else errors  and is swallowed and this password error is what's returned.

I'm not sure if this is a bug in LiT or LND but either way it would be great if the error could be handled in LiT to make it more clear what's going on.

Once in this state even if you completely uninstall LiT and reinstall it, nuking all data directories, the issue persists. However if you reinstall LND and nuke it's data directories and then create a new wallet, then the issue is resolved.

So it seems like changing the LND password is putting LND in a strange state that LND itself can still run in but LiT errors out.

Attached LiT logs below:

```
[INF] LITD: Dialing lnd gRPC server at 10.21.21.9:10009
[INF] LITD: Listening for http_tls on: 127.0.0.1:8443
[INF] LITD: Listening for http on: [::]:3004
----------------------------------------------------------
 Lightning Terminal (LiT) by Lightning Labs               
                                                          
 Operating mode      remote                                   
 Node status         online                                   
 Alias               02d561a482b9ddd1b492                                   
 Version             0.11.1-beta commit=v0.11.1-beta                                   
 Web interface       https://127.0.0.1:8443, http://localhost:3004                                   
----------------------------------------------------------
[INF] LNDC: Creating lnd connection to 10.21.21.9:10009
[INF] LNDC: Connected to lnd
[INF] LNDC: lnd version: v0.11.1-beta, build tags 'autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,watchtowerrpc'
[INF] LNDC: Using network mainnet
[INF] LNDC: Waiting for lnd to be fully synced to its chain backend, this might take a while
[INF] LNDC: lnd is now fully synced to its chain backend
[INF] LOOPD: Swap server address: swap.lightning.today:11010
[INF] STORE: Checking for schema update: latest_version=4, db_version=4
[INF] LLMD: Version: 0.3.4-alpha commit=
[INF] LOOPD: Starting liquidity manager
[INF] LOOPD: Waiting for updates
[INF] LOOPD: Starting swap client
[INF] LOOP: Connected to lnd node '02d561a482b9ddd1b492' with pubkey 02d561a482b9ddd1b492f208ab72275b73eb57f7f9e9fd6b76521f3e0d524b0f23 (version v0.11.1-beta, build tags 'autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,watchtowerrpc')
[INF] LOOP: Wait for first block ntfn
[ERR] LOOP: Swap client terminating: rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification
[INF] LOOP: Swap client terminated
[INF] LOOPD: Swap client stopped
[ERR] LOOPD: Runtime error in daemon, shutting down: rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification
[INF] LOOPD: Stopping gRPC server
[INF] LOOPD: Stopping REST server
[WRN] GRPC: grpc: addrConn.createTransport failed to connect to {swap.lightning.today:11010  <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp 52.25.40.106:11010: operation was canceled". Reconnecting...
[INF] LOOPD: Liquidity manager stopped
[INF] LOOPD: Daemon exited
[INF] LLMD: Auction server address: pool.lightning.finance:12010
[INF] CLDB: Checking for schema update: latest_version=1, db_version=1
[INF] RPCS: Starting trader server
[INF] RPCS: Connected to lnd node 02d561a482b9ddd1b492 with pubkey 02d561a482b9ddd1b492f208ab72275b73eb57f7f9e9fd6b76521f3e0d524b0f23
[INF] AUCT: Shutting down auctioneer client
[ERR] LITD: Could not start subservers: rpc error: code = Canceled desc = grpc: the client connection is closing
[ERR] LITD: Error stopping loop: rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification
[ERR] LNDC: Error closing client connection: rpc error: code = Canceled desc = grpc: the client connection is closing
[INF] SGNL: Received shutdown request.
[INF] SGNL: Shutting down...
[INF] SGNL: Gracefully shutting down.
[WRN] GRPC: grpc: addrConn.createTransport failed to connect to {pool.lightning.finance:12010  <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: context canceled". Reconnecting...
[ERR] LITD: Error shutting down: rpc error: code = Unknown desc = verification failed: signature mismatch after caveat verification
rpc error: code = Canceled desc = grpc: the client connection is closing
```

You can reproduce this with Umbrel by:
- Setting up Umbrel
- Installing LiT
- Opening the LiT app and logging in fine
- Change Umbrel password (which also changes the LND password)
- Log back in to Umbrel
- Open the LiT app and logging in will fail
- LiT server will soon crash
- You should see the logs above at http://umbrel.local/logs

Nuking the LND data directory and creating a new wallet solves the issue.

A few Umbrel users have run into this and as far as we're aware there's no easy fix apart from us walking them through nuking their LND wallet and recreating it via CLI. Any help resolving this issue would be hugely appreciated!

**Comment by guggero** [comment]
The main error here is `verification failed: signature mismatch after caveat verification`.
This is thrown if the macaroon that is used to connect to `lnd` is invalid.
Without knowing how exactly the "Change Umbrel password" function works, I assume it sets the `new_macaroon_root_key` to `true`. This invalidates all macaroons that `lnd` issued before that point.
That flag is currently only meant to be set to true if `lnd` is running in the stateless mode.

You have two options to fix this (in Umbrel):
1. Delete all `<lnd-mount-dir>/data/chain/bitcoin/mainnet/*.macaroon` files after changing the password. They will be re-created once `lnd` starts up. This will make all existing macaroons that other apps might use invalid. I think that is fine though as you always mount the `lnd` directory into the app's filesystem to read the macaroons.
2. Don't set `new_macaroon_root_key` to `true`. This will cause all macaroons to still be valid after the password change.

**Comment by lukechilds** [comment]
Thanks @guggero!

So looking through our code it doesn't look like we're setting `new_macaroon_root_key` to `true`:

https://github.com/getumbrel/umbrel-middleware/blob/9d4e1dd77b3fa45a1dab38566028dace73ecd511/services/lnd.js#L108-L111

I even hardcoded the value to false but we still get the same issue:

https://github.com/getumbrel/umbrel-middleware/compare/master...lukechilds:no-rotate-macaroon

I can confirm deleting macaroon files resolves the issue, but a little confused why they are getting changed in the first place if we aren't setting `new_macaroon_root_key`. Any ideas as to why that might be?

**Comment by guggero** [comment]
Ah, I keep forgetting that the stateless initialization mode (that added the `new_macaroon_root_key` parameter) was only introduced with `v0.12.0-beta.rcX`. Before, removing the macaroon DB (and therefore invalidating all macaroons) was the default behavior on changing the password.

So you have two options IMO:
 - Update to the latest RC of `lnd v0.12.0-beta`
 - Write a script that removes all `*.macaroon` files after successfully changing the password

**Comment by lukechilds** [comment]
Ahhhh ok so I'm not going crazy, thanks again!

**Comment by lukechilds** [comment]
@guggero do you have a rough ETA for a non-RC v0.12.0 release? (super rough, won't hold you to anything).

If it's not gonna be too far away then it might be worth us just waiting for that instead of nuking macaroons on password change.

**Comment by guggero** [comment]
It looks like there is only one major issue around the `payment_addr` field. But once that gets resolved, I think the final release could happen soon. So maybe something around 2 weeks?

**Comment by lukechilds** [comment]
Perfect! Thanks @guggero we'll wait for that.
