### ISSUE TITLE
https port 443 in config-lnd-remote.md example to be 8443

### ISSUE THREAD

**Issue by emplexity** [lightninglabs/lightning-terminal#170]
To ensure consistency with the command   
"Visit https://localhost:8443 to access Terminal"
the following rcd in the config file example 
"--httpslisten=0.0.0.0:443 \" 
should be set to 8443 instead of 443 in config-lnd-remote.md

**Comment by MrPaz** [comment]
docs still have:
```
# Application Options
httpslisten=0.0.0.0:443
```
which resulted in an error at startup for me until I changed it to 8443.

 https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit/ubuntu-integrated

**Comment by guggero** [comment]
https://github.com/lightninglabs/docs.lightning.engineering/pull/249
