### ISSUE TITLE
Closeing a account

### ISSUE THREAD

**Issue by rtbit** [lightninglabs/lightning-terminal#181]
![bilde](https://user-images.githubusercontent.com/79416315/108633335-0727a880-7474-11eb-8dbe-2b6fb23b4b10.png)
I was trying to close a account under Lightning Pool, it now say pending close. 
BUT I got a error message up in the right corner, when I selected close account. It say I did not have high enought fee to create transaction. But I did not get any way to change the fee after that. 
And it now only say pending close, and it seeams my funds is zeroed out. 

It is linked to a transaction the does not not exist.
https://mempool.space/tx/07e1b61c00b39e58d0cad67ac903c74d43bd7d32d11307fe9ac266b3fb6c6c3b 

Have I lost my funds?? How do I get my funds back?

**Comment by guggero** [comment]
Can you post your account's `trader_key` here please? It isn't shown in the UI (@jamaljsr it would be quite helpful if we could show this somewhere for debugging puprposes), you'll need to use the CLI: https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md#example-pool-command

**Comment by rtbit** [comment]
Thanks for answering, i need to get everyting step buy step, for this is new to me. I run this on a Raspberry Pi, with the Umbrel setup. https://getumbrel.com/ 
I have not tried to connect to the NODE without the GUI interface for Umbrel and the different apps, like Lightning Terminal, with the Pool beta... It is installed trough the Umbrel store in the GUI.

**Comment by jamaljsr** [comment]
Hi @rtbit, I have an Umbrel node setup, so I can provide the steps to obtain your `trader_key`. 

1. SSH into the Umbrel node. The password is the same one you use to login to the Umbrel website
   ```
   ssh umbrel@umbrel.local
   ```
   > This command works on Mac & Linux. If you are using a Windows computer, you'll need to use an app like [PuTTY](https://www.putty.org/) to SSH into the Umbrel node.
2. Once logged in, your terminal prompt should say `umbrel@umbrel:~ $`
3. Run `bash` inside the `lightning-terminal` docker container
   ```
   docker exec -it lightning-terminal_web_1 bash
   ```
4. When inside the container, your terminal prompt should say `bash-5.1$`
5. Run the `pool` CLI command to list your accounts
   ```
   pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts list
   ```
6. It will output your account information, such as
   ```
   {
	"accounts": [
		{
			"trader_key": "026b7447973b79e8eaf79258c104b716a8107eedeeb25e484616daf001cf24bba3",
			"outpoint": "5b09744a8a4ab8e31eabd1e14ce7de9c434dedf13ab9fe6b27bd2ab807276f04:0",
			"value": 5381514,
			"available_balance": 5381514,
			"expiration_height": 1906780,
			"state": "EXPIRED",
			"latest_txid": "5b09744a8a4ab8e31eabd1e14ce7de9c434dedf13ab9fe6b27bd2ab807276f04"
		}
	]
   }
   ```
7. The `trader_key` value is what @guggero is asking for. Copy and paste that into this issue.

To quit the SSH session, just enter the `exit` command twice.

**Comment by jamaljsr** [comment]
> (@jamaljsr it would be quite helpful if we could show this somewhere for debugging puprposes)

I agree. It should be displayed in the Account section. I'll create a PR.

**Comment by jamaljsr** [comment]
#191 adds the trader key to the account section in the UI

**Comment by rtbit** [comment]
@guggero 
Finally i got it... 

{
        "accounts": [
                {
                        "trader_key": "025eee6a194ce5fcd0fde92adf8e67df243673361288b011c38441bfcfdcfd5502",
                        "outpoint": "aae77c65563a841182a3ec334d0282003297d16d5507ea1cab6aa6fcfd0545e6:1",
                        "value": 0,
                        "available_balance": 0,
                        "expiration_height": 671748,
                        "state": "PENDING_CLOSED",
                        "latest_txid": "07e1b61c00b39e58d0cad67ac903c74d43bd7d32d11307fe9ac266b3fb6c6c3b"
                }
        ]

**Comment by rtbit** [comment]
I see now that it is sent to the mempool... It was not before. 
https://live.blockcypher.com/btc/tx/07e1b61c00b39e58d0cad67ac903c74d43bd7d32d11307fe9ac266b3fb6c6c3b/

**Comment by guggero** [comment]
Restarting `lnd` (or LiT) will re-broadcast the transaction. That's probably why it's appearing now.
Though this probably won't confirm any time soon with 1 sat/vByte. You can try `lncli wallet bumpfee --sat_per_byte 15 07e1b61c00b39e58d0cad67ac903c74d43bd7d32d11307fe9ac266b3fb6c6c3b:0` to get it in.

Closing this as the chosen fee rate was just too small.

**Comment by rtbit** [comment]
I just did not understad what I was doing. Trying out new services. I guess that is waht testnet is for.... 

So where du i run this command? @guggero 
**lncli wallet bumpfee --sat_per_byte 15 07e1b61c00b39e58d0cad67ac903c74d43bd7d32d11307fe9ac266b3fb6c6c3b:0**

Need step buy step, 
I guess i need to ssh in... 
than log on... (#2 in @jamaljsr guide) ... 
but then what?

**Comment by rtbit** [comment]
@guggero  Tried it now... Got his error. 

[lncli] could not load global options: unable to read macaroon path (check the network setting!): open /lnd/data/chain/bitcoin/admin.macaroon: no such file or directory

**Comment by jamaljsr** [comment]
On Umbrel, the `lnd` node is running inside of a different container than LiT. So instead of running `bash` in the LiT container, you'll need to run `lncli` in the `lnd` container.

Try running these commands instead of step 3 above:
```
cd ~/umbrel
docker-compose exec lnd lncli wallet bumpfee --sat_per_byte 15 07e1b61c00b39e58d0cad67ac903c74d43bd7d32d11307fe9ac266b3fb6c6c3b:0
```

**Comment by rtbit** [comment]
![bilde](https://user-images.githubusercontent.com/79416315/110595624-890b1780-817e-11eb-8366-34760d683d90.png)

So did not get any confirmation, but i guess it did something, since it took some seconds, and did not give errors.... 
Hope this helps. I keep you posted if it worked. 

Thanks a lot for the help @guggero and @jamaljsr, could not have doen anything with this without your help. Love the open source community. I probably should learn Linux....

**Comment by rtbit** [comment]
https://live.blockcypher.com/btc/tx/07e1b61c00b39e58d0cad67ac903c74d43bd7d32d11307fe9ac266b3fb6c6c3b/
It seams to have done something... But the fee looks the same? Or am I missreading this?

**Comment by rtbit** [comment]
I see that the transaction is confirmed.... But where was it sent? I cant see it in the transactions in either the bitcoin wallet or the lightening wallet on my umbrel...

**Comment by rtbit** [comment]
@jamaljsr @guggero 
Just wanted to say thank you!!!
