### ISSUE TITLE
Can't close "Failed" loops

### ISSUE THREAD

**Issue by lnd-dl** [lightninglabs/lightning-terminal#187]
Just a minor thing:
When a loop fails it gives a message saying it fails in "Lightning Terminal" on the top. Next to it is an **X** to close it. When clicking on that nothing happens. When going to another menu point is disappears.

**Comment by jamaljsr** [comment]
Thanks for pointing that out. Looks like this was introduced some time ago when we did a code refactoring. This is fixed in #192
