### ISSUE TITLE
add funds to existing account in lightning terminal poold preview stuck in 'pending update'

### ISSUE THREAD

**Issue by riannom** [lightninglabs/lightning-terminal#192]
I opened an account in the poold preview for the minimum of 100k sats and it settled fine.  

Later, i tried adding some more sats and change the sats/vbyte to 2.  I got the pink error flag saying something like 'insufficient funds' but now my poold account is stuck in 'pending update' and the transaction isn't even in the mempool nor is my bitcoin core wallet deducted for the amount.

is there any way to unstuck the broken funding transaction or does it time out?  I'm a little concerned that it hasn't hit the mempool after waiting hours.  it makes me think that i broke something in the app on my end.

**Comment by guggero** [comment]
Can you send us the `trader_key` (a.k.a. `account_key`) of the account in question? I can take a look at what the server side state of it is. You can DM me on Slack if you don't want to paste the account key here.

**Comment by guggero** [comment]
@wpaulino the user reached out to me on Slack and we were able to resolve the issue by removing the diff on the server side and then using the account recovery on the client side.

Is there anything we can do to avoid this problem in the future? Seems the client was unable to broadcast the account modification TX but the server still added the diff with the `latest_tx` field set to an invalid TX (is that missing the user's sig on the witness at that point?).

**Comment by riannom** [comment]
Thanks for the help!  With the help of Oliver I was able to get this resolved!

**Comment by marospekarik** [comment]
Hi, I'm having the same issue, although I'm stuck on `Pending Open`

**Comment by wpaulino** [comment]
@marospekarik could you open a new issue and include more details (logs, account details, etc.)?
