### ISSUE TITLE
change default password 

### ISSUE THREAD

**Issue by cubiclestorm** [lightninglabs/lightning-terminal#199]
I can't find documentation anywhere on changing the default password. I installed through the umbrel app store.

**Comment by guggero** [comment]
The password is set here: https://github.com/getumbrel/umbrel/blob/master/apps/lightning-terminal/data/.lit/lit.conf
You should be able to change it in that file directly on your Umbrel. Though it might change back if the software is updated.

Closing this as the documentation would need to be added on Umbrel side.
