### ISSUE TITLE
add funds to existing account in lightning terminal preview stuck in 'Pending Open'

### ISSUE THREAD

**Issue by marospekarik** [lightninglabs/lightning-terminal#209]
Hi, I'm trying out the lightning terminal and my account status got stuck on "Pending Open". Therefore I'm unable to make any orders and receiving err – `acct=032ad5b2fed43090fa682913e3ba03878fd8dc1ac74a309721ef0bb0f1f8a46111 is in state StatePendingOpen, cannot make order`. I'm running the terminal through Umbrel dashboard.
 
Account Status: Pending Open
Trader Key: 032a...6111
Funding Transaction: [7155...fc42](https://mempool.space/tx/7155fb538df7035188ae63d5e76949df9149f528a7e9126bff59954101cefc42)
Current Balance: 100,000 sats
Open Orders: 0
Pending Balance: 0 sats
Available Balance: 100,000 sats

**Comment by Roasbeef** [comment]
The transaction is unconfirmed. It used a low fee rate. If you have access to the command line, you can increase the fee rate using `pool accounts bumpfee -h`.
