### ISSUE TITLE
Lightning terminal on Umbrel

### ISSUE THREAD

**Issue by rarjan** [lightninglabs/lightning-terminal#212]
Last night I was trying out Lightning Pool on the (Umbrel) Lightning Terminal with the transactions shown below. While waiting on the confirmation of the transaction I decided to change the standard password for a unique one. I changed the password in the lit.conf and reinstalled Lightning Terminal as shown in the "change password" tutorial. After the reinstall the pool account I opened was gone. Is it possible to get the funds back or to find the pool account somewhere?

65a294c3fdd62b599a1a01470b214a8d9b72d37a2c302e6febbc35df4e0bd349
8836881a03b1b0f9e386e3b8c4f800eb130c820ebcee5544a433712d211ac4ba
84a8ecd05e43944bf4bdb42f48328e4662bbc690e7e55243cd0ea0a081140eff

Many thanks in advance.
Best,
Arjan
<img width="342" alt="Screenshot 2021-04-13 at 12 23 00" src="https://user-images.githubusercontent.com/58561896/114539047-57d9a780-9c54-11eb-8b72-37bfd24d6d57.png">

**Comment by jamaljsr** [comment]
Hey @rarjan, check out `pool accounts recover --help`
```
NAME:
   pool accounts recover - recover accounts after data loss with the help of the auctioneer

USAGE:
   pool accounts recover [arguments...]

DESCRIPTION:

  In case the data directory of the trader was corrupted or lost, this
  command can be used to ask the auction server to send back its view of
  the trader's accounts. This is possible as long as the connected lnd
  node is running with the same seed as when the accounts to recover were
  first created.

  NOTE: This command should only be used after data loss as it will fail
  if there already are open accounts in the trader's database.
  All open or pending orders of any recovered account will be canceled on
  the auctioneer's side and won't be restored in the trader's database.
```
