### ISSUE TITLE
Listening info incorrectly reported in logs

### ISSUE THREAD

**Issue by ketominer** [lightninglabs/lightning-terminal#214]
Logs report "localhost" instead of the actual listening IP / interface

**Expected behavior**

Logs should report actual listening IP: " Web interface       https://localhost:3010   "

**Actual behavior**

```
2021-04-18 13:22:48.469 [INF] LITD: Dialing lnd gRPC server at localhost:10009
2021-04-18 13:22:49.105 [INF] LITD: Listening for http_tls on: [::]:3010
----------------------------------------------------------
 Lightning Terminal (LiT) by Lightning Labs               
                                                          
 Operating mode      remote                                   
 Node status         online                                   
 Alias               xxx                                   
 Version             0.12.1-beta commit=v0.12.1-beta                                   
 Web interface       https://localhost:3010                                
----------------------------------------------------------
```

**To reproduce**

./litd --httpslisten=0.0.0.0:3010 --uipassword=xxx --remote.lnd.macaroonpath=~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon 

**System information**

LiT installed from release TGZ on ARM64

**Comment by jamaljsr** [comment]
We display `localhost` when the value is set to `0.0.0.0` because you cannot copy/paste "http://0.0.0.0:3010" into a browser.

The actual host:port is logged in the message above: "LITD: Listening for http_tls on: [::]:3010"

**Comment by guggero** [comment]
Going to fix this by just showing both values, the original and the copy/paste-able URL.
