### ISSUE TITLE
Pool preview - Can't insert number, wrong localization?

### ISSUE THREAD

**Issue by bota87** [lightninglabs/lightning-terminal#220]
On the numeric input fields I can't write number > 1000.

If I start typing 1 and adding 0, after the third 0 clear the field and start back from 1
If I type a lot of 1 is even more weird, it start to switch thousand and decimal separator at every digit 

I'm on windows and my international settings are set on Italy:
decimal separator ,
thousand separator .

**Comment by jamaljsr** [comment]
Thanks for the bug report. This was fixed already in #207 and will be included in the next release of Terminal.
