### ISSUE TITLE
Connect to remote BTCPayServer lnd instance

### ISSUE THREAD

**Issue by AryanJ-NYC** [lightninglabs/lightning-terminal#225]
I followed the [instructions to connect to a remote lnd instance](https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md) but continuously got the following:

```
2021-05-16 13:18:35.399 [INF] LITD: Dialing lnd gRPC server at btcpay.xyz.xyz:443
2021-05-16 13:18:35.501 [INF] LITD: Listening for http_tls on: 127.0.0.1:8443
2021-05-16 13:18:35.837 [WRN] GRPC: grpc: addrConn.createTransport failed to connect to {btcpay.litservices.app:443  <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority". Reconnecting...
2021-05-16 13:18:35.837 [INF] SGNL: Received shutdown request.
error displaying startup info: error querying remote node : rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
2021-05-16 13:18:35.837 [INF] SGNL: Shutting down...
```
**Expected behavior**
It connects successfully.

**Actual behavior**
2021-05-16 13:18:35.837 [INF] SGNL: Received shutdown request.
error displaying startup info: error querying remote node : rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"

**System information**

Running Lightning Terminal standalone on Mac version 11.2.3. 

lnd-mode=remote

LiT v0.41-alpha from https://github.com/lightninglabs/lightning-terminal/releases

**Comment by guggero** [comment]
You need to supply `lnd`'s TLS certificate to LiT.
I'm not sure where exactly this is located in a btcpayserver setup. But you have to supply it in this config option:
```
remote.lnd.tlscertpath=/some/folder/with/lnd/data/tls.cert
```

**Comment by AryanJ-NYC** [comment]
I did that. In `btcpayserver-docker`, it's normally located in `/var/lib/docker/volumes/generated_bitcoin_lnd/_data/chains/mainnet` (or something like that). I `scp`'d that into my local machine and supplied it via the conig option.

I still get that error. :\ I also downloaded the `tls.key` thinking I needed, for some reason. Still nothing.

**Comment by guggero** [comment]
Ah, I just saw this now: `btcpay.litservices.app:443`. This doesn't seem to be the correct RPC address of `lnd`. It should be something with port `10009`. You might have to open that port specifically on the docker container. I believe the `443` is the REST proxy (or the nginx reverse proxy).

**Comment by AryanJ-NYC** [comment]
I _DO_ believe BTCPayServer exposes the GRPC on port 443 (which is totally odd for me, too).
![Screen Shot 2021-05-17 at 11 07 47 AM](https://user-images.githubusercontent.com/8263430/118511665-bf718f80-b6f7-11eb-9a94-504235561a97.png)

I wonder if it has anything to do with the `docker-compose` setup on `btcpay-docker`.  It definitely _IS_ odd to listen on 443.

**Comment by guggero** [comment]
Ah, you're right. The `nginx` reverse proxy listens on that port. So probably that just uses its own certificate that you have to specify instead of `lnd`'s?

**Comment by AryanJ-NYC** [comment]
> Ah, you're right. The `nginx` reverse proxy listens on that port. So probably that just uses its own certificate that you have to specify instead of `lnd`'s?

This sounds right. I'll hunt down that cert, give that a shot and get back to you. Thanks!

**Comment by jamaljsr** [comment]
Going to close this now as there hasn't been any updates. Based on the last comment, it appears there isn't anything here fr us to do on our end. @AryanJ-NYC feel free to reply if you are still facing this issue.
