### ISSUE TITLE
Faraday Integration

### ISSUE THREAD

**Issue by emretezel** [lightninglabs/lightning-terminal#228]
Hi everyone,

I thought when starting litd, faraday is also running in integrated mode by default, but the following command gives an error

```
ubuntu@ip-172-31-47-210:~/.lit$ frcli revenue
[frcli] rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:8465: connect: connection refused"
```

I have separately compiled and built faraday the executable under go/bin and recompiled litd since then.

Here is my lit.conf, am I missing anything? 

```
ubuntu@ip-172-31-47-210:~$ more .lit/lit.conf
# Server settings
uipassword=<password>
remote.lnd.macaroonpath=/home/ubuntu/.lnd/data/chain/bitcoin/mainnet/admin.macaroon
httpslisten=0.0.0.0:443

# Loop settings
loop.maxlsatcost=10000
loop.maxlsatfee=1000
loop.loopoutmaxparts=10

# Faraday settings
faraday-mode=integrated
faraday.lnd.macaroondir=home/ubuntu/.lnd/data/chain/bitcoin/mainnet
faraday.lnd.tlscertpath=/home/ubuntu/.lnd/tls.cert
```

**Comment by emretezel** [comment]
Also should I expect to see Faraday specific UI element on the Lightning Terminal web site?

**Comment by jamaljsr** [comment]
The default values for `frcli` will not work with Terminal. You must provide the correct rpc server, cert and macaroon. See https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-integrated.md#example-frcli-command

> Also should I expect to see Faraday specific UI element on the Lightning Terminal web site?

No, there isn't a UI for Faraday in Terminal at the moment.

**Comment by guggero** [comment]
Question was around faraday CLI commands, which are documented at the link given above. UI functionality is already tracked here: https://github.com/lightninglabs/lightning-terminal/issues/91.
