### ISSUE TITLE
Display unconfirmed and limbo balance in UI

### ISSUE THREAD

**Issue by pfergi42** [lightninglabs/lightning-terminal#229]
**Is your feature request related to a problem? Please describe.**
When someone force closes a channel, it appears to the new user that the channel and capacity has disappeared. It can be scary.

**Describe the solution you'd like**
 It would be better to show all unconfirmed and limbo LND balances in the UI, right next to the confirmed balance.

**Comment by levmi** [comment]
Included in Terminal Web UI. Closing.
