### ISSUE TITLE
Loop confirmation target interaction should warn of action consequences

### ISSUE THREAD

**Issue by pmrcunha** [lightninglabs/lightning-terminal#230]
Related with #165.

When defining the confirmation target for the sweep transaction, the relation between the target and the cap it sets for the on-chain fee is unclear. This can lead a new user to try a large target (400, fx.), receiving an on-chain transaction that has a fee too low to confirm, and, if uncapable of doing a CPFP transaction, losing their funds. That risk should be clearer.

In my view, the ideal solution would be for the user to define a fee cap instead of a confirmation target, making the risk explicit in the choice.

A lower effort solution would be to replace the tooltip text from:
```
The number of blocks to target for confirmation of the on-chain swap transaction. 
Specify a larger number to reduce fees.
```
To something like:
```
The number of blocks to target for confirmation of the on-chain swap transaction. 
Larger numbers will reduce fees, but if the transaction doesn't confirm you could lose your funds.
```

![loop_target](https://user-images.githubusercontent.com/4266670/119574358-86978180-bdad-11eb-97ea-5dc5709f72d6.png)

**Comment by alexbosworth** [comment]
Even if you specify a very large conf target it will ignore the low fee target at the end of the timer to avoid trusting the server not to take the on-chain funds

**Comment by pmrcunha** [comment]
I think I misunderstood the loop mechanism (my knowledge is limited to [this article](https://lightning.engineering/posts/2019-04-15-loop-out-in-depth/)).

So what you're saying is that if the on-chain transaction never confirms and is dropped from the mempool, or the target is reached, there's no sweep transaction, the preimage is never revealed and the swap just fails?

**Comment by alexbosworth** [comment]
I'm saying that at the end of the specified confirmation target that target will be ignored to use RBF to more rapidly increase the sweep fee to get a confirmation during the time when there is no possibility that the server could take the funds

RBF is also used continuously to keep the sweep fee related to the confirmation target setting and the transaction in the mempool

**Comment by pmrcunha** [comment]
Ah, ok! A lot of misunderstanding on my part. No merit in this issue then. I'll close it.
Thank you for the explanation.
