### ISSUE TITLE
Channels opened with shared funding transaction cause "duplicate chan in set" upon manual loop out selection

### ISSUE THREAD

**Issue by maxgoldberg** [lightninglabs/lightning-terminal#232]
When trying to loop out via lightning terminal, if you try to manually select channels that were opened in batch (i.e. multiple channels opened in one BTC transaction) it appears to try to balance all channels from that transaction.  If you choose multiple channels that were opened in the same transaction, it causes duplicates to show up which results in `[ERR] LOOPD: LoopOut: duplicate chan in set`

example:

Channels 1,2,3 opened in transaction A
Channels 4,5 opened in transaction B

Manually looping out to 3,4 works, manually looping out to 2,3 does not.

**Expected:**

Only loop out selected channels, regardless of funding transaction.

**Actual:**

Tries all channels opened in funding transaction, causing duplication errors from loopd.

**To Reproduce:**

Open multiple channels in a single funding transaction, then try to balance them with manual selection.

**System information**

Standalone litd, default settings
SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by guggero** [comment]
Thank you for the report. This sounds like a problem in Loop. I'm going to re-open this issue in the Loop repo and close it here. My assumption is that we only look at the TXID and not the output index.

**Comment by guggero** [comment]
Thanks @maxgoldberg for giving this another spin and sending me detailed logs. It turns out it's actually the frontend code that sends the duplicate channel IDs.

Here's the Loop log:
```
[INF] LOOP: LoopOut 0.1xxx BTC to bc1qxxxx (channels: xxxxxxxxxxxxx736,xxxxxxxxxxxxx736,xxxxxxxxxxxxx736)
```

But the actual channel IDs are: `xxxxxxxxxxxxx737, xxxxxxxxxxxxx738, and xxxxxxxxxxxxx739`

@jamaljsr could this be an int64 overflow in JS? Or are the channel IDs always treated as strings in the UI? I think somewhere in the channel selection logic something's mixed up.

**Comment by jamaljsr** [comment]
> @jamaljsr could this be an int64 overflow in JS? Or are the channel IDs always treated as strings in the UI? I think somewhere in the channel selection logic something's mixed up.

Yup, it looks like you're correct about the int64 overflow. I'll work on a bugfix.

**Comment by maxgoldberg** [comment]
This still appears to happen on the latest alpha. Does the last release include this fix?

**Comment by guggero** [comment]
There hasn't been a release of LiT in quite a while so this bug fix wasn't included yet, no. We should probably create a new release soon.
