### ISSUE TITLE
Loop out issue on raspiblitz 

### ISSUE THREAD

**Issue by Arnalverbeht** [lightninglabs/lightning-terminal#234]
Hi, I'm very new to the lightning space. I want to learn more about it's possibilities. Thats why I started a full node on a raspiblitz. 
After set up I opened a lightning channel via Thunderhub. To gain some inbound liquidity I tryed to loop out some sats to remote via Lightning Terminal but I got an error message (see below). 

<img width="307" alt="Bildschirmfoto 2021-05-25 um 23 42 33" src="https://user-images.githubusercontent.com/85165468/120308979-fd181000-c2d4-11eb-8640-4ae595835644.png">

I already deleted everything but the blockchain on the raspiblitz and set it up again, but the issue still excists.

Has anybody an idea, what I can do now?

**Comment by guggero** [comment]
What version of Loop are you running? This issue should be fixed in the latest version (0.13.0-beta). Are you sure your channel is operational and online?

**Comment by Arnalverbeht** [comment]
Ah okay. I'm on 

"lncli version 0.12.1-beta commit=lightning-terminal-v0.4.1-alpha"

I installed it via the terminal and the ssh of the raspiblitz. When I download the latest version and run it in terminal it doesn't work. Can you explain how I upgrade it now to the new version?

**Comment by guggero** [comment]
Okay, this currently is the latest version of LiT. Can you try removing the `lsat.token.pending` file somewhere in the `/home/lit/` directory? You can use `find /home/lit -name lsat.token.pending` to find it.

**Comment by Arnalverbeht** [comment]
It says, there is no such file or directory

**Comment by guggero** [comment]
Then the command isn't correct. I'm not too familiar with the setup of RaspiBlitz. Try `find / -name lsat.token.pending`.

**Comment by Arnalverbeht** [comment]
That worked. But every directory says permission denied. BTW I'm on Mac. Maybe that's the problem?

**Comment by guggero** [comment]
It depends on which user you are logged in on your RaspiBlitz. You might need to get some help from the RaspiBlitz community (as I mentioned, I'm not sure how the users/directories are set up on those devices). The goal is to find the `lsat.token.pending` file somewhere in LiT's user directory and remove it.

**Comment by guggero** [comment]
Just delete the file on the file system and try again.

**Comment by Arnalverbeht** [comment]
It still doesn't work. Now I get another error
<img width="306" alt="Bildschirmfoto 2021-06-08 um 14 26 48" src="https://user-images.githubusercontent.com/85165468/121184742-b17ddd00-c865-11eb-92f7-32c870733a8c.png">

**Comment by guggero** [comment]
Okay, you got one step further. Is your graph fully synced? Check `lncli getinfo`, it needs to say `synced_to_graph: true`. This seems to be a common issue with Umbrel, you might need to get some help from them.

**Comment by Arnalverbeht** [comment]
"synced_to_chain": true,
    "synced_to_graph": false,

It's not fully synced

**Comment by guggero** [comment]
Yes, so you have to wait until your node knows the whole network graph. Otherwise it won't know how to send a payment to the Loop server and you get the `no_route` error. This can take a while. If it takes more than half a day or so, you should probably open an issue in the Umbrel repo. It sounds to me like their switch from Neutrino to `bitcoind` doesn't work properly in all cases and the `--routing.assumechansvalid` flag isn't set properly.

**Comment by guggero** [comment]
Great, good to hear. Whether or not the loop goes through now fully depends on your channel liquidity and the quality of your peers. It might also take a few attempts.

I'm going to close the issue as the main problem seems to be resolved.
