### ISSUE TITLE
Input field for offered price does not work

### ISSUE THREAD

**Issue by dsche-cyber** [lightninglabs/lightning-terminal#235]
Input field in pool for OFFERED OUTBOUND LIQUIDITY when making an ask is not working.
Clicking on it allows to type values, but after typing 4 numbers a pop up appears:
must be a multiple of 100,000

So when typing 1000 (while trying to type 100000), the pop up shows up.
When typing the next (5th number) it deletes everything but the 1.
As a result it is not possible to provide an input correctly (just by copy pasting).

When typing 1234567890 the text in the input field is just:
1.235.790

Type numbers to be displayed, and the pop up warning and not allowing to place ask order

**Comment by jamaljsr** [comment]
This is what I see when I type in "1234567890" into that field.
![image](https://user-images.githubusercontent.com/1356600/121405208-c40e1a00-c92a-11eb-825f-03c3c30bc9e0.png)

Can you share a screenshot of what you see in your browser?

**Comment by jamaljsr** [comment]
Closing due to no response. Please reopen if you are still facing this issue.

**Comment by dsche-cyber** [comment]
I am still facing this issue. I use brave browser (brave shield down did not help).
I am on lnd0.13.1-beta, litd 0.5.0_alpha
