### ISSUE TITLE
Macaroons deleted before upgrading to v0.5.0 were not recreated when starting litd

### ISSUE THREAD

**Issue by VajraOfIndra** [lightninglabs/lightning-terminal#241]
I deleted all macaroons before upgrading from v0.4.1 to v0.5.0 (following this[ guide](https://github.com/Stadicus/RaspiBolt/blob/05bd93c9526fe1a16e13c5f7b143901647409a2c/raspibolt_faq.md#how-to-upgrade-lnd), this step might not be necessary anymore..?). When I started litd, the macaroons were not recreated and litd did not work. 
As a work around, I copy/pasted an admin.macaroon file that I had stored somewhere else (in the Ride the Lighting directory) and this fixed the issue, allowing me to unlock the wallet and allowing LND to create all the other macaroons (except the readonly.macaroon which is still missing).

**Expected behavior**
When starting litd, if there are no macaroons, new macaroons are created (as is the case when runing LND on its own, as described in the [documentation](https://docs.lightning.engineering/lightning-network-tools/lnd/macaroons#how-macaroons-are-used-by-lnd-and-lncli)).

**Actual behavior**
No new macaroons were created, preventing litd to run and preventing the unlocking of the wallet.

**To reproduce**
1. Have Lightning Terminal v0.4.1 running (with Raspberry Pi OS Lite (32-bit)).
2. Stop litd.
3. Delete all macaroons from the `/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/` directory.
4. Upgrade to v0.5.0
5. Start litd.

**System information**
I use Lightning Terminal as a standalone application on a Raspibolt node.

- What mode are you running Lightning Terminal in? Specifically of interest are the values of 'lnd-mode', 'faraday-mode', 'loop-mode' and 'pool-mode': I don't know, so probably the default modes..? Let me know where I could double-check this.

- What version of Lightning Terminal are you using, where did you get it (website, self-compiled, etc)? Version 0.4.1 before the upgrade, v.0.5.0 after the upgrade. I got it using: `wget https://github.com/lightninglabs/lightning-terminal/releases/download/v0.5.0-alpha/lightning-terminal-linux-armv7-v0.5.0-alpha.tar.gz
`

- What type of machine are you observing the error on (OS/CPU and disk type)? A Raspberry Pi 4 4GB with Raspberry Pi OS Lite (32-bit) on microSD card and a 1TB SSD external drive for the bitcoin and LND data.

- What is your operating system and its version? Raspberry Pi OS Lite (32-bit): 

`$ cat /etc/os-release`
> PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
> NAME="Raspbian GNU/Linux"
> VERSION_ID="10"
> VERSION="10 (buster)"
> VERSION_CODENAME=buster
> ID=raspbian
> ID_LIKE=debian
> HOME_URL="http://www.raspbian.org/"
> SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
> BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Any extra information that might be useful in the debugging process: I built the node using the Raspibolt guide and installed LiT and upgarded LiT following this [guide](https://github.com/Stadicus/RaspiBolt/blob/05bd93c9526fe1a16e13c5f7b143901647409a2c/raspibolt_40_lnd.md). 

`$ sudo journalctl -f -u litd`

> Jun 23 15:11:39 raspibolt systemd[1]: Started LND Lightning Network Daemon.
> Jun 23 15:11:40 raspibolt litd[10527]: Attempting automatic RPC configuration to bitcoind
> Jun 23 15:11:40 raspibolt litd[10527]: Automatically obtained bitcoind's RPC credentials
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.184 [INF] LTND: Version: 0.13.0-beta commit=lightning-terminal-v0.5.0-alpha, bu ild=production, logging=default, debuglevel=info
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.185 [INF] LTND: Active chain: Bitcoin (network=mainnet)
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.188 [INF] RPCS: RPC server listening on 0.0.0.0:10009
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.188 [INF] LITD: Dialing lnd gRPC server at 127.0.0.1:10009
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.192 [INF] RPCS: gRPC proxy started at 0.0.0.0:8080
> Jun 23 15:11:40 raspibolt litd[10527]: ----------------------------------------------------------
> Jun 23 15:11:40 raspibolt litd[10527]: Lightning Terminal (LiT) by Lightning Labs
> Jun 23 15:11:40 raspibolt litd[10527]:
> Jun 23 15:11:40 raspibolt litd[10527]: Operating mode integrated
> Jun 23 15:11:40 raspibolt litd[10527]: Node status locked
> Jun 23 15:11:40 raspibolt litd[10527]: Alias Indra
> Jun 23 15:11:40 raspibolt litd[10527]: Version 0.13.0-beta
> Jun 23 15:11:40 raspibolt litd[10527]: Web interface <my IP>:8443 (open https://<my IP>:8443 in your browser)
> Jun 23 15:11:40 raspibolt litd[10527]: ----------------------------------------------------------
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.193 [INF] LTND: Opening the main database, this might take a few minutes...
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.193 [INF] LTND: Opening bbolt database, sync_freelist=true, auto_compact=false
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.197 [INF] LITD: Listening for http_tls on: <my IP>:8443
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.203 [INF] CHDB: Checking for schema update: latest_version=22, db_version=22
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.203 [INF] LTND: Database now open (time_to_open=9.650251ms)!
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.203 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to c reate a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and un lock it.
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.394 [INF] LNDC: Creating lnd connection to 127.0.0.1:10009
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.395 [INF] LNDC: Connected to lnd
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.395 [ERR] LITD: Could not start subservers: open /mnt/ext/lnd/data/chain/bitcoi n/mainnet/admin.macaroon: no such file or directory
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.395 [INF] SGNL: Received shutdown request.
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.395 [INF] SGNL: Shutting down...
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.396 [INF] SGNL: Gracefully shutting down.
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.396 [ERR] LTND: unable to set up wallet password listeners: shutting down
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.398 [WRN] GRPC: transport: http2Server.HandleStreams failed to read frame: read tcp4 127.0.0.1:10009->127.0.0.1:36572: use of closed network connection
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.398 [WRN] GRPC: transport: http2Server.HandleStreams failed to read frame: read tcp4 127.0.0.1:10009->127.0.0.1:36576: use of closed network connection
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.398 [WRN] GRPC: transport: http2Server.HandleStreams failed to read frame: read tcp4 127.0.0.1:10009->127.0.0.1:36562: use of closed network connection
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.399 [WRN] GRPC: transport: http2Server.HandleStreams failed to read frame: read tcp4 127.0.0.1:10009->127.0.0.1:36582: use of closed network connection
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.399 [WRN] GRPC: transport: http2Server.HandleStreams failed to read frame: read tcp4 127.0.0.1:10009->127.0.0.1:36564: use of closed network connection
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.400 [WRN] GRPC: grpc: addrConn.createTransport failed to connect to {127.0.0.1: 10009 <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: EOF". Reconnecting...
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.400 [WRN] GRPC: transport: http2Server.HandleStreams failed to read frame: read tcp4 127.0.0.1:10009->127.0.0.1:36560: use of closed network connection
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.411 [INF] LTND: Shutdown complete
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.411 [ERR] LITD: Error running main lnd: unable to set up wallet password listen ers: shutting down
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.411 [ERR] LITD: Error stopping lnd: unable to set up wallet password listeners: shutting down
> Jun 23 15:11:40 raspibolt litd[10527]: 2021-06-23 15:11:40.411 [ERR] LITD: Error shutting down: unable to set up wallet password listeners : shutting down
> Jun 23 15:11:40 raspibolt litd[10527]: open /mnt/ext/lnd/data/chain/bitcoin/mainnet/admin.macaroon: no such file or directory
> Jun 23 15:11:40 raspibolt systemd[1]: litd.service: Main process exited, code=exited, status=1/FAILURE
> Jun 23 15:11:40 raspibolt systemd[1]: litd.service: Failed with result 'exit-code'.

**Comment by guggero** [comment]
Thanks for the report. I think this is due to a small bug that's already been fixed in https://github.com/lightninglabs/lightning-terminal/pull/240. We'll create a bugfix release soon.

In the meantime, can you try building `LiT` from the current master branch instead of `v0.5.0-alpha` to see if that actually fixes your problem?
If you remove all macaroons again (none of the three default macaroons `admin.macaroon, readonly.macaroon, invoice.macaroon` must exist in order for them to be re-created) they should be re-created. The reason they haven't been before is that the integrated Pool/Loop runs into an issue and shuts everything down before lnd gets to re-create them.

**Comment by VajraOfIndra** [comment]
Thanks for the reply @guggero! Good to know the bug is known and already fixed and part of the next release :)

I'd love to build LiT from the current master branch and test it but I don't feel I know enough yet about this process to do it in a safe way for my node! So unless I find someone to guide me through the steps, I don't think I'll try it... I hope you understand.

I'm not sure if that's the right place to ask, but is it necessary to delete the macaroons before upgrading to a new version of LND or LiT or is that an unnecessary step? Thanks in advance.

PS: I suppose I could close the issue now? (I'm new to Github so prefer to ask! :)

**Comment by guggero** [comment]
> but is it necessary to delete the macaroons before upgrading to a new version of LND or LiT

No, normally that's not necessary. But it happened on the last bigger release of Pool that we used a new RPC that required a macaroon permission that was only added recently. And since macaroons normally are never re-created this lead to issues with very old nodes. That's probably why the installation doc or script mentions the deletion.

> PS: I suppose I could close the issue now? (I'm new to Github so prefer to ask! :)

Yes, closing as this should be fixed in #240. Feel free to comment again if that isn't the case.

**Comment by VajraOfIndra** [comment]
> No, normally that's not necessary.

Thank you for your reply, much appreciated.

> Yes, closing as this should be fixed in #240. Feel free to comment again if that isn't the case.

Great, I'll close it now then.
