### ISSUE TITLE
UNABLE TO FETCH [X]: pool is not yet ready for requests, lnd possibly still starting or syncing

### ISSUE THREAD

**Issue by anguschampion** [lightninglabs/lightning-terminal#251]
**Expected behavior**

After starting Lightning Terminal from the command line, logging into the interface, and navigating to Lightning Pool, I should be able to see my account details as well as Lightning Pool status.

**Actual behavior**

When navigating to Lightning Pool, I am unable to view Pool status or my account details, instead getting a series of error messages in the format above. E.g.

UNABLE TO FETCH ACCOUNTS: pool is not yet ready for requests, lnd possibly still starting or syncing
UNABLE TO FETCH LEASE DURATIONS: pool is not yet ready for requests, lnd possibly still starting or syncing
UNABLE TO FETCH BATCH WITH ID: pool is not yet ready for requests, lnd possibly still starting or syncing

I was able to see my channels, and I was able to access my LND instance, both locally and remotely.

**To reproduce**

I was unable to reproduce the issue.

**System information**

LiT version 0.13.0-beta
lnd version 0.13.0-beta

Both downloaded as binaries.

Running remote: lnd host is Ubuntu 20.04.2 LTS, LiT host is MacOS 11.4.

Two files attached: 
pool_error.log, the debug log for when the error occurred
pool_error_prior.log, for the logs for what was an unexpected shutdown prior to the error. I'm unsure if relevant.
[pool_error.log](https://github.com/lightninglabs/lightning-terminal/files/6842553/pool_error.log)
[pool_error_prior.log](https://github.com/lightninglabs/lightning-terminal/files/6842554/pool_error_prior.log)

Config:
# Remote lnd options
remote.lnd.rpcserver=XXX.XXX.XXX.XXX:10009
remote.lnd.macaroonpath=XXX
remote.lnd.tlscertpath=XXX

# Loop
loop.loopoutmaxparts=5

# Pool
pool.newnodesonly=true

# Faraday
faraday.min_monitored=48h

# Faraday - bitcoin
faraday.connect_bitcoin=true
faraday.bitcoin.host=localhost

**Comment by guggero** [comment]
Thanks for the report! Seems to be some kind of timing issue. I'm looking into it.

**Comment by guggero** [comment]
> I was unable to reproduce the issue.

Just to clarify: Do you currently still see this issue? Meaning, do you still see the `unable to subscribe for account updates: error during authentication, before sending subscribe: no subscription found for commit hash` error in the log if you restart LiT?
Or only the other, follow-up errors (`... transport is closing`)?

Looking at the code I cannot see how the `no subscription found for commit hash` could ever happen unless the server sends something wrong (which would lead to everyone having this problem).
If you're willing to try to debug this, @anguschampion, can you try renaming/moving your `pool.db` file and then run `pool accounts recover` to see if that changes anything? That will cancel pending orders (if you ever were able to submit any).

**Comment by anguschampion** [comment]
To clarify, I terminated litd and restarted it, and I have not had a problem since nor had that error message. It was functioning correctly before, and has functioned correctly since.

I will try the steps you've mentioned when my connection gets back up and running and will revert.

**Comment by guggero** [comment]
If you only saw this behavior once and never since and everything is working as expected, I'd see this as maybe a temporary networking issue. Pool tried to connect to the server but during the authentication handshake something went wrong. This caused Pool to restart which would explain the other errors (the `transport is closing`).

**Comment by anguschampion** [comment]
Took a while to get onto this as I had to restore my blockchain but renaming pool.db didn't do much. I couldn't run `pool accounts` recover as I don't have poold running, I'm running the packaged litd binary.

Perhaps this goes on the back burner if we can't replicate: hopefully if it happens again we can run more testing.

**Comment by guggero** [comment]
Okay, closing for now. Feel free to reopen if it happens again.
