### ISSUE TITLE
Unable to close the pool account

### ISSUE THREAD

**Issue by arunvl88** [lightninglabs/lightning-terminal#252]
Unable to close the Pool Account

 I added about 150K sats to play around on LN pool on Lightning terminal app.

On the GUI, even after hit 'close and refresh the page, it shows account open
Also tried closing from the CLI:

1> First SSH into umbrel

# ssh umbrel@umbrel.local

2> Find the process ID of LN terminal:

#docker ps

3> Open the LN Docker

#docker exec -it a5c33b1e0d57 /bin/bash

4> Close the pool account

#pool --tlscertpath=/lnd/tls.cert accounts close --trader_key XXX sat_per_vbyte 1 --addr YYY

Latest error after the above command: 

Command: # pool --tlscertpath=/lnd/tls.cert accounts close --trader_key XXX sat_per_vbyte 1 --addr YYY

Error: [pool] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:12010: connect: connection refused"

Also tried: 

Command: # pool --rpcserver=localhost:10009 --tlscertpath=/lnd/tls.cert accounts close --trader_key XXX sat_per_vbyte 1 --addr YYY

[pool] rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:10009: connect: connection refused"

**Expected behavior**

Able to close the account

**Actual behavior**

Account is not closed

**To reproduce**

Can easily close

**System information**

LN Terminal as part of Umbrel

Not sure what mode I'm running

lightninglabs/lightning-terminal:v0.4.1-alph

litd.log doesn't show anything:
umbrel@umbrel:~ $ sudo journalctl -u litd -n 1000
[sudo] password for umbrel: 
-- Logs begin at Thu 2021-07-22 21:31:13 UTC, end at Thu 2021-07-22 21:50:09 UTC. --
-- No entries --

**Comment by guggero** [comment]
Umbrel runs LiT in "remote" mode. So you need to use a different port and need to use the correct tls.cert and pool.macaroon.
See here: https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md#example-pool-command
You might need to change some paths, not sure where exactly Umbrel stores their data for LiT. Their support should be able to answer that.

**Comment by arunvl88** [comment]
Here is the output of port numbers. I'm not too technical. If someone can help release my 150K sats from the pool. It would be helpful. Why is 'Close' button on LiT GUI not working btw?

'''

umbrel@umbrel:~ $ docker exec -it 0493bfec1986 /bin/bash
bash-5.1$ netstat -anp
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address Foreign Address State PID/Program name
tcp 0 0 127.0.0.11:38741 0.0.0.0:* LISTEN -
tcp 0 0 127.0.0.1:8443 0.0.0.0:* LISTEN 1/litd
tcp 0 0 10.21.21.17:46626 44.227.67.173:12010 ESTABLISHED 1/litd
tcp 0 0 10.21.21.17:55284 10.21.21.9:10009 ESTABLISHED 1/litd
tcp 0 0 10.21.21.17:55278 10.21.21.9:10009 ESTABLISHED 1/litd
tcp 0 0 10.21.21.17:59552 35.164.40.201:11010 ESTABLISHED 1/litd
tcp 0 0 10.21.21.17:55296 10.21.21.9:10009 ESTABLISHED 1/litd
tcp 0 0 10.21.21.17:55294 10.21.21.9:10009 ESTABLISHED 1/litd
tcp 0 0 :::3004 :::* LISTEN 1/litd
udp 0 0 127.0.0.11:43179 0.0.0.0:* -
Active UNIX domain sockets (servers and established)

'''

**Comment by guggero** [comment]
So your command needs to look something like this:
```
pool --tlscertpath=/data/.lit/tls.cert --rpcserver=localhost:8443 --macaroonpath=/data/.pool/mainnet/pool.macaroon accounts close --trader_key XXX sat_per_vbyte 1 --addr YYY
```

> Why is 'Close' button on LiT GUI not working btw?

Without an error message/screenshot/more detailed description/logs of what actually happens, I can't answer that.

**Comment by arunvl88** [comment]
Thank you sir! This worked!
on the GUI, there is no error. When you hit 'close' nothing happens. After refreshing LiT app the Account says open.

**Comment by guggero** [comment]
Before you can hit 'close' you need to enter a chain fee rate to close with. Only then the button activates and brings you to a summary page. There you need to confirm again. Are you sure that didn't work for you?

**Comment by guggero** [comment]
I assume this was resolved in the meantime, feel free to re-open if not.
