### ISSUE TITLE
Definition of metrics on https://terminal.lightning.engineering/ ?

### ISSUE THREAD

**Issue by xanoni** [lightninglabs/lightning-terminal#253]
The site https://terminal.lightning.engineering/  shows certain node-level metrics, but I was not able to find the respective definitions of each metric. I grepped through the code here but seems it's not part of this repository? Where can I find the definitions? Is it in one of the other repos?

![image](https://user-images.githubusercontent.com/77220130/126731166-40026c50-52c2-45b7-9d51-611fca262a4e.png)

**Comment by guggero** [comment]
The code for the "Terminal Web" (what we call the website at terminal.lightning.engineering) is not open source. We intend to improve the documentation and information presented on the website in general. For now I guess there's no "definition" of these terms per se but the linked guides intend to give more insight into what is needed to pass a check.

**Comment by xanoni** [comment]
@guggero thank you! Can you share the rough definition of "channel stability"?

My nodes are all struggling with that, but I don't know what the metric is actually measuring.

E.g., I deliberately rotate my IP address via cron, which leads to a minute of downtime every rotation. This is for privacy purposes. I don't want to turn this off unless I know that it might be causing bad "ratings" which would then result in fewer good peers.

We could obviously argue about the value of the IP rotation, but the node also has other daemons on it which benefit from that.

**Comment by Roasbeef** [comment]
Check out the guides linked in the right hand column there: you want your channels to be continually active, and available to route payments. You'll receive feedback if your actions impact the stability of your channels (both in terms of your peers dropping off, but also the external value changing on the site).

**Comment by xanoni** [comment]
So this is like a credit rating agency that doesn't publish the definition of its metrics?
