### ISSUE TITLE
Allow for deployment in subdirectory

### ISSUE THREAD

**Issue by dennisreimann** [lightninglabs/lightning-terminal#254]
**Is your feature request related to a problem? Please describe.**

Currently the app assumes to be deployed on a separate (sub)domain. For the [BTCPay Server integration](https://github.com/btcpayserver/btcpayserver/discussions/2706) I'd like to use our existing FE proxy (nginx) and certificates to provide an easier setup for the user. I imaging deploying the LiT app in a subdirectory of the existing BTCPay domain, like `mybtcpay.com/lit/`.

Right now the asset and API requests target the root `/`, whereas we would need to have them prefixed with `/lit/`.

**Describe the solution you'd like**

I started looking into this a bit and found the option of setting the [`homepage` option](https://create-react-app.dev/docs/deployment/#serving-the-same-build-from-different-paths) for create-react-app. By using `"homepage": "."` as a setting the build uses a relative URL for the asset references, which would solve that part. I'm unsure though whether or not this also works for the API calls. Before proceeding on that front I wanted to inquire if this feature would be wanted.

**Describe alternatives you've considered**

I've started using nginx `sub_filter` directives in our setup to rewrite certain URLs, but this is error prone and brittle.

**Comment by jamaljsr** [comment]
> I'm unsure though whether or not this also works for the API calls. 

The urls for the API calls will remain `https://x.x.x.x/lnrpc.Lightning/GetInfo` when you modify the homepage option. I do not believe there will be any issues with this.

> Before proceeding on that front I wanted to inquire if this feature would be wanted.

Exactly what feature are you proposing? modifying the `homepage` field in this repo?

An alternative option to customize the url path is the `PUBLIC_URL` environment variable when running `yarn build`. Unfortunately, this is also something that cannot be specified at runtime, so you wouldn't be able to use the `lightninglabs/lightning-terminal` docker image as is. You'd need to create a new docker image that uses the one of these methods.

**Comment by dennisreimann** [comment]
The general request would be to allow for the app to be run/deployed in a subdirectory. I think the homepage setting would make it work more universally and solve my current issue with the asset paths not working with a subdir deployment.

As for the API calls I think the config would need to be adapted to not only use the [host](https://github.com/lightninglabs/lightning-terminal/blob/master/app/src/config.ts), but also a potential path (as in our case). 

I'd like to avoid shipping a separate docker image and think we can achieve this via the homepage setting and determining the API base URL at runtime.

**Comment by jamaljsr** [comment]
How do you proposed we make the `homepage` option customizable at runtime? create-react-app uses this field at build time to set the css/js paths in the html.

**Comment by dennisreimann** [comment]
I think it can be set on build time without having a negative effect on how the app works currently. From what I see it should just make it work for non-root directory deployments.

**Comment by jamaljsr** [comment]
Ok, if you'd like to submit a PR with these changes, then i'll review it.

**Comment by dennisreimann** [comment]
What's the best way to get the app and dependencies running locally for development? I tried connecting the dev Docker images and Polar, but am struggling with that because of certificate issues.

**Comment by jamaljsr** [comment]
The best way to get it running locally is using testnet. You should be able to follow the [compile from source](https://github.com/lightninglabs/lightning-terminal/blob/master/doc/compile.md) doc for more details. What certificate  issue are you running into?

**Comment by guggero** [comment]
> An alternative option to customize the url path is the PUBLIC_URL environment variable when running yarn build. Unfortunately, this is also something that cannot be specified at runtime, so you wouldn't be able to use the lightninglabs/lightning-terminal docker image as is. You'd need to create a new docker image that uses one of these methods.

I discussed this offline with @dennisreimann and I think it is reasonable to just offer two "official" images under different tags. One that serves the UI from the root path and one that serves it from a specific sub path (for example `/lit`).

One thing that doesn't work correctly when using `PUBLIC_URL` is the browser history rewrite mechanism (not sure what the correct term is, the mechanism that is responsible for the virtual pages like `/pool`). That also needs to take the public URL into account. I think that's probably not a big issue to solve, @jamaljsr ?

The problem with the API calls remains, but I'm sure that can be solved somehow. I'm going to think on this a bit more.

**Comment by guggero** [comment]
I think I found a possible solution how an nginx can rewrite incoming grpc-web requests to be forwarded to LiT based on the `Content-Type`. This worked for me (in combination with building the static resources using `PUBLIC_URL=/lit/`:


```
http {
    map $content_type $lnd_backend {
      "application/grpc-web+proto" "172.17.0.1:8443"; # This is the host:port of the LiT container (in this example the docker host).
      default "localhost:10009"; # This is the host:port of the lnd host where all normal gRPC (non-grpc-web) calls are sent to.
    }

    server {
        listen 80;
        server_name localhost;
        
        location /lit {
            # This needs a slash at the end!
            proxy_pass https://172.17.0.1:8443/;
        }
        
        location ~* ^/lnrpc.Lightning/ {
            # This cannot have a slash at the end!
            proxy_pass https://$lnd_backend;
        }
        
        location ~* ^/looprpc.SwapClient/ {
            # This cannot have a slash at the end!
            proxy_pass https://$lnd_backend;
        }
        
        location ~* ^/poolrpc.Trader/ {
            # This cannot have a slash at the end!
            proxy_pass https://$lnd_backend;
        }
    }
}
```

**Comment by dennisreimann** [comment]
@guggero I think we should not go down the latter route, because it is a combination of having the path set on the one side, while still circumventing the path not being set for the API requests. For BTCPay this also might not work, as there are other apps using the gRPC API as well, which this might interfere with.

I think the best way to handle this would be that the app is agnostic to its root (or picking it up on startup/runtime). The asset paths can be changed to work that way via the `homepage` option (see above). The API requests should also use relative paths or the base path of the app should be set on startup/runtime -- this way we wouldn't need different Docker builds and no workarounds in the deployment (i.e. nginx).

**Comment by guggero** [comment]
> there are other apps using the gRPC API as well, which this might interfere with.

No, that's what the map at the beginning is for. Only LiT makes calls with `Content-Type: application/grpc-web+proto` while any other, normal, gRPC traffic will have `Content-Type: application/grpc`. So the requests will be forwarded either to LiT or to `lnd` depending on whether they come from LiT or not.

> The API requests should also use relative paths or the base path of the app should be set on startup/runtime

gRPC doesn't support relative paths for RPC requests. So this might not even be possible with the library we use.

**Comment by dennisreimann** [comment]
Alright, added a draft PR for the integration, which thanks to @guggero's snippet almost works.

With the current state there are only the path issues left to resolve.

For the asset paths I've found [nginx sub_filters as a workaround](https://github.com/btcpayserver/btcpayserver-docker/pull/512/files#diff-05200e2a470c28b099494cd0a09359a967606b7768dd50eaa6d83bfb72b68979R115), though these might be rather easy to eliminate via the `homepage` option. From what I've seen this option would not have a negative side effect for the app.

Frontend-wise the paths switch to the root paths (e.g. `/loop/` instead of `/lit/loop/`) on navigation. This might be solvable by setting the `PUBLIC_URL` as Oliver suggested.

@jamaljsr What are your thoughts on this?

**Comment by jamaljsr** [comment]
> For the asset paths I've found [nginx sub_filters as a workaround](https://github.com/btcpayserver/btcpayserver-docker/pull/512/files#diff-05200e2a470c28b099494cd0a09359a967606b7768dd50eaa6d83bfb72b68979R115), though these might be rather easy to eliminate via the `homepage` option. From what I've seen this option would not have a negative side effect for the app.
> 
> Frontend-wise the paths switch to the root paths (e.g. `/loop/` instead of `/lit/loop/`) on navigation. This might be solvable by setting the `PUBLIC_URL` as Oliver suggested.

I believe that setting `PUBLIC_URL` would help solve both of these issues, but you'd also need a code change for the second one. The magic-string paths specified in the [Routes.tsx](https://github.com/lightninglabs/lightning-terminal/blob/master/app/src/Routes.tsx) and [appView.ts](https://github.com/lightninglabs/lightning-terminal/blob/master/app/src/store/views/appView.ts#L49) would also need to be updated to include the `PUBLIC_URL` env value. I haven't tested myself but this seems doable.
