### ISSUE TITLE
Swap error: signing: rpc error: code = Unknown desc = permission denied

### ISSUE THREAD

**Issue by sendbitcoin** [lightninglabs/lightning-terminal#256]
lnd 0.13.1-beta.rc2

lit v0.5.0

windows

Loop out always fails with RPC error. I have plenty of outgoing capacity/channels and even with the minimum of 250k sats it doesnt work. In the past i have used a past version of lit to successfully make loopouts but now it doesnt work at all since upgrading lnd and lit.

Any ideas what i need to check and/or change?

> 2021-07-25 11:36:06.784 [INF] RPCS: Received new block notification: height=692576
> 2021-07-25 11:36:06.784 [INF] LOOP: Received block 692576
> 2021-07-25 11:36:06.784 [INF] LOOP: Received block 692576
> 2021-07-25 11:36:06.787 [INF] LOOP: 86848c Checking preimage reveal height 692655 exceeded (height 692576)
> 2021-07-25 11:36:06.787 [INF] LOOP: 5aad29 Checking preimage reveal height 692655 exceeded (height 692576)
> 2021-07-25 11:36:06.788 [INF] LOOP: 86848c Swap script confirmed on chain
> 2021-07-25 11:36:06.789 [INF] LOOP: 86848c Htlc tx 28665150029ee255551XXXXXXXXXXXXXXXXXXXXfb4ec674ebf18d at height 692576
> 2021-07-25 11:36:06.789 [INF] LOOP: 86848c Htlc value: 0.0025 BTC
> 2021-07-25 11:36:06.963 [INF] LOOP: 86848c Server update: SERVER_HTLC_CONFIRMED received, timestamp: 2021-07-25 11:36:08.598107516 +0200 CEST
> 2021-07-25 11:36:07.564 [INF] LOOP: 86848c Payment 210290ea38c6XXXXXXXXXXXXXXXXXX401816: state=SUCCEEDED
> 2021-07-25 11:36:08.540 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/ListAccounts
> 2021-07-25 11:36:08.757 [INF] LITD: Handling gRPC web request: /lnrpc.Lightning/GetInfo
> 2021-07-25 11:36:16.797 [ERR] LOOP: 86848c Swap error: signing: rpc error: code = Unknown desc = permission denied
> 2021-07-25 11:36:16.798 [INF] LOOP: 86848c Loop out swap state: FailTemporary
> 2021-07-25 11:36:16.800 [ERR] LOOP: Execute error: signing: rpc error: code = Unknown desc = permission denied

**Comment by guggero** [comment]
You need to re-generate lnd's macaroons if you upgraded from an older version.

**Comment by sendbitcoin** [comment]
> 
> 
> You need to re-generate lnd's macaroons if you upgraded from an older version.

>On startup, lnd checks to see if the admin.macaroon, readonly.macaroon and invoice.macaroon files exist. If they don't exist, lnd updates its database with a new macaroon ID, generates the three files admin.macaroon, readonly.macaroon and invoice.macaroon, all with the same ID. 

I stopped lnd. renamed and oved all the old macaroons in C:\Users\XXXX\AppData\Local\Lnd... but no new macaroons are created. am i doing this wrong?

**Comment by sendbitcoin** [comment]
> 
> 
> You need to re-generate lnd's macaroons if you upgraded from an older version.

After regenerating the macaroons all the loops with temporary failure switched to preimage revealed... seems to be fixed. closing
