### ISSUE TITLE
Node showing up as pending from a week on Terminal Web

### ISSUE THREAD

**Issue by noderunner11** [lightninglabs/lightning-terminal#258]
I am not very sure if this is the same GitHub page for Terminal Web as well, I could not find the other one. Please redirect me if I am wrong.

My node is showing up as pending from a week for some reason. 

https://terminal.lightning.engineering/#/

Pubkey: `02827ff9e6664c1608e1cb65182c73c68395cb079492a8a4482045c4561c5aa179`
https://amboss.space/node/02827ff9e6664c1608e1cb65182c73c68395cb079492a8a4482045c4561c5aa179

**Comment by guggero** [comment]
If you click on your node, you see that it doesn't pass the "Plenty of channels" check. Only channels of a certain age are counted so you just need to wait a few more days.
