### ISSUE TITLE
Loop Out consistent error

### ISSUE THREAD

**Issue by PLK2** [lightninglabs/lightning-terminal#263]
Lightning Terminal v0.5.0-alpha
LND v0.13.1-beta
Umbrel v0.4.1

When I select a specific channel for a loop out on Terminal, it fails, giving me this error:
<img width="353" alt="Screen Shot 2021-09-04 at 4 10 46 PM" src="https://user-images.githubusercontent.com/20099374/132107037-5817ddd1-0e4e-46dd-a656-6d77c68e1555.png">
There are plenty of sats in the channel.

If I select the same channel for the same loop out amount using Ride the Lightning, it works.

If I don't select a specific channel and allow Terminal to select for me, then the loop out appears to work.

**Comment by jamaljsr** [comment]
Would you mind sharing screenshots of the the confirmation screens in both LiT and RTL? You do not have to submit the swaps, I'm curious to see how the fees differ between the two apps.

**Comment by PLK2** [comment]
Here's the terminal error:
<img width="938" alt="Screen Shot 2021-09-07 at 10 42 40 AM" src="https://user-images.githubusercontent.com/20099374/132364475-70ce13e1-ed1b-44ae-bb03-5299f1befac2.png">
<img width="427" alt="Screen Shot 2021-09-07 at 10 42 51 AM" src="https://user-images.githubusercontent.com/20099374/132364489-3b29a07c-0924-4912-93f1-bd96be5fffeb.png">
<img width="342" alt="Screen Shot 2021-09-07 at 10 43 01 AM" src="https://user-images.githubusercontent.com/20099374/132364508-f96e54e9-3f55-4154-9a72-f94404f9eaac.png">

**Comment by PLK2** [comment]
This loop out also failed on RTL.
<img width="625" alt="Screen Shot 2021-09-07 at 10 45 04 AM" src="https://user-images.githubusercontent.com/20099374/132364734-ce9aeb99-9bd3-4bd6-bb62-bd4ca943a4b2.png">

**Comment by PLK2** [comment]
I guess something is wrong with the channel?

**Comment by PLK2** [comment]
Ok, I figured it out. It was an issue with my chain of channels. Fees weren't high enough or connections didn't exist.

I recommend providing more details and/or changing the language of the error message as that was throwing me way off.
