### ISSUE TITLE
Loop History - Error on status displayed

### ISSUE THREAD

**Issue by trigger67** [lightninglabs/lightning-terminal#270]
**Expected behavior**
I performed a loop in. It seems that is failed at start. And then went successfully.
I expect to see the swap as successfull in the _History_ page.

**Actual behavior**

In _History_ page I see my swap with status "Temporary Failure" and tooltip "The swap cannot continue due to an internal error. Manual intervention such as restart is required.

**To reproduce**

If I remember well, here is what happened :
I performed a loop in, on one particular channel.
I saw the HTLC was created.
And then the error described before appeared on the screen.

I then rebooted my computer, and I still see the issue.
But I looked at my channel, and I saw that the rebalanced have been performed!

**System information**

I installed loop (LIT) yesterday, and have not changed any configuration.
I run the last version of raspiblitz: 1.7.0
I have lnd 0.13.1-beta
And loop version 0.11.4-beta

The swap : 
_lit-loop swapinfo 553e93d4f9e6c93c427e66430382b60ccca5f734ff96d17dc26adc44b26eb2db_
```
{
    "amt": "xxx",
    "id": "553e93d4f9e6c93c427e66430382b60ccca5f734ff96d17dc26adc44b26eb2db",
    "id_bytes": "553e93d4f9e6c93c427e66430382b60ccca5f734ff96d17dc26adc44b26eb2db",
    "type": "LOOP_IN",
    "state": "FAILED",
    "failure_reason": "FAILURE_REASON_TEMPORARY",
    "initiation_time": "1633161734646390591",
    "last_update_time": "1633163292283374376",
    "htlc_address": "bc1xxxxxx",
    "htlc_address_p2wsh": "bc1xxxxxx",
    "htlc_address_np2wsh": "",
    "cost_server": "-xxx",
    "cost_onchain": "0",
    "cost_offchain": "0",
    "label": ""
}
```

Some logs : 

```
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.102 [INF] LOOP: Wait for first block ntfn
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.108 [INF] LOOP: Starting event loop at height 703164
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.108 [INF] LOOP: 553e93 Loop in swap state: InvoiceSettled
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.108 [INF] LOOP: 553e93 Register for htlc conf (hh=703159, txid=xxx)
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.272 [INF] LOOP: 553e93 P2WSH htlc confirmed
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.272 [INF] LOOP: 553e93 Subscribing to swap invoice 553e93d4f9e6c93c427e66430382b60ccca5f734ff96d17dc26adc44b26eb2db
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.283 [INF] LOOP: 553e93 Received swap invoice update: Settled
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.283 [ERR] LOOP: 553e93 Swap error: EOF
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.283 [INF] LOOP: 553e93 Loop in swap state: FailTemporary
Oct 02 09:28:12 raspberrypi litd[7694]: 2021-10-02 09:28:12.283 [ERR] LOOP: 553e93 could not get swap subscription: rpc error: code = Canceled desc = context canceled
```

**Comment by guggero** [comment]
This [error was fixed](https://github.com/lightninglabs/lightning-terminal/pull/248) with the latest LiT version 0.5.1-alpha, please upgrade your LiT installation.

**Comment by trigger67** [comment]
Alright, openoms told me it will be upgraded in the next version of raspiblitz.
Sorry and thank you!
