### ISSUE TITLE
UI - oops, that password is incorrect

### ISSUE THREAD

**Issue by MrPaz** [lightninglabs/lightning-terminal#279]
Pardon my ignorance, I am running LiT for the first time.  At startup I enter `litd --uipassword=<YOUR_UI_PASSWORD>` but  on the web UI at https://127.0.0.1:8443/ I enter <YOUR_UI_PASSWORD> and it tells me my pw is incorrect...  why?  or what pw am I supposed to use if not the one in the startup command?  lmk if there is a better place to get support - telegram, irc, etc.

![Screenshot from 2021-11-04 10-30-59](https://user-images.githubusercontent.com/35268901/140357921-5bbb1464-2b46-42e5-8781-629e2df3875a.png)

**Comment by guggero** [comment]
What version (commit) are you running?
Are you sure you don't have any special characters in your password that might be changed by your shell? And I assume you checked that you didn't type it incorrectly?
Do you see any error in the log?

If you continue to experience this, can you please open the debug tools of your browser (usually with the F12 key), and look in the network tab if the first ever call to `https://localhost:8443/lnrpc.Lightning/GetInfo` has any special response headers (for example `grpc-message`) that contain some detailed error message?

**Comment by MrPaz** [comment]
arghh, yes, I had special characters in my pw.  after I quit and restarted with a new --uipassword that didn't have any special characters, I logged in just fine. so it appears the shell must have changed the special characters as you mentioned. version 0.5.2 btw.

Thank you!

**Comment by guggero** [comment]
Okay, yeah, that happens some time.

Closing as this was related to the shell's handling of special characters.

**Comment by majjihari** [comment]
> Okay, yeah, that happens some time.
> 
> Closing as this was related to the shell's handling of special characters.

I still see this error though i set very simple password without special characters. And also http://localhost/lnrpc.Lightning/GetInfo response is success

![image](https://user-images.githubusercontent.com/2501864/205946005-a28fdd46-f212-45c0-a3b6-207e96ba66c7.png)

**Comment by guggero** [comment]
Check your litd log, this error also happens if litd isn't fully started up yet (maybe because of an error).
