### ISSUE TITLE
How to copy `admin.macaroon` to my local machine?

### ISSUE THREAD

**Issue by LAMike310** [lightninglabs/lightning-terminal#285]
I'm trying to connect to data on my cloud node from my local machine. I copied the `tls.cert` locally, and then I tried to copy the macaroon text through VIM, but when I copy and paste from VIM, I don't think the correct data is being transferred over. When I run `xxd -p -c2000 admin.macaroon` on my local machine and cloud node, the length doesn't match up. 

One way I tried to copy over the macaroon was to take the hex output and remake it into a string w/ this script:

```
const fs = require('fs');

const convert = (from, to) => str => Buffer.from(str, from).toString(to)
const utf8ToHex = convert('utf8', 'hex')
const hexToUtf8 = convert('hex', 'utf8')
const macaroon_hex = '......'
fs.writeFileSync('./admin.macaroon', hexToUtf8('{macaroon_hex}'))
```

The hex didn't match up either, but is this still a valid way of copying over the `.macaroon` file?

**Comment by guggero** [comment]
That's a weird way of copying a file. Did you try something like `scp`?

Anyway, you can use `xxd` for doing the reverse as well:

```
# cloud machine
xxd -p -c9999 admin.macaroon > admin.hex

# local machine
cat admin.hex | xxd -p -r > admin.macaroon
```

Closing as this isn't exactly an issue with `lnd`. Please use the [Discussions](https://github.com/lightninglabs/lightning-terminal/discussions) section or join our [Slack server](https://lightning.engineering/slack.html) for troubleshooting questions.
