### ISSUE TITLE
Lit fails to connect to terminal web with a pairing phrase

### ISSUE THREAD

**Issue by agd-media** [lightninglabs/lightning-terminal#286]
"Failed to connect" is the only info I get. I tried various times to create a new passphrase without success.

**Comment by jamaljsr** [comment]
Can you please provide the exact error message that is displayed or a screenshot of what you are seeing on the screen?

**Comment by agd-media** [comment]
It only says: "Failed to connect". Nothing more.

**Comment by jamaljsr** [comment]
This error message is very vague. This could be produced by the browser due to a failure connecting to the litd backend. I need more information to help troubleshoot. Are you using tor browser to view to the Terminal app? Do you receive any errors when you visit the Pool or Loop pages? Can you open the browser Dev Tools console and see what error is displayed there?

**Comment by agd-media** [comment]
I tried with Firefox and Tor browser. Both show the same error. Clicking on Loop sends me to https://terminal.lightning.engineering/#/connect/pair . Probably because it needs to connect to the server.
Tor shows only 
Uncaught TypeError: p.wasmClientDisconnect is not a function
    value wasm.ts:121
    value lnd.ts:64
    e lnd.ts:44
    
    Firefox shows nothing.
![literror](https://user-images.githubusercontent.com/9844171/144244404-246a85f9-0507-44e9-8787-46c0894fb631.png)

**Comment by agd-media** [comment]
I tried reinstalling but the error persists

**Comment by jamaljsr** [comment]
Can you share the full browser console logs, and also a screenshot of the Network tab. I suspect the the LNC wasm file isn't being loaded properly.

**Comment by Mowgli34** [comment]
The exact same issue her - tried Chrome 7 Tor, with numerous attempts to reload page, and generate new pairing phrases - samme error all the time. Funnily enough I had it working in Chrome on first attempt a few days back, but since then, only this error - very frustrating

**Comment by jamaljsr** [comment]
Can you provide the full browser console logs?

**Comment by Mowgli34** [comment]
Sure - seems like a loop as this just keeps being added to the console over and over again
[image.png]

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jamaljsr** [comment]
Did you intend to attach the logs? I cannot see them.

**Comment by Mowgli34** [comment]
Isn’t there a screenshot of the log? I see it in my outbox

Sent from ProtonMail for iOS

Til tor., dec. 30, 2021 kl. 21:53, Jamal James ***@***.***> skrev:

**Comment by jamaljsr** [comment]
No, the screenshot is not attached. Can you post directly to github and paste the text in?

**Comment by Mowgli34** [comment]
Sure here is an excerpt, as it apparently loops endlessly:

2021-12-30 19:18:00.938 [DBG] WASM: WASM client ready for connecting
wasm_exec.js:51 2021-12-30 19:18:07.843 [DBG] MBOX: New client conn, read_stream=5e5b82924a8ed97671ec86129449952a88ab92cdfd7b533cd1442e7a2070c205be7d7291f38fedcc4998d3efd7e7cbc82ef08aa8beb00f923c6f8dd23263e1fa, write_stream=5e5b82924a8ed97671ec86129449952a88ab92cdfd7b533cd1442e7a2070c205be7d7291f38fedcc4998d3efd7e7cbc82ef08aa8beb00f923c6f8dd23263e1fb
wasm_exec.js:51 2021-12-30 19:18:07.844 [DBG] GRPC: [core] parsed scheme: ""
wasm_exec.js:51 2021-12-30 19:18:07.845 [DBG] GRPC: [core] scheme "" not registered, fallback to default scheme
wasm_exec.js:51 2021-12-30 19:18:07.846 [DBG] GRPC: [core] ccResolverWrapper: sending update to cc: {[{mailbox.terminal.lightning.today:443  <nil> 0 <nil>}] <nil> <nil>}
wasm_exec.js:51 2021-12-30 19:18:07.847 [DBG] GRPC: [core] ClientConn switching balancer to "pick_first"
wasm_exec.js:51 2021-12-30 19:18:07.848 [DBG] GRPC: [core] Channel switches to new LB policy "pick_first"
wasm_exec.js:51 2021-12-30 19:18:07.850 [DBG] GRPC: [core] Subchannel Connectivity change to CONNECTING
wasm_exec.js:51 2021-12-30 19:18:07.851 [DBG] WASM: WASM client connected to RPC
wasm_exec.js:51 2021-12-30 19:18:07.851 [DBG] GRPC: [core] Subchannel picks a new address "mailbox.terminal.lightning.today:443" to connect
wasm_exec.js:51 2021-12-30 19:18:07.852 [DBG] GRPC: [core] pickfirstBalancer: UpdateSubConnState: 0x1a69960, {CONNECTING <nil>}
wasm_exec.js:51 2021-12-30 19:18:07.855 [DBG] GRPC: [core] Channel Connectivity change to CONNECTING
wasm_exec.js:51 2021-12-30 19:18:08.364 [INF] WASM: Calling 'lnrpc.Lightning.GetInfo' on RPC with request {}
wasm_exec.js:51 2021-12-30 19:18:08.594 [DBG] MBOX: Client: Send mailbox created
wasm_exec.js:51 2021-12-30 19:18:09.277 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:09.444 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:433 WebSocket connection to 'wss://mailbox.terminal.lightning.today/v1/lightning-node-connect/hashmail/receive?method=POST' failed: 
syscall/js.valueNew @ wasm_exec.js:433
$func1346 @ wasm-client.wasm:0x123c12
$func1323 @ wasm-client.wasm:0x121afe
$func10744 @ wasm-client.wasm:0xaa167d
$func10789 @ wasm-client.wasm:0xaa8e98
$func10788 @ wasm-client.wasm:0xaa88f8
$func15156 @ wasm-client.wasm:0xecbfda
$func1111 @ wasm-client.wasm:0x104621
$resume @ wasm-client.wasm:0x104602
_resume @ wasm_exec.js:588
(anonymous) @ wasm_exec.js:314
wasm_exec.js:51 2021-12-30 19:18:12.105 [DBG] MBOX: Client: error creating receive socket failed to WebSocket dial "wss://mailbox.terminal.lightning.today:443/v1/lightning-node-connect/hashmail/receive?method=POST": WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:51 2021-12-30 19:18:12.626 [DBG] MBOX: Client: got failure on send socket, re-trying: failed to write: WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:433 WebSocket connection to 'wss://mailbox.terminal.lightning.today/v1/lightning-node-connect/hashmail/receive?method=POST' failed: 
syscall/js.valueNew @ wasm_exec.js:433
$func1346 @ wasm-client.wasm:0x123c12
$func1323 @ wasm-client.wasm:0x121afe
$func10744 @ wasm-client.wasm:0xaa167d
$func10789 @ wasm-client.wasm:0xaa8e98
$func10788 @ wasm-client.wasm:0xaa88f8
$func15156 @ wasm-client.wasm:0xecbfda
$func1111 @ wasm-client.wasm:0x104621
$resume @ wasm-client.wasm:0x104602
_resume @ wasm_exec.js:588
(anonymous) @ wasm_exec.js:314
wasm_exec.js:51 2021-12-30 19:18:14.779 [DBG] MBOX: Client: error creating receive socket failed to WebSocket dial "wss://mailbox.terminal.lightning.today:443/v1/lightning-node-connect/hashmail/receive?method=POST": WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:51 2021-12-30 19:18:15.441 [DBG] MBOX: Client: Send mailbox created
wasm_exec.js:51 2021-12-30 19:18:17.435 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:17.593 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:51 2021-12-30 19:18:19.462 [DBG] MBOX: Client: got failure on send socket, re-trying: failed to write: WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:51 2021-12-30 19:18:20.236 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:20.397 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:51 2021-12-30 19:18:22.152 [DBG] MBOX: Client: Send mailbox created
wasm_exec.js:51 2021-12-30 19:18:22.892 [DBG] GRPC: [core] Channel Connectivity change to SHUTDOWN
wasm_exec.js:51 2021-12-30 19:18:22.893 [DBG] GRPC: [core] Subchannel Connectivity change to SHUTDOWN
wasm_exec.js:433 WebSocket connection to 'wss://mailbox.terminal.lightning.today/v1/lightning-node-connect/hashmail/receive?method=POST' failed: 
syscall/js.valueNew @ wasm_exec.js:433
$func1346 @ wasm-client.wasm:0x123c12
$func1323 @ wasm-client.wasm:0x121afe
$func10744 @ wasm-client.wasm:0xaa167d
$func10789 @ wasm-client.wasm:0xaa8e98
$func10788 @ wasm-client.wasm:0xaa88f8
$func15156 @ wasm-client.wasm:0xecbfda
$func1111 @ wasm-client.wasm:0x104621
$resume @ wasm-client.wasm:0x104602
_resume @ wasm_exec.js:588
(anonymous) @ wasm_exec.js:314
wasm_exec.js:51 2021-12-30 19:18:23.063 [DBG] MBOX: Client: error creating receive socket failed to WebSocket dial "wss://mailbox.terminal.lightning.today:443/v1/lightning-node-connect/hashmail/receive?method=POST": WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:51 2021-12-30 19:18:25.727 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:25.896 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:51 2021-12-30 19:18:26.174 [DBG] MBOX: Client: got failure on send socket, re-trying: failed to write: WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:51 2021-12-30 19:18:28.549 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:28.720 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:51 2021-12-30 19:18:29.219 [DBG] MBOX: Client: Send mailbox created
wasm_exec.js:51 2021-12-30 19:18:31.367 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:31.533 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:51 2021-12-30 19:18:33.251 [DBG] MBOX: Client: got failure on send socket, re-trying: failed to write: WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:51 2021-12-30 19:18:34.198 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:34.368 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:433 WebSocket connection to 'wss://mailbox.terminal.lightning.today/v1/lightning-node-connect/hashmail/send?method=POST' failed: 
syscall/js.valueNew @ wasm_exec.js:433
$func1346 @ wasm-client.wasm:0x123c12
$func1323 @ wasm-client.wasm:0x121afe
$func10744 @ wasm-client.wasm:0xaa167d
$func10789 @ wasm-client.wasm:0xaa8e98
$func10788 @ wasm-client.wasm:0xaa88f8
$func15157 @ wasm-client.wasm:0xeccea5
$func1111 @ wasm-client.wasm:0x104621
$resume @ wasm-client.wasm:0x104602
_resume @ wasm_exec.js:588
(anonymous) @ wasm_exec.js:314
wasm_exec.js:51 2021-12-30 19:18:35.942 [DBG] MBOX: Client: error creating send socket failed to WebSocket dial "wss://mailbox.terminal.lightning.today:443/v1/lightning-node-connect/hashmail/send?method=POST": WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:433 WebSocket connection to 'wss://mailbox.terminal.lightning.today/v1/lightning-node-connect/hashmail/receive?method=POST' failed: 
syscall/js.valueNew @ wasm_exec.js:433
$func1346 @ wasm-client.wasm:0x123c12
$func1323 @ wasm-client.wasm:0x121afe
$func10744 @ wasm-client.wasm:0xaa167d
$func10789 @ wasm-client.wasm:0xaa8e98
$func10788 @ wasm-client.wasm:0xaa88f8
$func15156 @ wasm-client.wasm:0xecbfda
$func1111 @ wasm-client.wasm:0x104621
$resume @ wasm-client.wasm:0x104602
_resume @ wasm_exec.js:588
(anonymous) @ wasm_exec.js:314
wasm_exec.js:51 2021-12-30 19:18:37.028 [DBG] MBOX: Client: error creating receive socket failed to WebSocket dial "wss://mailbox.terminal.lightning.today:443/v1/lightning-node-connect/hashmail/receive?method=POST": WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""
wasm_exec.js:51 2021-12-30 19:18:38.593 [DBG] MBOX: Client: Send mailbox created
wasm_exec.js:51 2021-12-30 19:18:39.691 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:39.855 [DBG] MBOX: Client: got error message from receive socket: {"code":2,"message":"stream not found","details":[]}
wasm_exec.js:51 2021-12-30 19:18:42.524 [DBG] MBOX: Client: receive mailbox initialized
wasm_exec.js:51 2021-12-30 19:18:42.627 [DBG] MBOX: Client: got failure on send socket, re-trying: failed to write: WebSocket closed: unclean connection close: status = StatusAbnormalClosure and reason = ""

**Comment by guggero** [comment]
Sounds like LiT isn't ready to serve the connection attempt. Can you try restarting LiT and creating a new pairing phrase/session please?

**Comment by Mowgli34** [comment]
I actually got it working because I had to restart my node - thanks for getting back ;o)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by guggero** [comment]
Okay, thanks for the update. Closing the issue since a restart resolved it.
