### ISSUE TITLE
Unable to start litd, "timed out after 5s when trying to obtain exclusive lock"

### ISSUE THREAD

**Issue by finned-palmer** [lightninglabs/lightning-terminal#297]
**Expected behavior**
litd should start

**Actual behavior**

litd fails to start and produces this message:
`error while trying to open /home/[redacted]/.pool/mainnet/pool.db: timed out after 5s when trying to obtain exclusive lock - make sure no other pool daemon process (standalone or embedded in lightning-terminal) is running
2021-12-16 11:18:04.069 [INF] SGNL: Shutting down...`

There is no other pool process running.

This has happened before and I just rm -rf'd the .pool folder since I wasn't using pool, but I just started using pool this week and have deposited some money into an account. I'm worried that if I use that method again I might lose access to my funds.

Any idea what's going on?

**Comment by guggero** [comment]
If you get that error then another process must be locking the pool database. Are you really sure no `poold` or `litd` process is running somewhere in the background?

**Comment by finned-palmer** [comment]
Oof, after searching a bit more it turns out there was. Sorry about that, thanks for the quick response though!

**Comment by finned-palmer** [comment]
One other issue (sorry, I know that github issues is not for troubleshooting/support normally):

I deleted the macaroon.db file in the .pool/mainnet directory (I thought maybe if I delete it that will remove the lock and a new one would get created) and now I'm seeing an error in the pool dashboard on lightning terminal: "invalid macaroon verification failed". Did I hose myself here or can I fix this?

**Comment by guggero** [comment]
If you remove the macaroon DB file you'll invalidate all existing macaroons. So you need to remove the `pool.macaroon` as well, then restart Pool to re-generate both files (the DB and the actual macaroon).

**Comment by finned-palmer** [comment]
Got it, thanks again!
