### ISSUE TITLE
installed over umbrel : port not open ,and now i cant login in in umbrel over putty ..

### ISSUE THREAD

**Issue by flatounet** [lightninglabs/lightning-terminal#302]
i got last umbrel : 0.4.10
installed from app store  ; ok
started from app ( in umbrel ) : new page open : 192.168.0.10 : connection refused.

i go putty , i put my login , password : refused now :(
no ip error : i got internet page with working umbrel , i have IP
no error from login pass , writed from copy / past ( im on windws here )
and im logged in before without probmeme ...

so now , cant connect to raspberry
no log to know what's wrong :(
and just interface to umbrel :(

**Comment by jamaljsr** [comment]
This sounds like an Umbrel configuration issue or may even be hardware related. This isn't an issue with Terminal. You should reach out to the Umbrel team for assistance.
