### ISSUE TITLE
lost pool account and funding

### ISSUE THREAD

**Issue by xtophe632** [lightninglabs/lightning-terminal#304]
today when opening lightning terminal I can't find my account and the two orders I made have disappeared (makes sense if my account is closed) what is the reason and what should I do to recover?

**Comment by guggero** [comment]
Did you re-install LiT in Umbrel? You'll need to run `pool accounts recover` on the command line to get the accounts back if you deleted the data (by re-installing LiT).

**Comment by xtophe632** [comment]
Thank you , and by the way good time to wish you a happy new year.
I will reinstall LiT and run the command.

**Comment by guggero** [comment]
> Thank you , and by the way good time to wish you a happy new year.

Thanks, same to you!

If you have LiT already installed, don't re-install! That will delete the data again. Just run the command. If you mean you already uninstalled LiT then yes, you'll need to install it again.

**Comment by xtophe632** [comment]
yes I was not clear but after a second thought I understood what you meant :-)

**Comment by xtophe632** [comment]
hello , the pool command seems not to be present, maybe I don't use the right command line or don't go in the correct directory?

**Comment by guggero** [comment]
I can't answer that question since you chose not to give any additional information (e.g. what node software you're running, Umbrel, RaspiBlitz, myNode). You'll need to find out what the command is called or where it is located in the documentation of your node software or through their support.

**Comment by xtophe632** [comment]
true, sorry. I will go to umbrel support. here is my configuration
umbrel on an intel computer under ubuntu, so using docker containers.
I guess using the pool command in the ubuntu command line is not the right way to do, and I am not savvy enough to know how to pass the command to the lightning terminal container. If you have the info at hand, tahnk you for letting me know, if not thank you for your help so far, I see where the problem is at least.
Best

**Comment by guggero** [comment]
From https://www.reddit.com/r/getumbrel/comments/op0j80/unable_to_close_account_on_lightning_pool/:

```
1> First SSH into umbrel

# ssh umbrel@umbrel.local

2> Find the process ID of LN terminal:

#docker ps

3> Open the LN Docker

#docker exec -it a5c33b1e0d57 /bin/bash
```

Then

```
pool --tlscertpath=/data/.lit/tls.cert --rpcserver=localhost:8443 --macaroonpath=/data/.pool/mainnet/pool.macaroon accounts recover
```

**Comment by xtophe632** [comment]
excellent, worked like  a charm. thank you and sorry for not providing the useful info in the first place.

Best Regards
