### ISSUE TITLE
Match max miner setting to CLI config in Loop Out

### ISSUE THREAD

**Issue by alexbosworth** [lightninglabs/lightning-terminal#307]
The CLI will set the max miner fee to 250x the current fee level and this or higher is advisable for all clients

The max miner fee is currently intended as only a sanity check and not a fee control system. Setting the max miner fee to the current fee level will have adverse impact on the Loop Out experience in the case that the chain backend fee estimation increases over the duration of the swap.

The GUI for Loop Out should match the API access pattern of the CLI to maintain consistency in behavior.

**Comment by jamaljsr** [comment]
Also, additional context is in https://github.com/lightninglabs/lightning-terminal/issues/303#issuecomment-1002202213
