### ISSUE TITLE
v0.6.3-alpha unable to fetch... rpc error: code = Unimplemented desc = unknown service poolrpc.Trader

### ISSUE THREAD

**Issue by dekdynamics** [lightninglabs/lightning-terminal#329]
I updated to v0.6.3-alpha today and cannot use the Pool page at https://terminal.lightning.engineering/#/pool  Connecting to the Dashboard seems fine, but once I select Pool, I get a sidebar full of errors like:

`UNABLE TO FETCH ORDERS rpc error: code = Unimplemented desc = unknown service poolrpc.Trader`

The interface never finishes loading after that. The Loop page has a similar issue, but there is only one error card instead of multiple. The data eventually loads in Loop.

My upgrade procedure from the previous version was:

`git checkout v0.6.3-alpha`
`make install`

I run litd in a screen session:  `litd --uipassword=something`
And generate a connect string: `litcli --lndtlscertpath ~/.lit/tls.cert sessions add --label="default"`

Then I used https://terminal.lightning.engineering/ and the Connect my node button.

**Actual behavior**

Pool error:

![image](https://user-images.githubusercontent.com/81862609/154388553-e0fa8e37-63f0-4cde-85c6-92d2c9b67472.png)

Loop error:

![image](https://user-images.githubusercontent.com/81862609/154388500-a03ba7d2-c8c4-442f-ade4-0064d4937d7a.png)

**To reproduce**

I can reproduce the issue every time.

**System information**

I have lnd release v0.14.2-beta installed, and I used the guide here to install litd: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit#docs-internal-guid-ae172929-7fff-f9d0-7921-e6f8acc92f53

The version is latest release from git (v0.6.3-alpha), and built from source. I also tried downloading the binaries (lightning-terminal-linux-arm64-v0.6.3-alpha.tar.gz), and I have the same issue. 

The system architecture is ARM64:

`Linux hostname 5.11.0-1027-oracle #30~20.04.1-Ubuntu SMP Thu Jan 13 09:43:40 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

OS is Ubuntu: `DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"`

The only looks that looks like an error is this:

`2022-02-17 01:47:00.277 [WRN] GRPC: [transport] transport: http2Server.HandleStreams failed to read frame: error decrypting payload: error reading from go-back-n: cannot receive, gbn exited`

**Comment by guggero** [comment]
Hmm, it looks like something broke with the update. I was able to reproduce the error. Going to look into it.

**Comment by dekdynamics** [comment]
A few more odd lines from overnight:
```
2022-02-17 07:43:51.975 [ERR] AUCT: [/poolrpc.ChannelAuctioneer/SubscribeBatchAuction]: rpc error: code = Unavailable desc = error reading from server: read tcp 10.0.0.82:43384->34.216.42.11:12010: read: connection reset by peer
2022-02-17 07:43:51.978 [ERR] AUCT: Server connection error received: rpc error: code = Unavailable desc = error reading from server: read tcp 10.0.0.82:43384->34.216.42.11:12010: read: connection reset by peer
2022-02-17 07:43:51.978 [ERR] RPCS: Error in server stream: server sent unexpected error
2022-02-17 07:43:51.978 [ERR] AUCT: Error in stream, trying to reconnect: server sent unexpected error
2022-02-17 07:43:57.658 [INF] AUCT: Successfully connected to auction server
2022-02-17 07:43:58.987 [ERR] RPCS: Unknown server error: %v server sent unexpected error
```
