### ISSUE TITLE
Can't Find "Recommended Channels"

### ISSUE THREAD

**Issue by jquiros2** [lightninglabs/lightning-terminal#330]
Our node passes all health checks, but we can't find where the "recommended channels" are in terminal web lightning.
Any conditions necessary for this to show?  

https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/recommended-channels

**Comment by levmi** [comment]
Thanks for filing an issue. This is actually the intended behavior at the moment. Once a node passes all health checks and becomes a "Good" node, we no longer show recommended channels. Recommended channels are meant to be helpful to nodes as they onboard to become quality, good nodes. Once they reach that state, it's more difficult to make relevant, helpful channel recommendations. It's possible that as we improve the channel recommendations we introduce them for good nodes. But, for now, this is the intended behavior.

**Comment by jquiros2** [comment]
Perfect, thank you 👍🏽👍🏽👍🏽
