### ISSUE TITLE
Missing container image for arm64 architecture

### ISSUE THREAD

**Issue by johnnyasantoss** [lightninglabs/lightning-terminal#335]
**Is your feature request related to a problem? Please describe.**

Yes! There's no image to `arm64` (raspberry) so when trying to pull `lightninglabs/lightning-terminal` it fails.

```
$ docker-compose up litd
Pulling litd (lightninglabs/lightning-terminal:)...
ERROR: manifest for lightninglabs/lightning-terminal:latest not found: manifest unknown: manifest unknown
```
I know that lnd builds images for `arm64` arch. Are there any plans to support it in this project as well?

**Comment by guggero** [comment]
There is no `latest` build. You need to specify a version. There is an ARM64 build of `v0.6.4-alpha`: https://hub.docker.com/layers/lightninglabs/lightning-terminal/v0.6.4-alpha/images/sha256-5dc063001add6bcd54d9b1acbe03c72580517e71afbc55b626d971fc6c4a1d8c?context=explore
