### ISSUE TITLE
Difficulty recovering lightning pool account after update of lightning terminal

### ISSUE THREAD

**Issue by domesticblend** [lightninglabs/lightning-terminal#352]
Hello,

I have an umbrel. 

On 4/10/2022 I created a Lightning Pool account inside Lightning terminal by funding it with 5000000satoshis.

I then tried to initiate an ASK order for 1000000satoshis and I got a message that said my Lightning Terminal version was too old. Indeed it was not the most current version.

I uninstalled and reinstalled Lightning Terminal to get the latest version

Now my account and 5000000satoshis are gone at Lightning Pool is asking me to open a new account.

I understand that there is a procedure for account recovery, possibly more than one. 
I have tried doing some SSH work as described here: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery

I'm not able to get it to work.
I have posted a similarly in the community.getumbrel.com system, but I've not heard back from them yet. 
I feel compelled to try to resolve the issue as quickly as possible so I'm reaching out here to see if I can get some assistance in recovering my lightning pool account on my umbrel.

I have lot's of screenshots and more information available on request.

**Comment by domesticblend** [comment]
FYI, my latest attempt:
umbrel@umbrel:~ $ docker exec -it 55065ce08f71 /bin/bash
bash-5.1$ pool --tlscertpath "/data/.lit/tls.cert" --rpcserver localhost:8443 --macaroonpath "/data/.pool/mainnet/pool.macaroon" accounts recover
[pool] rpc error: code = Unknown desc = recovery already in progress

Last night I noticed it used the wrong "trader key" - e.g. see attached image.
I'm confused where it says "could not recover account 02ab6c ... . " as this is not my "trader key" and therefore I assume not my account that it is trying to recover. 

![LIGHTNINGPOOLsshwork1](https://user-images.githubusercontent.com/103458559/162830884-191bfe31-5ca1-4c7b-b9f8-d02eaf3776df.PNG)

**Comment by positiveblue** [comment]
Hello @domesticblend, just to be 100% sure,  you are using the same LND backend node right?

**Comment by domesticblend** [comment]
Apologies, but I don't know what that means - "LND backend node". 
I haven't changed much on my node/umbrel in the last 24 hours or so since I reinstalled the Lightning Terminal app on my umbrel and lost the account.

**Comment by domesticblend** [comment]
And . . . . please excuse my ignorance

**Comment by positiveblue** [comment]
No problem at all, LND backend node => you are using the Pool with the same lightning node that you created the account with.
It looks like you are not able to try the recovery process more than once because of a non-related bug (I already created a  [PR in Pool with the fix](https://github.com/lightninglabs/pool/pull/355))

Can you restart the lightninglabs terminal container and try to run the recovery command again?

**Comment by domesticblend** [comment]
Thanks so much for helping me out!

I am indeed using the same lightning node that I created the account with. 

I do not know how to "restart the lightninglabs terminal container." - Would you mind doing a step by step with me on this one?

I am capable of running the recovery command again. However, again, I'd prefer if you walk me through it ;)

I have very basic SSH skills, but I am working on it . . .

**Comment by domesticblend** [comment]
FYI, I saved quite as much data as I could about this issue . . I have several images, details from RTL, debug logs . .. .images of the original account . . .   trader key etc . . .

**Comment by positiveblue** [comment]
Are you in [LL slack](https://join.slack.com/t/lightningcommunity/shared_invite/zt-14t8nv2vn-242LpFsrlA44uur1QeAAjg)? 
Join and write in the #pool channel, I will DM and help you there.

**Comment by domesticblend** [comment]
I just created a slack account and joined the #pool channel - Thanks again.

**Comment by positiveblue** [comment]
Fixed. The server returned an unrelated error the first time that he retried to run a recovery and he was unable to re run it because the rpc server did not marked the recovery process as done in case of failure (so the user was not able to run a new one).

This can be fixed by restarting the server/container + running the recovery process again (fixed in Pool [#355](https://github.com/lightninglabs/pool/pull/355))
