### ISSUE TITLE
Possible to run lightning-terminal only for lightning-node-connect?

### ISSUE THREAD

**Issue by neb-b** [lightninglabs/lightning-terminal#359]
I'm attempting to get the local lightning-node-connect stack running on my machine and am having issues connecting lightning-terminal to my standalone regtest lnd process. I believe it is because I haven't correctly setup the config for additional lightning-terminal services.

Is setup for every lightning-terminal service (loop, pool, faraday) needed to properly run lightning-terminal locally?

Currently the only values I have set in my `lit.conf` are
```
httpslisten=0.0.0.0:8443
lnd-mode=remote
network=regtest
uipassword={password}
remote.lit-debuglevel=debug
remote.lnd.macaroonpath=/{filepath}/admin.macaroon
remote.lnd.tlscertpath=/{filepage}/tls.cert
```

It seems like the beginning of startup is working correctly but fails with:
`no swap server address specified`

full startup logs here:
https://gist.github.com/neb-b/e992d115010e6433bc14b9fc5808f8df

Are there any docs for the minimum service setup needed if I only want to use `lightning-node-connect`?

**Comment by vafanassieff** [comment]
Hey

How did you manage to run lit only in regtest ?

I'm trying to start a loop server for regtest but it's not working either :(

**Comment by jamaljsr** [comment]
Unfortunately, it is not possible to run `litd` on regtest today because you'd need to run the Pool auctioneer server which is not open source. You'll need to use `litd` on testnet or signet to do your testing.

**Comment by vafanassieff** [comment]
Hey, thanks for the quick reply, I managed to start `litd` on regtest by using :

-  `lightninglabs/loopserver:v0.9.52-beta` as a loopserver
- `test.pool.lightning.finance:12010` as auction server (pool didn't complain about the server)
-
