### ISSUE TITLE
cannot set a lightning pool account

### ISSUE THREAD

**Issue by xtophe632** [lightninglabs/lightning-terminal#361]
I closed my previous account and now can't open a new one.

account status shows recovery failed. 
![Capture d’écran 2022-05-05 à 13 47 55](https://user-images.githubusercontent.com/75199564/166917316-d427cd4b-8c94-4cf9-98d5-0508e10ffd1d.png)

how can I move past this?

Best Regards

**Comment by levmi** [comment]
Is this through Lightning Terminal on the web (terminal.lightning.engineering) or litd? It looks like it says you have an available balance. Can you take actions like submitting asks or bids and just not fund the account? Any more details would be helpful. Thanks!

**Comment by xtophe632** [comment]
thank you. I use litd out of an umbrel configuration. I can't access the ask or bid buttons. I received the funds on chain when I closed my account. so I should not see any more available balance. does this help?
Best

**Comment by xtophe632** [comment]
maybe uninstalling and reinstalling the app would reset?

**Comment by levmi** [comment]
Don't uninstall and reinstall just yet. That can cause a whole set of other issues. Let me dig into this a bit more and get back to you with a potential solution.

**Comment by xtophe632** [comment]
ok thank you. on european time so will be off for a couple hours. Best

**Comment by levmi** [comment]
I'm not sure how you initially got into this state. But, I think the best option now is to attempt an account recovery using this guide: https://docs.lightning.engineering/lightning-network-tools/pool/account_recovery

**Comment by xtophe632** [comment]
i don’t know either, but thank you for the doc i will follow the guide.

**Comment by guggero** [comment]
@xtophe632 where you able to resolve this problem?

**Comment by xtophe632** [comment]
yes thank you. honestly your doc didn’t fix the problem, and I finally uninstalled reinstalled and it worked like a charm. I now have closed the account, because i am a little bit disappointed by the lack of traction. but no more technical issues.

**Comment by guggero** [comment]
Thanks for the feedback.

By "lack of traction", you mean order book/batch activity?

Closing as initial issue is fixed.

**Comment by xtophe632** [comment]
yes exactly, difficult to understand if you really have demand/offer.
