### ISSUE TITLE
ui: channels should be grouped/collapsed based on the node key/id

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/lightning-terminal#37]
Today in the network, it's possible to open up many channels to a single node. As a result, if a loop is initiated that ends up traversing that node, we don't have direct control over which channel is used, since the end node is able to select which channel it _wants_ to use. Therefore any operations which select one channel (out of many) for a single node, should also grow to select all the other channels for that node. 

There're a few ways to do this, and this may require another brief UI iteration. One idea that pops into mind is to collapse (group) all channels belonging to a target node in the UI. This grouped channel would appears as though it's a single channel, as we would sum up all balance information for that groups of channels.

**Comment by levmi** [comment]
This is done in Terminal Web UI. Gonna close this issue given that.
