### ISSUE TITLE
Failed Loop

### ISSUE THREAD

**Issue by Play4Adv** [lightninglabs/lightning-terminal#374]
I am getting the following message: "The swap cannot continue due to an internal error. Manual intervention such as a restart is required." My coins show as unsettled. How do I do a restart?

**Comment by jsmalaga** [comment]
Hi,
I did purchase a channel and I am getting inbound traffic via the node "Zerofeerouting" and outbound traffic via another channel i have open "ln.nicehash.com".
This is causing me a problem.
The Local liquidity in my channel "ln.nicehash.com" drain very fast and the routing/Forwarding stops!

I am trying to rebalance "Loop in" but with no success.
![image](https://user-images.githubusercontent.com/19676380/173340310-5f321806-a500-4440-a6e2-538906ba47aa.png)
![Loop in Stuck in HTLC Published](https://user-images.githubusercontent.com/19676380/173340422-6084433b-197c-4513-987f-0f5e35aa188b.PNG)

Is there any way to config and force the routing in/out via the same node "Zerofeerouting" ?
How could auto rebalance my outbound node "ln.nicehash.com" to keep liquidity high?
Thanks,

**Comment by guggero** [comment]
@Play4Adv assuming from your reaction to my comment the restart seems to have fixed the issue for you?
Going to close the issue, please comment if unresolved with the restart.

@jsmalaga please open a separate issue for your problem (or problems, sounds like more than one issue/question).
