### ISSUE TITLE
Lightning Terminal 0.7 working, but lncli shows lnd 0.14.3

### ISSUE THREAD

**Issue by pleb4868** [lightninglabs/lightning-terminal#409]
**Expected behavior**

"lncli getifo" to return same version as "litd --lnd.version"

**Actual behavior**

Upgraded lightning terminal to the latest version 0.7.0-alpha which includes lnd v0.15.0, but various tools show my lnd version as v0.14.3
"litd --lnd.version" returns
litd version 0.15.0-beta commit=lightning-terminal-v0.7.0-alpha

but "lncli getinfo" returns
`
{
"version": "0.14.3-beta commit=v0.14.3-beta",
.
.
.
}

lightning terminal ui shows 0.14.3 too

**To reproduce**
Upgraded from lnd according to [the lit guide](https://raspibolt.org/guide/bonus/lightning/lightning-terminal.html#upgrade)

**System information**

    Hardware platform: Raspberry Pi 4 8GB
    Operating system: Raspberry Pi OS Lite (64-bit)
    Version: Debian GNU/Linux 11 (bullseye)

running lightning terminal as standalone as part of the [raspibolt guide](https://raspibolt.org/)

using lnd pool and loop

using latest lit version 0.7.0

**Comment by levmi** [comment]
What LND version are you actually on? It seems like Raspibolt might still be on 0.14.3?

**Comment by pleb4868** [comment]
Hi @levmi 

I started with previous version of lnd (0.13) and upgraded to 0.14.3 when new version was available.

I upgraded to lightning terminal 0.7.0 according to the [upgrade section of the guide](https://raspibolt.org/guide/bonus/lightning/lightning-terminal.html#upgrade)

anyway when I run "litd --lnd.version"
I get :
litd version 0.15.0-beta commit=lightning-terminal-v0.7.0-alpha
which I assume means I'm on the latest version

**Comment by ellemouton** [comment]
@pleb4868 , are you running LND in remote mode?

**Comment by ellemouton** [comment]
if you are following the raspibolt guide to the T then I assume you are running in remote mode. 

In this case, you need to actually updated your LND binary. 

When you run `litd --lnd.version` it is returning the version of LND that Lit is compiled with. So if you ran in integrated mode, it would run with that version of LND. At the point of running `litd --lnd.version`, litd does not know the version of LND that you will connect it to if the LND node is remote.

**Comment by pleb4868** [comment]
Hi @ellemouton,

I guess I didn't realize I was running LND in remote mode...

Thank you very much for your help, upgrading LND, and restarting fixed the issue.
