### ISSUE TITLE
Error when trying to open channel: macaroon validation failed

### ISSUE THREAD

**Issue by cliffpeskin** [lightninglabs/lightning-terminal#425]
**Issue Description**
When attempting to open a channel at https://terminal.lightning.engineering/#/channels/open (from a remote machine) I receive an error message and cannot proceed.

**Expected behavior**
Channel opens successfully. 

**Actual behavior**
Upon selecting the 'Open Channel' button, below error message appears and channel does not open:
_UNABLE TO OPEN CHANNEL
rpc error: code = Unknown desc = lnd macaroon validation failed: rpc error: code = InvalidArgument desc = permission denied_

**To reproduce**
With below mentioned system information:
- Go to https://terminal.lightning.engineering/#/dashboard and select Open Channel on any recommended channel
- Enter SATS amount and FEE RATE
- Select Open Channel button
--> Error

**System information**
- Machine / Server: AWS EC2 t3.medium Instance / 2 vCPUs / 25 GiB storage / Ubuntu 22.04.1 LTS
- Setup guide (neutrino config): https://github.com/alexbosworth/run-lnd
- LND Version: V0.15.1-beta 
- Lightning Terminal Version: v0.8.0-alpha installed from github binaries as per https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/get-lit
- Lightning Terminal Mode: I would assume lnd-mode=remote as I have not adjusted the default settings although I am not sure how to check this definitively
- Remote machine displaying error: Windows 10 Home / Chrome OS Version 106.0.5249.91

**Extra Info**
I have tried deleting all .macaroon and macaroons.db files inside of all folders, restarting lnd / litd and starting a new lightning terminal session. All deleted files were recreated but I still get the same error
Note that I am able to see my node alias and correct sat balance in the lightning terminal.

**ATTACHMENTS**

_Error screenshot_
![macaroon error](https://user-images.githubusercontent.com/20306099/194428699-39f97c2d-938d-45a2-8c1c-51e645a99d00.PNG)

_litd log file..._
[litd.log](https://github.com/lightninglabs/lightning-terminal/files/9728982/litd.log)

**Comment by guggero** [comment]
To connect to `terminal.lightning.engineering`, what kind of session did you create in your local LiT instance? Was that a read-only session perhaps?

**Comment by cliffpeskin** [comment]
Thanks @guggero for taking a look at this.

I am not sure how to the check the LiT session type but what I did is follow these instructions https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/run-litd#docs-internal-guid-fa69f7a0-7fff-8b6a-aadb-a1932e40738b 

In other words, I logged into my aws ec2 instance via ssh, started up lnd and litd and then typed `litcli --lndtlscertpath ~/.lit/tls.cert sessions add --label="default"` into the command line.

**Comment by ellemouton** [comment]
Hi @cliffpeskin , yes that command will create a read-only session :) to create an admin session you can add `--type=admin` to that command

**Comment by cliffpeskin** [comment]
Awesome, thanks @ellemouton and @guggero ! Have been stuck on this for days.

**Comment by ellemouton** [comment]
Thanks for pointing this out! We should defs update the docs to explain how to create an admin session 👍
