### ISSUE TITLE
Corrupted lnd macaroon path on Windows

### ISSUE THREAD

**Issue by eliotcougar** [lightninglabs/lightning-terminal#429]
After update to 0.8.1 the daemon doesn't start because it looks for the macaroon in the wrong place...
lnd macaroon path is defined as an absolute path, but it seems it adds .\ to the path:

2022-10-12 17:40:00.290 [WRN] GRPC: [core] grpc: addrConn.createTransport failed to connect to {127.0.0.1:10009 127.0.0.1:10009 <nil> 0 <nil>}. Err: connection error: desc = "transport: authentication handshake failed: context canceled". Reconnecting...
2022-10-12 17:40:00.290 [INF] SGNL: Received shutdown request.
error displaying startup info: error querying remote node: open .\C:\Users\eliot\AppData\Local\Lnd-testnet\data\chain\bitcoin\testnet\admin.macaroon: The filename, directory name, or volume label syntax is incorrect.

**System information**
Windows 10 x64, running in lnd-remote mode

**Comment by levmi** [comment]
What version did you upgrade from?

**Comment by eliotcougar** [comment]
I upgraded from 0.7.0... That version gets the correct macaroon, but soon shuts down with
2022-10-12 18:03:21.662 [INF] SGNL: Received shutdown request.
unable to fetch order(84c7860ccae07aaeb09a0f3afc50c53779269918cddb6c23a17675420896bcc1): rpc error: code = Unavailable desc = connection closed
That's after I upgraded to LND 0.15.2...

**Comment by eliotcougar** [comment]
Update: The bug is introduced between 0.7.0 and 0.7.1...
Just downloaded 0.7.1, and now I get the error with the LND macaroon path...

**Comment by guggero** [comment]
Hmm, I don't see a change between 0.7.0 and 0.7.1 that would explain the problem... What does your config or your startup flags for litd look like?

**Comment by eliotcougar** [comment]
It works with 0.7.0, but when I replace the exe with 0.7.1 it gives an error as if it can't find the macaroons...

Config:
`httpslisten=0.0.0.0:8443
uipassword=TestPassword
network=testnet
lit-dir=C:\Users\eliot\AppData\Roaming\LiT-testnet
macaroonpath=C:\Users\eliot\AppData\Roaming\LiT-testnet\testnet\lit.macaroon

# Remote lnd options
remote.lnd.rpcserver=127.0.0.1:10009
remote.lnd.macaroonpath=C:\Users\eliot\AppData\Local\Lnd-testnet\data\chain\bitcoin\testnet\admin.macaroon
remote.lnd.tlscertpath=C:\Users\eliot\AppData\Local\Lnd-testnet\tls.cert`

Startup:
`C:\Users\eliot\AppData\Roaming\LiT-testnet\bin\litd-t.exe --lit-dir=C:\Users\eliot\AppData\Roaming\LiT-testnet`

**Comment by guggero** [comment]
Hmm, it looks like filesystem paths are handled differently in different Golang versions. I think the main difference between `v0.7.0` and `v0.7.1` is the Golang version we used to compile it.
Can you try changing all your paths to use forward slashes instead? That should get it working and I'll prepare a fix for this in the meantime.

What I mean is:

```
lit-dir=C:/Users/eliot/AppData/Roaming/LiT-testnet
macaroonpath=C:/Users/eliot/AppData/Roaming/LiT-testnet/testnet/lit.macaroon
...
remote.lnd.macaroonpath=C:/Users/eliot/AppData/Local/Lnd-testnet/data/chain/bitcoin/testnet/admin.macaroon
remote.lnd.tlscertpath=C:/Users/eliot/AppData/Local/Lnd-testnet/tls.cert
...
startup:
 C:/Users/eliot/AppData/Roaming/LiT-testnet/bin/litd-t.exe --lit-dir=C:/Users/eliot/AppData/Roaming/LiT-testnet
```

**Comment by eliotcougar** [comment]
I already tried that... Strangely enough the error still looks the same... I mean, there are backslashes in the error, despite the forward slashes in the config...

**Comment by guggero** [comment]
Ah, I see. They are removed by one of the path cleanup functions... So this needs a code fix.
Can you try with https://github.com/lightninglabs/lightning-terminal/pull/430 please?

**Comment by eliotcougar** [comment]
> Can you try with #430 please?

Sorry... I can't compile anything here... I'll have to wait for the binaries... Thank you in advance...
_Maybe I should finally learn how to do that, though..._

**Comment by guggero** [comment]
Yeah, litd is a bit more complicated to compile since it's not just Go but also some frontend stuff.
Because I cannot really test this (I have no Windows machine at hand), would you mind giving this a spin with a binary that I build from the branch? Since it looks like this is testnet anyway and not mainnet (please wait for the official and signed release for mainnet!)?

**Comment by eliotcougar** [comment]
> would you mind giving this a spin with a binary that I build from the branch?

Sure... I'll wait for the official binary for the mainnet, but I can test it on my testnet...

**Comment by guggero** [comment]
Okay cool, thanks in advance!
Here's the Windows build for testnet:
[lightning-terminal-windows-amd64-v0.8.0-alpha-11-g1e8baee.zip](https://github.com/lightninglabs/lightning-terminal/files/9776649/lightning-terminal-windows-amd64-v0.8.0-alpha-11-g1e8baee.zip)

**Comment by eliotcougar** [comment]
I can confirm the macaroon path issue is fixed... 👍
But it looks like the other issue persists... I'll try to look into it and create another bugreport if I can't fix it...

**Comment by guggero** [comment]
Okay, thanks for testing!

You mean the `Received shutdown request.
unable to fetch order(84c7860ccae07aaeb09a0f3afc50c53779269918cddb6c23a17675420896bcc1): rpc error: code = Unavailable desc = connection closed` error?
If yes, can you include more of the logs please, since this sounds like a follow-up error.
