### ISSUE TITLE
litd[1134]:  [ERR] LNWL: Unable to complete chain rescan: readScript: script witness item is larger than the max allowed size [count 33970, max 11000]

### ISSUE THREAD

**Issue by mylightningnetwork** [lightninglabs/lightning-terminal#433]
Hi I was running 

pool and lnd service it was all good untill last week, my node restarted I believe and I am facing this issue 

[ERR] LNWL: Unable to complete chain rescan: readScript: script witness item is larger than the max allowed size [count 33970, max 11000]

Any Pointer how to resolve the same would be of great help

**Comment by alexbosworth** [comment]
Did you try updating LND

**Comment by mylightningnetwork** [comment]
Many thanks for quick feedback this the service log 
Currently I am using 
"version": "0.15.0-beta commit=lightning-terminal-v0.7.0-alpha",

Which version should I update to, any suggestions Please thanks




lit.service - LiT  Daemon
   Loaded: loaded (/etc/systemd/system/lit.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2022-10-15 20:13:02 UTC; 27s ago
 Main PID: 1210 (litd)
   Status: "Wallet unlocked"
    Tasks: 8 (limit: 4660)
   CGroup: /system.slice/lit.service
           └─1210 /home/lightningnetwork_magazine/lit/litd --httpslisten=0.0.0.0:8443 --lnd.wallet-unlock-password-file=/home/lightningnetwork_magazine/.lit/password.txt # --lnd.wallet-unlock-allow-create

Oct 15 20:13:02 lnd-node-1 litd[1210]: 2022-10-15 20:13:02.226 [INF] ATPL: Instantiating autopilot with active=false, max_channels=5, allocation=0.600000, min_chan_size=20000, max_chan_size=16777215, priv
Oct 15 20:13:02 lnd-node-1 litd[1210]: 2022-10-15 20:13:02.230 [INF] SGNL: Systemd was notified about our readiness
Oct 15 20:13:02 lnd-node-1 litd[1210]: 2022-10-15 20:13:02.230 [INF] LNDC: Wallet state of lnd is now: Lnd RPC server is ready for requests
Oct 15 20:13:02 lnd-node-1 litd[1210]: 2022-10-15 20:13:02.244 [INF] LTND: Waiting for chain backend to finish sync, start_height=758829
Oct 15 20:13:02 lnd-node-1 litd[1210]: 2022-10-15 20:13:02.259 [INF] LNDC: lnd version: v0.15.0-beta, build tags 'litd,autopilotrpc,signrpc,walletrpc,chainrpc,invoicesrpc,watchtowerrpc'
Oct 15 20:13:02 lnd-node-1 litd[1210]: 2022-10-15 20:13:02.260 [INF] LNDC: Using network mainnet
Oct 15 20:13:02 lnd-node-1 litd[1210]: 2022-10-15 20:13:02.260 [INF] LNDC: Waiting for lnd to be fully synced to its chain backend, this might take a while
Oct 15 20:13:02 lnd-node-1 systemd[1]: Started LiT  Daemon.
Oct 15 20:13:03 lnd-node-1 litd[1210]: 2022-10-15 20:13:03.060 [INF] LNWL: Started rescan from block 00000000000000000007477b90ff0ea53cdd1db88e03799af18ff58df0cebaa7 (height 757921) for 0 addresses
Oct 15 20:13:03 lnd-node-1 litd[1210]: 2022-10-15 20:13:03.222 [ERR] LNWL: Unable to complete chain rescan: readScript: script witness item is larger than the max allowed size [count 33970, max 11000]

**Comment by alexbosworth** [comment]
LND 0.15.2

**Comment by mylightningnetwork** [comment]
if you look at compatible pairs of LND to LIT there is no 0.15.2 release yet 

Please check here 
https://github.com/lightninglabs/lightning-terminal

**Comment by mylightningnetwork** [comment]
I just download binary and place it always to make sure there is compatibility
from LIT releases

**Comment by alexbosworth** [comment]
There should be a release, look for the latest one of LND

**Comment by mylightningnetwork** [comment]
Thank you switching to 0.15.2 solved the issue which is bundled with new release of LIT v0.8.1-alpha

**Comment by guggero** [comment]
Closing as per the comment above.
