### ISSUE TITLE
How to set password in .conf.file or somwhere else ?

### ISSUE THREAD

**Issue by thmsmullee** [lightninglabs/lightning-terminal#435]
Hi, 

I installed lit like this:

wget https://github.com/lightninglabs/lightning-terminal/releases/download/v0.8.1-alpha/lightning-terminal-linux-armv7-v0.8.1-alpha.tar.gz
tar xvf
cd lightning-terminal-linux-armv7-v0.8.1
sudo cp * /usr/local/bin

Then I created a service file under /etc/systemd/system with one of the lines saying:

.....
.....
[Service]
ExecStart=/usr/local/bin/litd --uipassword=supersecurepassword --httpslisten 0.0.0.0:8443
.....
....

**LITD works fine, but for me it seems not soooo secure. Or is this fine ?**

THANKS

**Comment by guggero** [comment]
https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md#use-a-configuration-file
