### ISSUE TITLE
Account Status = CLOSED

### ISSUE THREAD

**Issue by iksolon** [lightninglabs/lightning-terminal#437]
Today I made a deposit into my account and after initiating it the "Account Status Closed" appeared.

My transaction was processed on the blockchain but the new balance does not appear on https://terminal.lightning.engineering/#/pool

When I enter the umbrel app, I get the message "Welcome to pool", which means: 

- my account no longer exists? 
- Where did the sats I had in balance go and where did the sats I sent today go? 
- can you help me rescue my account?

obs: about 5 days ago there was a force close in a channel that had not yet passed the pool deadline. I suffered a penalty of some blocks and waited for the penalty to pass to send more funds and continue trading.

This morning, before sending the funds, I closed some channels that had already elapsed the deadline (I checked this well so as not to make a mistake). Soon after I sent the funds and cancelled the ask order I had open. That's when it appeared that my account was closed.

I am using umbrel 0.5.1 on a raspberry pi 4 8gb. Lightning Terminal 0.8.0-alpha.
All the apps and OS are all updated to the latest version available on the umbrel.

I already did stop and start Lightning Terminal and it didn't work. I have not done a full reset of the node yeat.

**Comment by iksolon** [comment]
<img width="200" alt="Screen Shot 2022-10-22 at 07 31 02" src="https://user-images.githubusercontent.com/107311059/197337553-c6690f22-3141-4971-8e77-11a9e24d9080.png">

<img width="1438" alt="Screen Shot 2022-10-22 at 07 31 56" src="https://user-images.githubusercontent.com/107311059/197337575-20a49fd3-3b49-4aa2-9a6f-bfebafcd4b57.png">

<img width="153" alt="Screen Shot 2022-10-22 at 08 55 06" src="https://user-images.githubusercontent.com/107311059/197337602-98eede63-2427-4629-b197-43e6602b73f0.png">

**Comment by jamaljsr** [comment]
It's difficult to tell from your description if the account has been closed, deleted, or just not being read by the UI properly. Can you check the comments in https://github.com/lightninglabs/lightning-terminal/issues/372 for instructions on how to manage your accounts via the CLI on Umbrel. You should first list the accounts to see if the one is displayed there and what the `state` value is. If there are no accounts listed, then you can try to recover the account.

**Comment by iksolon** [comment]
When I try to give the first command of #372:

docker exec -it lightning-terminal_web_1 bash

The response is:

umbrel@umbrel:~ $ docker exec -it lightning-terminal_web_1 bash
Error response from daemon: Container 75e10d2331b63939616416616f79cd3e7e69b4d95bfd395d4b5bec351025f26a is not running
umbrel@umbrel:~ $ 

what should i do now?

**Comment by jamaljsr** [comment]
It looks like the app isn't running. Can you open the Terminal app from the Umbrel UI? 

Can you run `docker ps` to see the list of containers and share the output?

**Comment by iksolon** [comment]
<img width="1440" alt="Screen Shot 2022-10-24 at 21 45 18" src="https://user-images.githubusercontent.com/107311059/197656468-4b5391ad-86a5-4515-bef5-30d8c9818f54.png">

Connected via the umbrel app right now.

This is how the pool appears to me now. It keeps asking me to create an account. But what about my old account, why was it closed?

And where is the balance I had of 1M plus the 5M I deposited?

**Comment by jamaljsr** [comment]
What is the output of `docker ps`?

**Comment by jamaljsr** [comment]
Ok, I see `lightning-terminal_web_1` there running. Try the command `docker exec -it lightning-terminal_web_1 bash` again. If that doesn't work, try `docker exec -it 57721f1cd2ec bash`.

**Comment by iksolon** [comment]
umbrel@umbrel:~ $ docker exec -it lightning-terminal_web_1 bash
bash-5.1$ pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts list
{
        "accounts": []
}
bash-5.1$

**Comment by jamaljsr** [comment]
Ok, it's not showing the account, likely because it's closed. Can you add `--show_archived` so it shows closed accounts as well.
```
pool --rpcserver=localhost:8443 --tlscertpath=/.lit/tls.cert --macaroonpath=/.pool/mainnet/pool.macaroon accounts list --show_archived
```

**Comment by jamaljsr** [comment]
Oh the tilde was removed when I copied your command above. Try this.

```
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts list --show_archived
```

**Comment by iksolon** [comment]
bash-5.1$ pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts list --show_archived
{
        "accounts": [
                {
                        "trader_key": "038444b4bcccec17443a4d73c01b39ce2183d9407cbbb3e6058465a056cf69083c",
                        "outpoint": "a2807486889f83c724124266a3393cd00e088a5d70d167f01d40c68428aef8a0:1",
                        "value": 1052719,
                        "available_balance": 1052719,
                        "expiration_height": 762782,
                        "state": "CLOSED",
                        "latest_txid": "e70c4d48f644b9edf2b59c2b33ff8fb8427749e677f2a23d875bb2d598425deb"
                }
        ]
}
bash-5.1$

**Comment by jamaljsr** [comment]
Ok, It looks like your account was indeed closed via the transaction [e70c4d48f644b9edf2b59c2b33ff8fb8427749e677f2a23d875bb2d598425deb](https://mempool.space/tx/e70c4d48f644b9edf2b59c2b33ff8fb8427749e677f2a23d875bb2d598425deb). Pool doesn't automatically close accounts, so maybe you accidentally clicked the wrong button in the UI. The funds are returned to your LND wallet when an account is closed.

**Comment by iksolon** [comment]
This is hardly the case. But what happened doesn't really matter now... We have to solve it, because the last thing I did, before the account was closed, was to send her 5M (e70c4d48f644b9edf2b59c2b33ff8fb8427749e677f2a23d875bb2d598425deb). And both the 1M that was in the pool account, and the 5M that I sent, did not come back to my node wallet.

Can you help me with this?

**Comment by jamaljsr** [comment]
Yes, I'll do my best to try to figure out what happened.

Can you share a screenshot of the History page in the Terminal UI. I'm specifically interested in the Pool txns so you can click on that tab to filter the list.

**Comment by iksolon** [comment]
<img width="789" alt="Screen Shot 2022-10-25 at 12 21 45" src="https://user-images.githubusercontent.com/107311059/197814729-b021dc57-da48-4e0f-835e-2130ee7d101b.png">

Thacks a lot man!

Is that screenshoot good for you?

**Comment by iksolon** [comment]
<img width="1440" alt="Screen Shot 2022-10-25 at 12 25 26" src="https://user-images.githubusercontent.com/107311059/197815648-9fcbd138-6463-4f58-8acd-59ae0c7693f4.png">


You see that after I sent the 5M to the pool, no more significant value has entered the node wallet.

**Comment by jamaljsr** [comment]
Great, this helps. It looks like there were two more Pool txns after your 5M deposit. Can you give the transaction IDs of thode two top transactions on Sept 14th & 25th? Just click on the row and the txid will be displayed in a popup.

**Comment by iksolon** [comment]
<img width="789" alt="Screen Shot 2022-10-25 at 12 54 03" src="https://user-images.githubusercontent.com/107311059/197822378-75b068fd-3eff-4639-aa27-d8957ea622f9.png">

When I click on the transaction, it shows this.

**Comment by iksolon** [comment]
<img width="984" alt="Screen Shot 2022-10-25 at 12 54 52" src="https://user-images.githubusercontent.com/107311059/197822597-ae2c68b9-2cc4-4a24-a5b7-163e3d1727fd.png">

When I put the mouse over the transaction, I get this.

**Comment by jamaljsr** [comment]
Ah ok. I think you have an account that needs to be recovered. Maybe the pool.db file got wiped away by Umbrel somehow. Can you run this command?
```
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts recover
```

**Comment by jamaljsr** [comment]
Nice! 

Now list the accounts to see the recovered one.
```
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts list --show_archived
```

Then close the recovered the account with this command, replacing `<acct_key>` with the value from `accounts list` command.
```
pool --rpcserver=localhost:8443 --tlscertpath=~/.lit/tls.cert --macaroonpath=~/.pool/mainnet/pool.macaroon accounts close <acct_key>
```

**Comment by iksolon** [comment]
<img width="1431" alt="Screen Shot 2022-10-25 at 13 23 28" src="https://user-images.githubusercontent.com/107311059/197829460-ff8df9c1-a48e-4d20-a79a-74ad177cb052.png">

Before you do that, see that in the umbrel app the account is back to normal!!!!

Should I still do the last procedure?

**Comment by jamaljsr** [comment]
Oh sweet. No need to close the account if it's currently active. You should be all good now.

**Comment by iksolon** [comment]
Thank you very much, man.

Please send me your lightning address so I can send you a tip, just for graditude.

**Comment by jamaljsr** [comment]
lol.. thanks for the offer, but it's all good. You're participation in the market and providing feedback is valuable to the team. Thank you

**Comment by iksolon** [comment]
Well, in that case, thank you very much for your attention and for solving my problem.

If I can do anything for you, let me know
