### ISSUE TITLE
Add docs for running litd in regtest in a Polar environment

### ISSUE THREAD

**Issue by otech47** [lightninglabs/lightning-terminal#441]
Seems like it may be possible (https://github.com/lightninglabs/lightning-terminal/issues/359#issuecomment-1207956072) currently to run `litd` on regtest (with any risks?) but at least for development purposes it would be great if the README or some other doc detailed how to get this running

I tried to get it working with Polar and blocked by some issue with the macaroon service. Not 100% sure if this can be solved from `litd` or maybe something specific to Polar... leaving this here in case it is helpful or if anyone can solve it

Getting error
`error starting macaroon service: unable to unlock macaroon DB: invalid password`

with specs:

OSX 12.6 (Apple M1 ARM)
Polar 1.4.0
Docker 4.13.0
LND (tried with [custom LND](https://github.com/lightningnetwork/lnd/commit/81b17ef4fde9c73d57e699a97778454198f3893d) , and `v15.2`)
LitD (`v0.8.2-alpha` [commit](9126875beb7c462abcc2bdbfbfa4b20a194be57d))

![Screen Shot 2022-10-27 at 6 51 41 PM](https://user-images.githubusercontent.com/4914611/198412678-5cc3dd56-42d1-4c31-a25f-4d6424839359.png)
![Screen Shot 2022-10-27 at 6 46 29 PM](https://user-images.githubusercontent.com/4914611/198412686-08a78962-12e0-4980-ba85-09427e3f6fa2.png)

**Comment by huumn** [comment]
I've managed to get it running with this config (from a working copy of [our compose file](https://github.com/stackernews/stacker.news/blob/master/docker-compose.yml)):

```yaml
    command:
      - 'litd'
      - '--httpslisten=0.0.0.0:8444'
      - '--insecure-httplisten=0.0.0.0:8443'
      - '--uipassword=password'
      - '--lnd-mode=remote'
      - '--network=regtest'
      - '--remote.lit-debuglevel=debug'
      - '--remote.lnd.rpcserver=stacker_lnd:10009'
      - '--remote.lnd.macaroonpath=/lnd/data/chain/bitcoin/regtest/admin.macaroon'
      - '--remote.lnd.tlscertpath=/lnd/tls.cert'
      - '--autopilot.disable'
      - '--pool.auctionserver=test.pool.lightning.finance:12010'
      - '--loop.server.host=test.swap.lightning.today:11010'
```

We run a regtest network without polar, but I suspect something like this should work in polar. The subserver part is the ugliest bit. 

The config options are documented in code well: https://github.com/lightninglabs/lightning-terminal/blob/080c93429e872a4c305b9fc422892f3f2ea8c439/config.go#L149-L227

**Comment by jamaljsr** [comment]
The [latest release](https://github.com/jamaljsr/polar/releases/tag/v3.0.0) of Polar officially added support for running `litd` nodes. It should be pretty straight forward now, without needing to add docs here.
