### ISSUE TITLE
oops, that password is incorrect

### ISSUE THREAD

**Issue by majjihari** [lightninglabs/lightning-terminal#465]
> Okay, yeah, that happens some time.
> 
> Closing as this was related to the shell's handling of special characters.

I still see this error though i set very simple password without special characters. And also http://localhost/lnrpc.Lightning/GetInfo response is success

I tried with versions 0.8.4 and 0.8.5. same issue.

![image](https://user-images.githubusercontent.com/2501864/205946005-a28fdd46-f212-45c0-a3b6-207e96ba66c7.png)

_Originally posted by @majjihari in https://github.com/lightninglabs/lightning-terminal/issues/279#issuecomment-1339511117_

**Comment by guggero** [comment]
https://github.com/lightninglabs/lightning-terminal/issues/279#issuecomment-1339513345

**Comment by guggero** [comment]
Maybe need to go further back in the logs, check from the startup (where it prints the connection info) all the way down.

**Comment by majjihari** [comment]
> Maybe need to go further back in the logs, check from the startup (where it prints the connection info) all the way down.

Please find the attached log

[litd log.txt](https://github.com/lightninglabs/lightning-terminal/files/10167735/litd.log.txt)

**Comment by majjihari** [comment]
> Ah, you need to unlock the wallet first. See [first sentence here](https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-integrated.md#configuring-lit-with-integrated-lnd-node).

If you are referring to below log, it is just info only and in integrated mode wallet is not mentioned mandatory as for documentation at https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-integrated.md

2022-12-06 17:52:08.404 [INF] LTND: Waiting for wallet encryption password. Use `lncli create` to create a wallet, `lncli unlock` to unlock an existing wallet, or `lncli changepassword` to change the password of an existing wallet and unlock it.

**Comment by guggero** [comment]
Unfortunately unlocking (or creating) the wallet through the UI isn't possible yet. See https://github.com/lightninglabs/lightning-terminal/issues/136, https://github.com/lightninglabs/lightning-terminal/issues/128, https://github.com/lightninglabs/lightning-terminal/issues/121.
