### ISSUE TITLE
UNABLE TO FETCH

### ISSUE THREAD

**Issue by majjihari** [lightninglabs/lightning-terminal#466]
![image](https://user-images.githubusercontent.com/2501864/206154320-04280c64-2d29-49be-9b70-61471d22ba4d.png)

In browser when trying to access Pools, I am facing this. Is it because of firewall? What permissions to set in order for FETCH ACCOUNTS, FETCH LATEST BATCH, FETCH LEASES and others to work.

**Comment by guggero** [comment]
To connect to the Pool server, you need to allow connections to `pool.lightning.finance:12010`: https://github.com/lightninglabs/pool/blob/master/config.go#L187

**Comment by majjihari** [comment]
> To connect to the Pool server, you need to allow connections to `pool.lightning.finance:12010`: https://github.com/lightninglabs/pool/blob/master/config.go#L187

Thank you @guggero

**Comment by majjihari** [comment]
> > To connect to the Pool server, you need to allow connections to `pool.lightning.finance:12010`: https://github.com/lightninglabs/pool/blob/master/config.go#L187
> 
> Thank you @guggero

Thank you @guggero 

Allow below in firewall solved the issue

test.swap.lightning.today:12010
test.pool.lightning.finance:11010
