### ISSUE TITLE
Unable to fund the multisig pool account

### ISSUE THREAD

**Issue by majjihari** [lightninglabs/lightning-terminal#468]
![image](https://user-images.githubusercontent.com/2501864/206830678-d2f2e172-46ec-4fe7-b0db-84f0a56c99a5.png)

I have enough SATS but still unable to make the deposit to multisig

Pls suggest and thank you in advance

**Comment by levmi** [comment]
Are there enough confirmations on the funds in the LND wallet? It needs 6 confirmations before you can then use the funds to fund a Pool account.

**Comment by guggero** [comment]
The error sounds like an issue with paying the LSAT required to open an account. For that you need at least one active channel with the ability to pay for a 1000 satoshi invoice. The litd logs should have more info as well.
See https://docs.lightning.engineering/lightning-network-tools/pool/quickstart#prepare-lnd.

**Comment by majjihari** [comment]
> The error sounds like an issue with paying the LSAT required to open an account. For that you need at least one active channel with the ability to pay for a 1000 satoshi invoice. The litd logs should have more info as well. See https://docs.lightning.engineering/lightning-network-tools/pool/quickstart#prepare-lnd.

Yes that may be correct @guggero. After setting 1000 LSAT fee I got his. If you have BTC testnet balance, kindly send 0.1 BTC to tb1pyy82f5y9zqme90yxy2dw2y9rs6ppexgf4cpwql2cylld5dte2nasazw4xu

Thank you in advance.

![image](https://user-images.githubusercontent.com/2501864/207236483-99e35ed7-d87c-42a6-822f-b0e65d01bf4d.png)

**Comment by guggero** [comment]
I sent you some testnet coins to the address. Closing this issue as it sounds like you were able to resolve it. Please join our [Slack server](https://lightning.engineering/slack.html) for further troubleshooting.

**Comment by majjihari** [comment]
> I sent you some testnet coins to the address. Closing this issue as it sounds like you were able to resolve it. Please join our [Slack server](https://lightning.engineering/slack.html) for further troubleshooting.

Thank you @guggero  for tokens and support.
