### ISSUE TITLE
Unable to open channel

### ISSUE THREAD

**Issue by majjihari** [lightninglabs/lightning-terminal#469]
![WhatsApp Image 2022-12-14 at 2 41 34 PM](https://user-images.githubusercontent.com/2501864/207589891-776fd38c-c4de-40cf-b8aa-0982de4ceca5.jpeg)

Kindly find the logs here. 

[litd log.txt](https://github.com/lightninglabs/lightning-terminal/files/10227585/litd.log.txt)

**Comment by jamaljsr** [comment]
Is your node on testnet trying to connect to a mainnet node, or vice-versa?

**Comment by levmi** [comment]
Haven't gotten a response on this one. Feel free to re-open if you want to discuss further.
