### ISSUE TITLE
Default app password not working

### ISSUE THREAD

**Issue by quinteiroh** [lightninglabs/lightning-terminal#478]
I don't know what I'm doing wrong but when a paste the password on the app to log in I receive a "wrong password" message

**Comment by guggero** [comment]
That usually means that the service isn't ready or fully started up because of some error. Can you check your logs?

**Comment by quinteiroh** [comment]
Probably was the first option. I was going to sleep and it was working on next day. 

Thank you :)

**Comment by guggero** [comment]
Okay, thanks for the response. Closing the issue in that case.
