### ISSUE TITLE
Error code: ENOTFOUND

### ISSUE THREAD

**Issue by LatiNodos** [lightninglabs/lightning-terminal#479]
Hey there - I am running Umbrel and after the update to LND 0.15.5 , my Terminal app (and all LNC connections) fail.

"Session Not Found. Failed to connect the WASM client to the proxy server. Try reloading the page or obtaining a new pairing phrase."

Appreciate any guidance - given I want to avoid risk of locking the funds in the Pool Account.

thx

**Comment by LatiNodos** [comment]
When I ran `docker ps` I don't see the lightninglabs/lightning-terminal ID at all.

Could it have been removed after the LND update?

**Comment by positiveblue** [comment]
The first thing would be to ensure that `lightninglabs/lightning-terminal` is up and running. If it is not, start the container/app.

You should then be able to connect to terminal locally (by default uses the port 8443). If after this you cannot still connect, try creating a new session.

**Comment by LatiNodos** [comment]
thanks a lot for the quick reply! a simple restart fixed it :)

looks like it was a simple after-update hiccup. please close this issue.

`~/umbrel/scripts/app restart lightning-terminal`
