### ISSUE TITLE
Send payments with Terminal appears to work differently than CLI

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-terminal#480]
When sending a payment, pasting the Lightning invoice into Terminal immediately results in the following pop-up error:

<img width="317" alt="Screen Shot 2023-01-21 at 12 13 24 PM" src="https://user-images.githubusercontent.com/628298/213885798-05b843a2-6f70-43f2-8391-0ac8f3cc2d07.png">

However, using the CLI and "lncli sendpayment --pay_req [PAYMENT_REQUEST]" results in a successful payment. 

I would expect that the results from attempting to pay the invoice via Terminal or the CLI would be the same, but in the case of attempting to send the payment via Terminal, it's not possible to get past the "Next" button to attempt making the payment.

If there is a difference between what can be sent via Terminal and the CLI, the error message could suggest that to the user. Also, the pop-up error doesn't include the full error message and isn't persistent, so that makes it a bit more confusing.

![Screen Shot 2023-01-21 at 12 28 05 PM](https://user-images.githubusercontent.com/628298/213886002-323932e5-5172-4cfc-aa18-ecba9170a034.jpg)

I've reproduced the issue with a couple different channels and a couple different destinations.

Standalone.

Using litd and Lightning Terminal Web.

lightning-terminal-linux-amd64-v0.8.5-alpha, binary download from Github.

Linux, amd64, SSD

Ubuntu 22.10

litd.log doesn't seem to contain any entries that are relevant to the issue.

**Comment by levmi** [comment]
Hey Bryan - thanks for the detailed bug report. We'll take a look at this this week to see what's going on here.

**Comment by jamaljsr** [comment]
Hey @bryanvu, happy to see you're still dabbling in Lightning.

I'm pretty sure the difference you are seeing is due to Terminal using the SendPayment RPC while the CLI uses SendPaymentV2. We certainly need to update Terminal to use V2 instead.

**Comment by bryanvu** [comment]
Thanks @jamaljsr and @levmi. Makes sense about the different SendPayment RPCs. Just trying to finally take some time to catch up on all the great work you guys have been doing. :)

**Comment by levmi** [comment]
As an update, we're actively working on this. There should be a fix going out in the next release. Thanks again for flagging.

**Comment by levmi** [comment]
Fixed in the release that went out today. Thanks again for the feedback!
