### ISSUE TITLE
error message on LND / umbrel LT app ?

### ISSUE THREAD

**Issue by chmeulblu** [lightninglabs/lightning-terminal#481]
HI, 
don't know if it is the right place but here it is : i get 

Oops, there was an error
There was an error connecting to Lightning Terminal. Error code: EAI_AGAIN

when i try to open Lightning Terminal  App using Umbrel 

thanks

**Comment by guggero** [comment]
According to the error message that looks like something isn't configured correctly in Umbrel itself. EAI_AGAIN seems to be a DNS resolution problem.
Try restarting your Umbrel and if that doesn't work check the logs of Lightning Terminal (the Umbrel docs should help you on how to do that).

**Comment by chmeulblu** [comment]
Ok thanksEnvoyé de mon iPadLe 23 janv. 2023 à 12:16, Oliver Gugger ***@***.***> a écrit :﻿
According to the error message that looks like something isn't configured correctly in Umbrel itself. EAI_AGAIN seems to be a DNS resolution problem.
Try restarting your Umbrel and if that doesn't work check the logs of Lightning Terminal (the Umbrel docs should help you on how to do that).

**Comment by guggero** [comment]
Sounds like the issue was solved? Feel free to re-open if problems persist.

**Comment by chmeulblu** [comment]
‌yes thanks !

De : "Oliver Gugger"
A : "lightninglabs/lightning-terminal" ,"chmeulblu" ,"Author"
Envoyé: lundi 27 Février 2023 10:10
Objet : Re: [lightninglabs/lightning-terminal] error message on LND / umbrel LT app ? (Issue #481)
 

 

Sounds like the issue was solved? Feel free to re-open if problems persist.
