### ISSUE TITLE
Minor - Loop Swap Details Page says "Loop Out" when doing a Loop In

### ISSUE THREAD

**Issue by bryanvu** [lightninglabs/lightning-terminal#483]
Screenshot: 

![Screen Shot 2023-01-25 at 5 18 10 PM](https://user-images.githubusercontent.com/628298/214736862-c6a195c5-cd40-4847-83e6-d4ae5bbbd62c.jpg)

Other than that, the Loop UI in Terminal worked flawlessly.

**Comment by jamaljsr** [comment]
Ah, good catch! That indeed is a typo and a one-liner to fix. We should get this resolved pretty quickly. Thanks for pointing that out.
