### ISSUE TITLE
Missing darwin arm build

### ISSUE THREAD

**Issue by lukaszsamson** [lightninglabs/lightning-terminal#491]
**Is your feature request related to a problem? Please describe.**
With no darwin arm build it’s troublesome to run lightning terminal on M1/M2 macs.

**Describe the solution you'd like**

Build added. Other platforms already have arm builds

**Describe alternatives you've considered**

**Additional context**

**Comment by guggero** [comment]
We'll add that to the next bigger release. In the meantime, there is a Docker image for `arm64` environments: https://hub.docker.com/layers/lightninglabs/lightning-terminal/v0.8.6-alpha/images/sha256-6017cd63b1169f376c1851e3b3a16fa729e15d556144b6ddf7bc3f023749a24b?context=explore

**Comment by lukaszsamson** [comment]
Thanks
