### ISSUE TITLE
v0.8.6 Does not start up correctly with LND remote config

### ISSUE THREAD

**Issue by lukeroberts** [lightninglabs/lightning-terminal#492]
**Expected behavior**

LiT starts up after upgrade to v0.8.6

**Actual behavior**

The following error occurs during startup and LiT exits
```
2023-02-18 16:07:21.113 [INF] LITD: Starting LiT middleware manager
2023-02-18 16:07:21.114 [ERR] LNDC: Could not receive from interceptor stream: rpc error: code = Unknown desc = RPC middleware not enabled in config
2023-02-18 16:07:21.114 [ERR] LITD: Could not start subservers: context canceled
```

**To reproduce**

Configure a LiT instance to connect to a remote LND node

**System information**

LiT is running using docker compose on Ubuntu 20.04 with lnd remote configured to a v0.15.5-beta LND node (no configuration has been done with [rpcmiddleware]

Is there any configuration that needs to be done besides enabling rpcmiddleware?
```rpcmiddleware.enable=true```

**Comment by jamaljsr** [comment]
The `rpcmiddleware.enable` flag is the only one that you need to set. This is required for the new custodial accounts feature.

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/lightning-terminal/pull/493.
