### ISSUE TITLE
Lightning Terminal Pool account recovery on Embassy OS

### ISSUE THREAD

**Issue by em1xAdmin** [lightninglabs/lightning-terminal#528]
Hi,
Is there any specific instructions for recovering a Lightning Terminal Pool account when running on Start9 Embassy OS?

The issue: Setup a pool account and configured an ASK offer 2 weeks ago. Everything appears normal for days, Now, on logon there is only the welcome to Pool banner and no evidence of the account. Restore from the latest backup does not help.

Thanks

**Comment by guggero** [comment]
You should be able to follow this guide: https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery
Maybe you also need to move/rename the `pool.db` as described in the step above.

Some arguments/flags might change on Start9 Embassy, unfortunately I'm not familiar with software and can't give you more info on that. Their support might be able to help you.

**Comment by guggero** [comment]
@em1xAdmin were you able to recover the account using the guide linked above? Can we close the issue?

**Comment by em1xAdmin** [comment]
Hi,
Sorry for the slow response.

Recovery was not successful.  See results below.
:~ $ sudo docker exec -it lightning-terminal.embassy bash
lightning-terminal:/# pool --tlscertpath "/data/.lit/tls.cert" --rpcserver localhost:8443 --macaroonpath "/data/.pool/mainnet/pool.macaroon" accounts recover
[pool] rpc error: code = Unknown desc = proxy error with context pool: invalid macaroon: verification failed: signature mismatch after caveat verification

**Comment by guggero** [comment]
This sounds like something changed on your system and some things in the Pool data directory were deleted while other things were not. Can you try removing the poo.macaroon, restarting litd and then trying again?

**Comment by em1xAdmin** [comment]
Hi,

How do I remove the poo.macaroon?

**Comment by guggero** [comment]
Sorry, that was a typo, I meant `pool.macaroon`. You just delete it (`rm path/to/pool.macaroon`), it will then be re-generated on the next startup.

**Comment by ellemouton** [comment]
Glad you got everything sorted! Thanks @guggero for hoping in and helping here 🚀
