### ISSUE TITLE
Paying invoice through web UI kept failing, succeeded in command line

### ISSUE THREAD

**Issue by shaurya947** [lightninglabs/lightning-terminal#529]
I was trying to use terminal web ui to pay an invoice yesterday. The recipient was a muun wallet, and my node has several channels with peers in a variety of centralization percentiles. In other words, I was quite confident that this should be a smooth routing experience.

However terminal ui would keep showing me an error "unable to find a path to destination." The error would show up almost as soon as I hit the send button, which led me to believe that there might be something wrong in my configuration. And sure enough, as soon I switched to command line and used `lncli payinvoice` it went through in a few seconds.

I posted in slack and it was suggested I make an issue in case there is some default behavior with `fee_limit_sat` when paying using the web UI which differs from directly using `lncli payinvoice` (with defaults).

**Expected behavior**

Paying the invoice through the terminal web UI should have succeeded just the same as using `lncli payinvoice`.

**Actual behavior**

Terminal web ui would instantly fail with the error "unable to find a path to destination" leading me to believe that there might be some configuration issue on my end. 

**To reproduce**

This was the first invoice I attempted to pay using terminal web UI and I haven't tried with another invoice again, but I'm guessing I can reproduce this any time I try to pay an invoice?
 
**System information**

Running terminal standalone on a linux distro also running bitcoind. Machine is a repurposed Chromebook running GalliumOS.

Terminal is running in integrated mode. v0.9.0 alpha, downloaded from github releases page.

**Comment by levmi** [comment]
Thanks for the report. There is indeed an issue on the Terminal side that makes the behavior slightly different from the CLI, which can result in these errors. We're actively working on a fix which will be included in our next release.

**Comment by shaurya947** [comment]
Thanks @levmi ! I decided to look around a bit more in the repo since I would like to learn and contribute over time. :)

Is this purely an issue on the `terminal.lightning.engineering` webapp side? Is the source for that available somewhere or is it closed? On the other hand, does the issue pertain to `lightning-node-connect` and how it interacts with the `lnd` instance? Would love to follow along if there's any references you could point to.

**Comment by shaurya947** [comment]
Thanks for the explanation @levmi ! The fee limit difference makes total sense, and I look forward to the customizability that you mentioned :)

Thanks for the links as well. I read through and it was interesting to learn about mission control's different configuration options. A few days ago, I was attempting to balance some of my channels through self-looping payments (using `queryRoutes`) so all this information was instantly relatable.

**Comment by levmi** [comment]
Awesome! Definitely dig into the Builder's Guide as you move forward on your node running/Lightning building journey. There is an incredible amount of useful information in there :) 

Also, this issue should now be fixed in the latest release of Terminal. So, if you give this another try, it should behave the same way as the CLI. Thanks again for flagging, closing for now, but feel free to re-open if something doesn't match your expectations!
