### ISSUE TITLE
Failed reading TLS server keys

### ISSUE THREAD

**Issue by seeker0003** [lightninglabs/lightning-terminal#534]
Upon starting litd, it immediately fails with an error about missing keys. I'm attempting to connect it to a remote Voltage node. Nowhere in any of the instructions is there something about needing to provide a tls.key file, so I'm completely lost.

lit.conf (located at ~/.lit):
```
uipassword=censored
lnd-mode=remote
remote.lnd.rpcserver=censoredserver:10009
remote.lnd.macaroonpath=/home/username/.lit/admin.macaroon
remote.lnd.tlscertpath=/home/username/.lit/tls.cert
```

litd terminal output:
```
2023-04-25 14:57:05.346 [INF] LITD: LiT version: 0.9.1-alpha commit=v0.9.1-alpha
2023-04-25 14:57:05.350 [INF] SESS: Checking for schema update: latest_version=0, db_version=0
2023-04-25 14:57:05.350 [INF] LITD: Dialing lnd gRPC server at censoredserver:10009
error starting UI HTTP server: unable to create TLS config: failed reading TLS server keys: open /home/username/.lit/tls.key: no such file or directory
```

**Comment by GeorgeTsagk** [comment]
Hey @seeker0003 !

Your configuration seems to be correct. What you need to change is either the path or the filename for the LND tls certificate. Currently `litd` will auto-generate its own `tls.cert` and place it inside the `~/.lit/` directory, which currently overwrites the LND tls cert.
