### ISSUE TITLE
macaroons: auto-regenerate if API changes

### ISSUE THREAD

**Issue by ellemouton** [lightninglabs/lightning-terminal#540]
Currently, each time we make additions to any API, users have to manually delete their lit.macaroon so that it is regenerated on startup. We should let lit do this re-generation automatically on startup.

**Comment by almostheaven1863** [comment]
How do you delete the macaroon? When I try to start Terminal, it gives as error saying the macaroon password is wrong.

**Comment by ViktorTigerstrom** [comment]
I've pushed a fix in the lndclient repo that should address this issue:
https://github.com/lightninglabs/lndclient/pull/151

**Comment by ViktorTigerstrom** [comment]
Opened the PR #559 to make it quick for reviewers to test the feature. Sorry for taking some time to open that PR.
