### ISSUE TITLE
Unable to register custodial account

### ISSUE THREAD

**Issue by bspankratz** [lightninglabs/lightning-terminal#548]
For "Terminal Lightning" when I'm trying to create a "custodial" session, I get this error:

Unable to register custodial account
proxy error with context lit: invalid macaroon: permission denied

What am I doing wrong?  I was able to successfully create an Admin session with this same lightning node.

**Comment by bspankratz** [comment]
Where do I export the relevant logs?

Brendan

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by bspankratz** [comment]
I think this is what you need?

Brendan

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by levmi** [comment]
You can take a look at how to grab the relevant logs in the [litd Troubleshooting Guide](https://github.com/lightninglabs/lightning-terminal/blob/master/doc/troubleshooting.md), but feel free to let me know if any further questions about how to grab it!

**Comment by levmi** [comment]
We can dig in more when we get those logs, but in the meantime, this is likely due to a macaroon issue and you could fix it by following this comment: https://github.com/lightninglabs/lightning-terminal/issues/463#issuecomment-1338099650

**Comment by bspankratz** [comment]
I don't know how to delete my admin.macaroon. I'm not that technical 🤣

Can I delete the app and reinstall it?

Brendan

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by levmi** [comment]
No worries! Understandable, can try to get you more detailed instructions. What OS are you using for your node? Umbrel?

**Comment by bspankratz** [comment]
I have the latest version of Umbrel

Brendan

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by bspankratz** [comment]
I think this email thread went cold. I believe you were going to send instructions for how to reset some macaroons or something?

Thanks for your help!

Brendan

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by levmi** [comment]
Hiya, thank you for the bump on this. Bad news is that we don't have ready-made instructions for this. Good news is that I was able to scrounge around and find the pieces that should make it work. Better news is that, thanks to feedback from users like yourself, with a coming release of Terminal, this should no longer be an issue as we'll check macaroons and regenerate without any user action if needed on update/restart (https://github.com/lightninglabs/lightning-terminal/issues/540). 

Okay, onto the good stuff... To delete and regenerate the macaroons on an Umbrel, you should start by: 

1. SSH into the Umbrel node. The password is the same one you use to login to the Umbrel website. `ssh umbrel@umbrel.local`
This command works on Mac & Linux. If you are using a Windows computer, you'll need to use an app like [PuTTY](https://www.putty.org/) to SSH into the Umbrel node.
2. Once logged in, your terminal prompt should say `umbrel@umbrel:~ $`
3. Run `bash` inside the `lightning-terminal` docker container `docker exec -it lightning-terminal_web_1 bash` When inside the container, your terminal prompt should say `bash-5.1$`
4. Delete the macaroon in `~/umbrel/app-data/lightning-terminal/data/.lit/mainnet/` titled `lit.macaroon`
5. Restart Lightning Terminal 

To quit the SSH session, just enter the `exit` command twice

For more guidance, you can also refer to the below issues which have some similarities, but some differences. You can also reach out to the Umbrel Community to ask for more guidance as that forum is normally pretty helpful (https://community.getumbrel.com/).   

https://github.com/lightninglabs/lightning-terminal/issues/545
https://github.com/lightninglabs/lightning-terminal/issues/181#issuecomment-783499465

If you don't feel comfortable with this level of technical configuring on the CLI, I can also flag for you when the Terminal release comes out with the regeneration built in, should be relatively soon (weeks). Then, you can update to that and it should automagically work.

**Comment by bspankratz** [comment]
Good morning,

Any idea when the Lightning Terminal update that will fix this macaroon issue will come out? I'm really looking forward to being able to segregate lightning wallets for each of my kids.

Thanks,

Brendan

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by levmi** [comment]
Hey Brendan, thanks for the follow up! With Lightning Terminal v0.10.1, this issue should hopefully be fixed. So, update to that version and it should work. Let us know if not! 

P.S. Love that you're using custodial accounts to give your kids Lightning wallets! So cool!

**Comment by bspankratz** [comment]
Just updated and everything works now, thanks!

Brendan

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by levmi** [comment]
Love to hear it! Hope your kids enjoy their new Lightning wallets! ♥️
