### ISSUE TITLE
Loopout State Initiate for more than 5 hours and continue

### ISSUE THREAD

**Issue by Redinpais** [lightninglabs/lightning-terminal#569]
I have a loopout instance on the lightning terminal that has been going on for more than 5 hours and is not ending. Status Initiated
Is this normal? How can I terminate it and start over again?
Thanks.

**Comment by levmi** [comment]
Hiya- thanks for reaching out! Is this on Lightning Terminal locally hosted or on the web? Have you checked whether the funds have arrived in your on-chain wallet on the node?

**Comment by Redinpais** [comment]
I am using LT for Umbrel. The funds have not been sent onchain.I ended up uninstalling LT and re-installing.Now I can't even give a loopout order. I always get a no route error. Strange because my node is well placed and with good liquidity. And since I've been using your service I've never had a route outage problem.(BTW: Your webbrowser version never worked either and it starts to show a drawback right away. It asks me to start clicking on the "Start" button, and that button doesn't exist).Attached Images.
Thanks


António Pais





    Em sábado, 3 de junho de 2023 às 02:06:51 WEST, ***@***.***> escreveu:  
 
 


Hiya- thanks for reaching out! Is this on Lightning Terminal locally hosted or on the web? Have you checked whether the funds have arrived in your on-chain wallet on the node?

**Comment by Redinpais** [comment]
... correction, i mean... "Begin" button

António Pais


    Em sábado, 3 de junho de 2023 às 02:06:51 WEST, ***@***.***> escreveu:  
 
 


Hiya- thanks for reaching out! Is this on Lightning Terminal locally hosted or on the web? Have you checked whether the funds have arrived in your on-chain wallet on the node?

**Comment by levmi** [comment]
Hmm.. it seems the attached images didn't upload. Sorry that you seem to be having some trouble here. Uninstalling and reinstalling the app will wipe the Loop db. Are your funds from the original Loop still in a limbo state? Can you see them in your wallet anywhere?

**Comment by Redinpais** [comment]
Fortunately nothing happened to my funds. They didn't go to limbo either. I chose to reinstall the app.I just kept seeing the instruction being in progress for many hours and it wouldn't leave the list, which prevented me from running it again because I knew I wouldn't have any more liquidity.Thank you for your support. I will test the functionality again in another occasion.
António Pais




    Em segunda-feira, 5 de junho de 2023 às 14:50:33 WEST, ***@***.***> escreveu:  
 
 


Hmm.. it seems the attached images didn't upload. Sorry that you seem to be having some trouble here. Uninstalling and reinstalling the app will wipe the Loop db. Are your funds from the original Loop still in a limbo state? Can you see them in your wallet anywhere?
