### ISSUE TITLE
Pending actions stuck at Fetching

### ISSUE THREAD

**Issue by eliotcougar** [lightninglabs/lightning-terminal#595]
In Terminal Web I cleared browser data and logged back in... Now the entire "Pending Actions" section of the UI is stuck in "Fetching…" state. Therefore, all the data about channel open/close fees isn't reflected in the stats… The same happens if I try a different browser…
![image](https://github.com/lightninglabs/lightning-terminal/assets/1861169/72e2c32a-55c1-4e93-97a4-b3a866a9819d)

**System information**

lnd-remote mode with lnd 0.16.4, terminal 0.10.1
Windows 10 x64

There's nothing of interest in litd.log or in the browser console… I did encounter a similar bug with one of the older versions, but usually, clearing the browser data and repopulating helped. This time it made it worse - all channel open/close info is now lost…

**Comment by eliotcougar** [comment]
1. Yes, I create a new session, with a new pairing phrase. And I clear all the relevant data in the browser. Also, connecting from a separate empty browser (MS Edge) shows same behavior.
 
2. I am aware that everything is stored in LND. What I was trying to say is that in Terminal, there is no info on the sats spent on channel management, only on routing fees. Until channel actions are resolved, the fees spent on channel opening/closing aren't counted at the top of the page or in downloadable node report...

Previously I already experienced stuck channel actions from time to time, but I was able to resolve those by clearing data and reconnecting... This time, however, it didn't solve the issue - instead, all actions since the very beginning of this node are now stuck...

**Comment by levmi** [comment]
Thanks for the feedback and the report! We have tested this on our end and see similar issues. So, there is a bug/problem. We'll work to get this fixed in an upcoming release and keep you updated on our progress. Thanks again for the report, super helpful for us :)

**Comment by levmi** [comment]
Can you retry this now? We just released a new version to terminal.lightning.engineering, which should fix the issue.

**Comment by levmi** [comment]
Thanks for confirming! Closing for now, can always re-open.
