### ISSUE TITLE
`-lit-dir=` not used for the `mainnet` subfolder for everything

### ISSUE THREAD

**Issue by AndySchroder** [lightninglabs/lightning-terminal#596]
`-lit-dir=` not used for the `mainnet` subfolder for everything

**Expected behavior**

`-lit-dir=` used for everything

**Actual behavior**

~/.lit/mainnet/ was used

**To reproduce**

1. Run with `-lit-dir=/home/user/.lit2/`
2. No `lit.macaroon` and `accounts.db` files exist in `/home/user/.lit2/mainnet/` . Those files in `/home/user/.lit/mainnet/` get overwritten.

**System information**

Standalone install on ubuntu

Remote lnd

v0.10.1-alpha, self compiled

**Comment by ellemouton** [comment]
Thanks for catching! Fixed in #598
