### ISSUE TITLE
allow disabling unneeded subservers

### ISSUE THREAD

**Issue by AndySchroder** [lightninglabs/lightning-terminal#597]
Lightning Terminal has a nice LND Accounts feature. There are also a lot of other cool services bundled in Lightning Terminal that have nothing to do with LND Accounts:

- faraday
- loop
- pool
- taproot assets

For all of these services we have the `mode` option of `integrated|remote`. I'd like a third option of `disabled`, especially if you are running with `--disableui`.

I'd like the ability to disable all this other stuff for the following reasons:

- Reduce system resources.
- Eliminate attack vectors on unused services.
- Remove taproot assets if I don't want to work with non-bitcoin stuff (I know right now this is only enabled if you are on testnet, but I assume you will change that in the future).
- Running multiple instances of litd on the same machine just to have multiple LND Account systems is a complete mess with all the extra subservers. I need to adjust the data directory and the RPC TCP ports for every subserver.

Another option would be to separate the LND Accounts feature into its own stand alone application and then integrate it like all the other subservers are back into litd. Possibly you should allow for doing both.

Would it be currently possible to compile litd with some different flags without that other stuff in it, rather than have a setting to turn things off?

**Comment by levmi** [comment]
This should be enabled with this PR: https://github.com/lightninglabs/lightning-terminal/pull/537. Should be coming very soon, just waiting to finalize the UX components to complement the backend change.

**Comment by AndySchroder** [comment]
Most things are disabled now if I use

```
faraday-mode=disable
loop-mode=disable
pool-mode=disable
taproot-assets-mode=disable
```

However, I still get

`2024-08-28 16:23:13.035 [INF] AUTO: Starting Autopilot Client`

on startup. Seems like this should be disable able too if you just want to use the accounts feature.

**Comment by AndySchroder** [comment]
Sorry, looks like there is another option of a different category needed to disable autopilot: `autopilot.disable=true`.
