### ISSUE TITLE
gpg: keyserver receive failed: Server indicated a failure

### ISSUE THREAD

**Issue by Deekee62** [lightninglabs/lightning-terminal#603]
While doing a fresh install of v0.10.2 I got the following error, when verifying the release:

```
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 187F6ADD93AE3B0CF335AA6AB984570980684DCC
gpg: keyserver receive failed: Server indicated a failure

```

**Expected behavior**

Correct import of key to verify the manifest file and successful addition to my GPG keyring

**Actual behavior**

```
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 187F6ADD93AE3B0CF335AA6AB984570980684DCC
gpg: keyserver receive failed: Server indicated a failure
```

**To reproduce**

Doing a fresh install of v0.10.2

**System information**

I use Lightning Terminal as a standalone application.

Not sure yet in which mode to running Lightning Terminal, but most probably in **Channel balance mode**. 

Lightning Terminal was downloaded from:

[https://github.com/lightninglabs/lightning-terminal/releases/download/v0.10.2-alpha/lightning-terminal-linux-amd64-v0.10.2-alpha.tar.gz](url)

Linux MacMini 6.3.0-1-amd64 SMP PREEMPT_DYNAMIC Debian 6.3.7-1 (2023-06-12) x86_64 GNU/Linux

ATA device, with non-removable media
        Model Number:       CT1000MX500SSD1                         
        Serial Number:      2214E62401B8        
        Firmware Revision:  M3CR043 
        Transport:          Serial, ATA8-AST, SATA 1.0a, SATA II Extensions, SATA Rev 2.5, SATA Rev 2.6, SATA Rev 3.0

**Comment by guggero** [comment]
The command completes correctly for me:
```
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 187F6ADD93AE3B0CF335AA6AB984570980684DCC
gpg: key B984570980684DCC: "Viktor Tigerström <vtigerstrom@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

Unfortunately key servers aren't extremely reliable. Please try again.

**Comment by Deekee62** [comment]
Now after the 3rd try it seems to have completed successfully:
```
$ gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 187F6ADD93AE3B0CF335AA6AB984570980684DCC
gpg: key B984570980684DCC: public key "Viktor Tigerstr?m <vtigerstrom@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
