### ISSUE TITLE
Issues with the non-costudial pool account

### ISSUE THREAD

**Issue by bhg2023** [lightninglabs/lightning-terminal#608]
I had an account funded to create an Ask on the liquidity pool. After reinstalling Lightning Terminal, I can't see that Ask anymore and am unsure of it's status.  Where do I find it? and were is the fund?

**Comment by dstadulis** [comment]
Hi @bhg2023 

Could you provide more details about:
- the platform you're running on
- What steps you took while reinstalling (deleting the app and or application state)
- Run `pool accounts recover` and what the output is

**Comment by bhg2023** [comment]
- Umbrel / Ubuntu Latest Server Edition
- I deleted the app because it was crashing (e.g. Umbrel wasn't able to connect to it, or the lightening web terminal). Then installed it
- Where is this executable in Umbrel installation.

**Comment by guggero** [comment]
See https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery.

**Comment by bhg2023** [comment]
> See https://docs.lightning.engineering/lightning-network-tools/lightning-terminal/troubleshooting#pool-account-recovery.

Restored. Thank you!
