### ISSUE TITLE
Add support for depositing funds on the base layer

### ISSUE THREAD

**Issue by supertestnet** [lightninglabs/lightning-terminal#625]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I set up lnd and litd and when I finally log into lightning terminal, there's no way for me to deposit funds. I can't get inbound liquidity because it says I need to have channels first, and I can't open channels because it says I need funds on the base layer first, and I can't get funds on the base layer because there is no way to deposit them. I have to go back into the command line and find/run the newaddress command with the appropriate flag, which is annoying.

**Describe the solution you'd like**
I would like the Receive button to give me an option to deposit funds on the base layer to a regular bitcoin address.

**Comment by levmi** [comment]
Thanks for the feedback! Tracking this on our end and will prio. Would it be okay for you if this is on terminal.lightning.engineering? We can land it quicker there. Or, do you need/want it on locally hosted `litd` UI?

**Comment by supertestnet** [comment]
I'm okay with it being on your website first

**Comment by levmi** [comment]
This is now live on terminal.lightning.engineering! Thanks for the issue and feedback, closing this for now. But, feel free to re-open if you have any issues with it.
