### ISSUE TITLE
[litcli] internal error

### ISSUE THREAD

**Issue by dasiyes** [lightninglabs/lightning-terminal#630]
After running `litcli getinfo` I get the following error:
**[litcli] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: remote error: tls: internal error"**

If I will try `curl https://127.0.0.1:8443` the error is:
**curl: (35) OpenSSL/3.0.8: error:0A000438:SSL routines::tlsv1 alert internal error**

The configuration of the app in *lit.conf*:
```
lnd-mode=integrated
uipassword=************
httpslisten=0.0.0.0:8443
tlscertpath=~/.lit/letsencrypt/fullchain.pem
tlskeypath=~/.lit/letsencrypt/privkey.pem
letsencrypt=true
letsencrypthost=lit.ivmanto.dev
letsencryptdir=~/.lit/letsencrypt/
letsencryptlisten=8282
```
And the certificates for `lit.ivmanto.dev` is installed successfully with certbot for nginx. I have tried almost all possible combinations in the config - from the simplest suggested by the documents to the one above - with and w/o the certs file etc...

Any ideas on how to fix this issue?

PS - LND works well with this installation of litd.

**Comment by guggero** [comment]
If you're installing the certificate with `certbot` then you shouldn't set `letsencrypt=true`, otherwise `litd` will itself try to acquire the cert and likely fail.

**Comment by dasiyes** [comment]
It is set in the conf file. Does the position of this parameter in the list make some difference?

**Comment by guggero** [comment]
This seems to be related to https://github.com/lightninglabs/lightning-terminal/issues/631. Closing this one to keep the discussion in a single issue.
