### ISSUE TITLE
use already existing LetsEncrypt certificate in LIT's config file

### ISSUE THREAD

**Issue by dasiyes** [lightninglabs/lightning-terminal#631]
It seems that once the Letsencrypt is set to TRUE in the lit.conf file, according to the code below from config.go [417-427]:
```
	if cfg.LetsEncrypt {
		if cfg.LetsEncryptHost == "" {
			return nil, fmt.Errorf("host must be set when using " +
				"let's encrypt")
		}

		// Create the directory if we're going to use Let's Encrypt.
		if err := makeDirectories(cfg.LetsEncryptDir); err != nil {
			return nil, err
		}
	}
```
the app tries to create the directory (and it works :)) - but it would be nice to just use this directory (if already exists - assuming the cert / key are in it) instead of only trying to create it and generate the cert/key pair.

**Comment by dasiyes** [comment]
I have this subdomain `lit.ivmanto.dev`, and using `certbot` on Ubunto for `nginx`, I have created a Letsencrypt certificate for this subdomain. Now, if I try to add the folder where Letsecrypt has created the certificate and the key files, at startup, LITD says cannot create the folder because it already exists.
I was wondering how to add the existing certificate path in the `lit.conf` file in such a way that it uses the already existing certificate and existing folder instead of trying to create a new certificate. 

I hope this makes more sense now as a request.

**Comment by dasiyes** [comment]
So - that worked for me. 👍 
I have only added `letsencryptdir=/etc/letsencrypt/live/domain-name/` in the config file and commented out the `letsencrypt=true`.
Do I understand it correctly now that `letsencrypt=true` should be only used in lit.conf file when litd is supposed to `create` the Letsencrypt certificate on its own and not when using the Letsencrypt as certificate vendor?

Thanks a lot for the clarification.

**Comment by guggero** [comment]
Exactly.

From `litd --help`:
```
      --letsencrypt                                                              Use Let's Encrypt to create a TLS certificate for the UI instead of using
                                                                                 lnd's TLS certificate. Port 80 must be free to listen on and must be
                                                                                 reachable from the internet for this to work.
```

Any other config options that start with `letsencrypt` will be ignored if `letsencrypt=false`.
