### ISSUE TITLE
[bug] Autoloop feature incorrectly flags 'no open channels' 

### ISSUE THREAD

**Issue by hieblmi** [lightninglabs/lightning-terminal#650]
On a mainnet node with 20 active channels the autoloop Tab flags the following, preventing me from setting up autoloops.

<img width="838" alt="image" src="https://github.com/lightninglabs/lightning-terminal/assets/18631614/475d5de8-577a-49ac-a455-9f7058c6c05e">

**Comment by levmi** [comment]
Are you trying to set up an Autoloop or do you have channels actively Autolooping? The function of this tab is to filter from the list of all your channels, the subset that is currently Autolooping. To setup Autoloops, you can just drag and drop the slider on a particular channel and then click Autoloop. From there, just follow the UX.

**Comment by hieblmi** [comment]
Yes, I am trying to set up an Autoloop, and apologies, I was mistaking this tab for the place to set things up. The slider setup is actually very clear and intuitive in hindsight.
