### ISSUE TITLE
Connecting to terminal and permissions

### ISSUE THREAD

**Issue by Barba732** [lightninglabs/lightning-terminal#658]
Does connecting to terminal with a read only session, blocks fee autopilot?

**Comment by guggero** [comment]
Yes. The to enable the autopilot on your node, you can't use a read-only session with terminal.lightning.engineering.

**Comment by levmi** [comment]
Thanks @guggero! Yep, that's 100% accurate. You cannot enable Autopilot on your node with a read-only session. Read-only, as the name suggests :), only allows for you to see the node data, but not make any changes to the node/liquidity management. 

Depending on your use case, you could use an admin session to turn on Autofees on your node. Then, grant yourself or someone else, again depending on your use case, access to the node using a read-only session. That flow wouldn't interrupt Autofees as once something is setup then the creation of a read-only session has no impact.

**Comment by Barba732** [comment]
Sorry I was not 100%clear, I already had an admin session which activated autopilot, then I revoked the admin session but the autopilot remained. Then I login in many other times but as read-only sessions. Autopilot session is always there, but as I see no activities for a few days I wonder if I need to grant an admin session again.
