### ISSUE TITLE
Add Signet support to non-liquidity service components of `litd`

### ISSUE THREAD

**Issue by zoop-btc** [lightninglabs/lightning-terminal#661]
**Is your feature request related to a problem? Please describe.**
I'd love to use lightning terminal in my signet environment.

**Describe the solution you'd like**
Adding the signet network option in addition to mainnet, simnet, testnet & regtest.

**Describe alternatives you've considered**
No alternative.

**Additional context**
No additional context needed

Thank you and best regards,
Zoop

**Comment by MegalithicBTC** [comment]
Just pushing this up to see it's somehow been resolved but not noted in this issue. Using LND, we can use this configuration option:

```
bitcoin.signet=true
```
And then LND works well with Mutinynet (which is a signet).

Trying the same option in `lit.conf` ...
`lnd.bitcoin.signet=true` 
... produces the error:
```
could not load config: ValidateConfig: The mainnet, testnet, regtest, simnet and signet params can't be used together -- choose one of the five
```

**Comment by dstadulis** [comment]
Issue fulfilled, given #902 merged
