### ISSUE TITLE
No ‘Send’ records found in the history records

### ISSUE THREAD

**Issue by originalix** [lightninglabs/lightning-terminal#681]
Hello, since November, my Terminal no longer displays the history of Send type data, meaning I can’t see the data from `lncli listpayments`. Could you please advise me on what to do? I have tried disconnecting and reconnecting to the Terminal, and also restarting the LND node, but none of them have worked.

Just as shown in the screenshot, there have been no off-chain send records after October 30th.

**Expected behavior**

Send type data can be correctly displayed in the history records

**Actual behavior**
There are no off-chain send records in the history records.

**To reproduce**

I’m sorry, but I currently don’t know how to reproduce the issue.

**System information**

- lncli version 0.16.4-beta commit=v0.16.4-beta
- litcli version 0.10.5-alpha commit=v0.10.5-alpha

![CleanShot 2023-11-13 at 21 58 56@2x](https://github.com/lightninglabs/lightning-terminal/assets/16911056/cb304b22-99e4-496c-9dc2-97a30904d6fd)

**Comment by levmi** [comment]
Thank you for filing this issue! We're going to work on a fix for this shortly. Will circle back once it's implemented for testing!

**Comment by levmi** [comment]
Should be fixed with some of our more recent releases, but feel free to re-open if it's not!
