### ISSUE TITLE
password for lightning terminal

### ISSUE THREAD

**Issue by mariof72tor** [lightninglabs/lightning-terminal#690]

**Comment by levmi** [comment]
Hi - We'll need more information to help you with any issues. Please provide a description of what's happening so we can support and help debug!

**Comment by Karthi02116K** [comment]
When I installing terminal-password,it showing this Error,I also bold this Error 

_**Building wheel for terminal-password (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for terminal-password (pyproject.toml) did not run successfully.
  │ exit code: 1**_
  ╰─> [18 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'terminal_password' extension
      creating build
      creating build/temp.linux-aarch64-cpython-311
      aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC -I/data/data/com.termux/files/usr/include/python3.11 -c password.c -o build/temp.linux-aarch64-cpython-311/password.o
      _**password.c:16:51: warning: passing 'const char *[2]' to parameter of type 'char **' discards qualifiers in nested pointer types [-Wincompatible-pointer-types-discards-qualifiers]
         16 |         if (!PyArg_ParseTupleAndKeywords(args, kw, "|O", key, &a))
            |                                                          ^~~**_
      /data/data/com.termux/files/usr/include/python3.11/modsupport.h:29:72: note: passing argument to parameter here
         29 |                                                   const char *, char **, ...);
            |                                                                        ^
      _**password.c:66:18: error: incompatible function pointer types initializing 'PyCFunction' (aka 'struct _object *(*)(struct _object *, struct _object *)') with an expression of type 'PyObject *(PyObject *, PyObject *, PyObject *)' (aka 'struct _object *(struct _object *, struct _object *, struct _object *)') [-Wincompatible-function-pointer-types]**_
         66 |         {"get_password",test, METH_VARARGS|METH_KEYWORDS,"get_password function"},
            |                         ^~~~
_**      1 warning and 1 error generated.
      error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
      [end of output]**_

  _**note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for terminal-password
Failed to build terminal-password
ERROR: Could not build wheels for terminal-password, which is required to install  pyproject.toml-based projects**_
