### ISSUE TITLE
UTXO missing after failed batch channel open

### ISSUE THREAD

**Issue by evenkeel** [lightninglabs/lightning-terminal#701]
I used the terminal app to try to batch open 3 channels. I completed all the steps and got to the last step and clicked batch open channels but nothing happened except a spinning wheel so after a couple minutes I x'd out of the window. 

I then used the Lightning Node app on Umbrel to try to open a single channel. That also failed. 

I then noticed that my balance was missing a massive UTXO that would have been used for the batch opening of 3 channels that I tried on Terminal. That UTXO is no longer showing up anywhere in my wallet. And I don't see any channels as pending either. It's like the UTXO has vanished without a trace - and there is no transaction anywhere to be found. 

Part of me feels like this will just be resolved with time and the sats will show back up in my wallet - but I don't like that I can't see any trace of them right now.

**Comment by levmi** [comment]
Do you have CLI access for this node? If so, do you see anything returned for `lncli pendingchannels` or `lncli listchaintxns`?

**Comment by evenkeel** [comment]
OK I stopped and rebooted LND and now my balance is correct. I'm not sure what happened but we are all good now. I appreciate your responsiveness on Christmas Eve! Have a great one. Thanks.

**Comment by levmi** [comment]
Of course. Glad it all got sorted before the holiday!
