### ISSUE TITLE
Remote fee shows as 5000 when it is actually 0

### ISSUE THREAD

**Issue by Liongrass** [lightninglabs/lightning-terminal#702]
I have a channel, opened by a remote peer. Initially they set their fee at 5000pm, then lowered it to 0. I can confirm that with `lncli getchaninfo`. Lightning Terminal however still shows the channel with a remote fee of 5000pm. This also affects the liquidity report, which shows the channel in the 5000ppm bucket.

**Actual behavior**

**To reproduce**

`"0.12.1-alpha commit=v0.12.1-alpha"`
compiled from source.

lnd remote, faraday, loop, pool integrated, taproot assets disabled.

**Comment by jamaljsr** [comment]
Hey @Liongrass are you still facing this issue? In Terminal, the fees are cached in your browser for 24 hours. That could explain why you were seeing the older fee rate.

**Comment by Liongrass** [comment]
Hi! It's been over a month that I noticed it, and as of now the fee still shows up as 5000ppm.

**Comment by jamaljsr** [comment]
Interesting. Can you try running `localStorage.removeItem('feeRates');` in your browser console, then reload the page. This will purge all fee data persisted in your browser.

**Comment by Liongrass** [comment]
I'm not sure I'm doing that right. When I hit enter in the console, I see the message "undefined". I do see the item "feeRates" in the local storage tab disappearing though. Looking at the raw "feeRates" data, I can see `"891142079706759175":0,`, which is the correct remote fee for that channel. It's the same fee I see for `lncli getchaninfo 891142079706759175`.
In the Terminal channel list however I still see the remote fee as 5000.

I then deleted the cache and local data, obtained a new pairing phrase and looked at the remote channel fee again, and it now shows as `3049 PPM`, which is equivalent to the channel's local fee, which in the "Autopilot" tab I can see was raised yesterday from `2983 PPM`. Under local storage the fee is still correct at `"891142079706759175":0`

![Screenshot from 2024-01-16 14-19-29](https://github.com/lightninglabs/lightning-terminal/assets/2104935/3fa793c6-ef18-4179-ba6b-1e69fb2928ce)

**Comment by jamaljsr** [comment]
Ahhh, I see the problem. We currently don't handle zero fee rate values properly. We'll get this fixed soon.

**Comment by levmi** [comment]
Should be fixed with the most recent release, but feel free to re-open if it's not!
