### ISSUE TITLE
Dashboard profit wrong amount

### ISSUE THREAD

**Issue by superkruger** [lightninglabs/lightning-terminal#710]
**Expected behavior**
On the dasboard, profit in sats should be displayed correctly.

**Actual behavior**
In the summary, as well as the 'fees earned' box it's displayed incorrectly.
The summary displays it as 'actual sats earned' * 10 sats
The 'fees earned box' displays it as 'actual sats earned' * 10000

I've attached screenshots of the amounts.
E.g. 273 sats should be 27.3 sats
And 273,356 sats should also be 27.3 sats

**To reproduce**
View dashboard

**System information**

Standalone app

integrated-mode, pool-mode

0.12.2-alpha, website download

Raspberry pi

![Screenshot from 2024-01-23 13-10-35](https://github.com/lightninglabs/lightning-terminal/assets/992768/9123f36b-213f-43af-9c0c-9ed6444e85df)
![Screenshot from 2024-01-23 13-11-35](https://github.com/lightninglabs/lightning-terminal/assets/992768/c81485a7-feb6-40c2-bfcd-9376ba4b9f69)
![Screenshot from 2024-01-23 13-11-50](https://github.com/lightninglabs/lightning-terminal/assets/992768/94c0343c-92f4-4f1d-8450-da69ec20daa1)
![Screenshot from 2024-01-23 13-12-11](https://github.com/lightninglabs/lightning-terminal/assets/992768/baef18ff-a344-4d96-baff-a7301b948cfa)

**Comment by levmi** [comment]
Can you share your exported CSV from the info button under the Spent category? Then, we can see the full list to see what's happening here?

**Comment by superkruger** [comment]
[earned_spent.csv](https://github.com/lightninglabs/lightning-terminal/files/14026908/earned_spent.csv)

It only seems to affect the daily amounts.
Weekly, etc are correct.

**Comment by levmi** [comment]
Hi, this will be fixed in our next release next Tuesday! Thanks for reporting!

**Comment by levmi** [comment]
Should be fixed with the most recent release, but feel free to re-open if it's not!
