### ISSUE TITLE
Sat blocked

### ISSUE THREAD

**Issue by TempTempesta** [lightninglabs/lightning-terminal#720]
Hi,
after i started a loop out is 2 days that i have the loop blocked on the second passage and my sats are not anymore on the channel and not in my wallet, what can i do?

**Comment by levmi** [comment]
Can you provide us with some more logs from Loop and litd so we can help debug this issue?

**Comment by TempTempesta** [comment]
thanks, levmi. where i can find in  Lightning Terminal for umbrel this logs?

**Comment by levmi** [comment]
You should be able to grab some of the logs from Umbrel settings --> troubleshoot

**Comment by TempTempesta** [comment]
this is the log for lightning terminal:
lightning-terminal

Attaching to lightning-terminal_tor_server_1, lightning-terminal_web_1, lightning-terminal_app_proxy_1
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
app_proxy_1   | Validating token: c1067bd28a72 ...
web_1         | }
web_1         | 
web_1         | 2024-02-12 15:54:13.728 [INF] UNIV: Attempting to sync universe: host=universe.lightning.finance:10029, sync_type=full, ids=([]universe.Identifier) <nil>
web_1         | 
web_1         | 2024-02-12 15:54:13.756 [INF] UNIV: Fetching 0 roots
web_1         | 2024-02-12 15:54:13.756 [INF] UNIV: Obtained 0 roots from remote Universe server
web_1         | 2024-02-12 15:58:37.064 [INF] RPCS: Received new block notification: height=830160
web_1         | 2024-02-12 15:58:37.064 [INF] LOOP: Received block 830160
web_1         | 2024-02-12 15:58:37.064 [INF] LOOP: 1f1be3 Checking preimage reveal height 830238 exceeded (height 830160)
web_1         | 2024-02-12 15:58:37.065 [INF] GRDN: New block at height 830160


but i don't see any problem on the 7-2-24

**Comment by levmi** [comment]
You may have to dig a bit deeper to access the underlying Lightning Terminal and Loop logs. You can ask the Umbrel team how to access those here: https://t.me/getumbrel

Is the Loop still stuck? Oftentimes, this problem will resolve after a few days.

**Comment by levmi** [comment]
I assume that this issue has sorted itself out given lack of response. Feel free to re-open if not.
