### ISSUE TITLE
lnd binary missing from lightning-terminal-linux-amd64-v0.12.3-alpha.tar.gz 

### ISSUE THREAD

**Issue by cj-chua** [lightninglabs/lightning-terminal#727]
As pointed out in the title, lnd binary is missing from the latest linux-amd64 release lightning-terminal-linux-amd64-v0.12.3-alpha.tar.gz

**Comment by bitromortac** [comment]
I don't think the lnd binary is part of the release (checked a few releases), but you can run lnd in internal mode by default when running litd.

**Comment by guggero** [comment]
`lnd` is built into `litd`, it's part of that binary. That's why only `litd` and all the `*cli` binaries are included in the release. See https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-integrated.md.

**Comment by cj-chua** [comment]
My bad guys, got confused!
