### ISSUE TITLE
Funds lost after Loop Out got stuck

### ISSUE THREAD

**Issue by M31andromeda** [lightninglabs/lightning-terminal#741]
I initiated a Loop Out on LiT but it was stuck for several hours showing the "initiated" message.

I then found this report:

https://github.com/lightninglabs/loop/issues/354

So I decided to restart both LND and LiT as advised. 

The status now shows "Off-chain Failure" but the payment (over 1.000.000 SATs!) was not redirected to my off-chain funds.

Any ideas how I can get it back?

**Comment by bhandras** [comment]
Hi @M31andromeda thanks for your report!

Can you please share the swap hash so we can look closer into it?

**Comment by M31andromeda** [comment]
Sure. Can you please point me towards the place where I can find it? Sorry, I'm a noob. ;)

**Comment by hieblmi** [comment]
On the command line you can do `loop listswaps` and check for the `id` of the affected swap.
Or within LiT you should be able to find the swap id on the Loop page or in the history view of your LiT.

**Comment by M31andromeda** [comment]
Thanks for your help. I just rechecked and my balance is now correct again. So no more lost funds!!!

It was this ID: 808a4ccf73f4c5e7c3b66ad828eda9b2328474d10a4208fb16b038aa7de492a0

**Comment by levmi** [comment]
Thanks for the report and glad it got resolved!
