### ISSUE TITLE
Clearnet IP of Node outdated , wont update

### ISSUE THREAD

**Issue by Funman2** [lightninglabs/lightning-terminal#743]
Hey,
I am running an umbrel node on clearnet/tor hybrid mode, everything is configured right and tested, my IP is updated via Dyndns and all lightning network directories ( Amboss.space, 1ml, Lighning Networkplus, etc )are getting new IP address after my ISP changed it, except Lightning Terminal. Why does it not update even after days?

**Comment by Funman2** [comment]
it did opropagate now after serveral days, solved.

**Comment by ViktorTigerstrom** [comment]
Hi @Funman2,

Thanks for the issue report! I was just about to write you a reply, but great to hear that the issue has already been resolved!
