### ISSUE TITLE
TLS certificates are not automatically recreated when deleted (litd integrated mode)

### ISSUE THREAD

**Issue by Liongrass** [lightninglabs/lightning-terminal#753]
From time to time it may be necessary to regenerate your `tls.cert`, which requires you to regenerate your `tls.key` as well.

The process should be:

- Shut down litd
- Delete `tls.key` and `tls.cert` in `~/.lnd`
- Start litd

**Expected behavior**

I expect litd to generate both `tls.cert` and `tls.key` on startup.

**Actual behavior**

Litd does not start up. Instead it gives the error message:

`2024-04-26 18:09:01.115 [ERR] LTND: Shutting down because error in main method: error setting cert before unlock: unable to generate or renew TLS certificate: open /home/ubuntu/.lnd/tls.key: no such file or directory`

A workaround can be to compile LND on the same machine, translate the `lit.conf` to `lnd.conf`, start LND, wait for it to generate the certificates, shut down LND and restart Litd.

**To reproduce**

**System information**

`"version": "0.12.4-alpha commit=v0.12.4-alpha-dirty"`
Litd integrated mode.

**Comment by ellemouton** [comment]
closing since OP has said offline that issue has been solved 🎉
