### ISSUE TITLE
The  v0.13.99-alpha.rc3   branch of  lightning-terminal   does not contain the path  doc/WALKTHROUGH.md.

### ISSUE THREAD

**Issue by RajGoodF** [lightninglabs/lightning-terminal#791]
Walkthrough file missing.

**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

**Comment by ellemouton** [comment]
The v0.13.99-alpha.rc3 tag points to commit:  2f0f95d019bca42bc5e4593424b85d8ca3c6ae1a which does contain the walkthrough.md file: https://github.com/lightninglabs/lightning-terminal/blob/2f0f95d019bca42bc5e4593424b85d8ca3c6ae1a/docs/WALKTHROUGH.md

**Comment by ellemouton** [comment]
ah @RajGoodF  - I think the issue is that the `doc` folder was recently renamed to `docs`

**Comment by guggero** [comment]
Thanks for the report. Created a fix here: https://github.com/lightninglabs/lightning-terminal/pull/792, will cherry-pick this into the staging branch once merged.
