### ISSUE TITLE
12 UNIMPLEMENTED: unknown service priceoraclerpc.PriceOracle"

### ISSUE THREAD

**Issue by jimtracy1007** [lightninglabs/lightning-terminal#822]
`rpc QueryRateTick (QueryRateTickRequest) returns (QueryRateTickResponse);`
I call bakemacaroon,permissions=[{
entity: “uri”,
action: “/priceoraclerpc. PriceOracle/QueryRateTick”,
}]
return : 2 UNKNOWN: invalid permission action, must be an existing URI in the format /package.Service/MethodName.

**Actual behavior**

**To reproduce**

**System information**

https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.13.993-experimental

**Comment by ellemouton** [comment]
hi @jimtracy1007  - are you specifying the `--allow_external_permissions` flag?

**Comment by jimtracy1007** [comment]
I accessed it using RPC interface, where can I configure it?

**Comment by jimtracy1007** [comment]
Oh,I'll try,thanks.

**Comment by guggero** [comment]
> rpc QueryRateTick (QueryRateTickRequest) returns (QueryRateTickResponse);

This isn't an RPC that's implemented by `lightning-terminal` or `tapd`. You need to build your own price oracle if you want to use a real one and not the internal mock.

See https://github.com/lightninglabs/taproot-assets/blob/main/docs/examples/basic-price-oracle/main.go.

So even if you could bake a macaroon, it wouldn't help you.

**Comment by jimtracy1007** [comment]
I created an invoice through the taprootassets channel, but when I parsed it, I couldn't get how many taprootassets it corresponded to, which was worth the value in sats units. How can i get the taprootassets account?

**Comment by guggero** [comment]
Do you have a taproot assets channel? Then you can ask your peer for a quote using [`rfqrpc.AddAssetSellOrder`](https://lightning.engineering/api-docs/api/taproot-assets/rfq/add-asset-sell-order).

Also see https://docs.lightning.engineering/lightning-network-tools/taproot-assets/rfq and https://docs.lightning.engineering/lightning-network-tools/taproot-assets/taproot-assets-channels.

For general questions and troubleshooting I'd also recommend joining [our developer Slack server](https://lightning.engineering/slack.html) or creating **discussions** [here](https://github.com/lightninglabs/taproot-assets/discussions).
