### ISSUE TITLE
[CI] Create lighting-terminal PR CI job which persistently updates litd's tapd dependency to main HEAD

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/lightning-terminal#827]
## Motivation:
- When changes to tapd occur, in order to fully conclude the ramifications of the PR, testing must occur in litd CI pipeline.
- There have been instances of tapd PRs been merged, but testing coverage could have been more comprehensive.
- By creating these perpetually updating tapd dependency PRs, the cross-daemon CI process will be less fault prone

### An update notification method
`entr`
Github Actions
Time-based cron job 

### Should Update
the tapd module dependency to 
- origin/main HEAD
- or be extensible to set a development branch (for future releases where engineers want to refrain from merging into main)

**Comment by ellemouton** [comment]
(also - i'd say this is something that needs to happen on the taproot-assets github actions side since there you can subscribe to actions from the tap repo)

**Comment by dstadulis** [comment]
> Do you only want things to run on merge to master or do you want things to run when a new PR is opened?

ah yeah probably most appropriate for the checks to run during PR
