### ISSUE TITLE
Can't access lit - error on the webpage

### ISSUE THREAD

**Issue by utnet9684** [lightninglabs/lightning-terminal#832]
I have installed litd on one node, running debian 11 on x86 with minibilt guide. I have LND 0.18.2 installed and litd 0.13.3

I have the following error while trying to access the page:
Error when creating LND Services client: error subscribing to lnd wallet state: lnd version incompatible, need at least v0.13.0-beta, got error on state subscription: rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: tls: failed to verify certificate: x509: certificate signed by unknown authority"
LND is not running. Please start lnd and try again.

**Comment by dstadulis** [comment]
>LND is not running

It looks like the issue might be related to LND not running, as indicated by the error message. Can you please confirm that LND is indeed started and running on your system?

```bash
pgrep lnd
lncli --version
```

**Comment by ViktorTigerstrom** [comment]
Hi @utnet9684,
We just had another issue with the exact same issue who had been following the minibolt guide:
https://github.com/lightninglabs/lightning-terminal/issues/831

This was resolved by:
1. Removing the `tlsencryptkey=true` flag from the `lnd.conf`
2. Remove the `tls.cert` in the `lnd` folder.
3. Restarting `lnd`.

Hope that helps!

**Comment by utnet9684** [comment]
> Hi @utnet9684, We just had another user with the exact same issue who had been following the minibolt guide: #831
> 
> This was resolved by:
> 
>     1. Remove the `tlsencryptkey=true` flag from the `lnd.conf`
> 
>     2. Remove the `tls.cert` in the `lnd` folder.
> 
>     3. Restart `lnd`.
> 
> 
> Alternatively, you can run `litd` in integrated mode with `tlsencryptkey` enabled as I've described in this comment: [#831 (comment)](https://github.com/lightninglabs/lightning-terminal/issues/831#issuecomment-2310744557)
> 
> Hope that helps!

It worked! Thanks!
