### ISSUE TITLE
`./release.sh` produces tags of different lengths, across certain hosts

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/lightning-terminal#854]
# Background
Digest entries in the manifest file are produced here:
https://github.com/lightninglabs/lightning-terminal/blob/43ac9fac94cd158e1b7c560555f2a7b565c307f9/release.sh#L91

Assigned from here:
https://github.com/lightninglabs/lightning-terminal/blob/43ac9fac94cd158e1b7c560555f2a7b565c307f9/release.sh#L33

Called from here
https://github.com/lightninglabs/lightning-terminal/blob/43ac9fac94cd158e1b7c560555f2a7b565c307f9/Makefile#L164C30-L164C45

Defined here:
https://github.com/lightninglabs/lightning-terminal/blob/43ac9fac94cd158e1b7c560555f2a7b565c307f9/make/release_flags.mk#L1C23-L1C42

# Issue
@ViktorTigerstrom produced a build **with** an **extra** character, `a`, at the end of the tag
```log
lightning-terminal-darwin-amd64-v0.13.995-experimental-1-g8da6c29a
```

On two different hosts[1], after running
```bash
make release tag=v0.13.995-experimental
```

a build with tags **without** the `a` character, at the end of the tag are produced
```log
lightning-terminal-darwin-amd64-v0.13.995-experimental-1-g8da6c29
```

[1] Hosts running:
git version 2.46.2
git version 2.30.2

# Reproduce
- [ ] Reproduce git tag with extra `a` character
  - @ViktorTigerstrom report the output of 
git describe --tags
git --version
- [ ] Determine any differences in `git describe` has occurred between the git versions

**Comment by ViktorTigerstrom** [comment]
@dstadulis thanks! 

`git describe --tags` when having pr #853 checked out results in:
`v0.13.995-experimental-1-g8da6c29a`

`git --version` is:
`git version 2.45.2`

**Comment by guggero** [comment]
Just a general/drive-by comment that `litd` release builds are _NOT_ yet fully reproducible. I think there might be other things than just the git tag that could cause differences in the build (biggest unknown being the frontend/UI/NodeJS build, not sure if that can even be made reproducible in the first place).

**Comment by dstadulis** [comment]
have a fix for the git tag issue, targeting to post soon.

Will create an issue cataloging the factors that affect reproducibility

**Comment by dstadulis** [comment]
Fixed in https://github.com/lightninglabs/lightning-terminal/pull/864
