### ISSUE TITLE
itests: Assert payment+invoice HTLC custom wire records are persisted, returned

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/lightning-terminal#860]
Given https://github.com/lightningnetwork/lnd/issues/8769 has been merged, this issue can be started.

As discussed in https://github.com/lightninglabs/taproot-assets/issues/1091, litd should update integration tests to 
- [x] Assert the lnd changes to persist payment+invoice HTLC custom wire records and return them in RPCs hold true.

Specifically, itest should validate:

- [x] (maintainer edit: seems this functionality has been confirmed in https://github.com/lightninglabs/taproot-assets/issues/1091) SendPaymentResponse_AcceptedSellOrder response is returned with the correct assets amount 
- [x] (maintainer edit: seems this functionality has been confirmed in https://github.com/lightninglabs/taproot-assets/issues/1091) Custom data fields are added to the lnrpc.InvoiceHtlc and lnrpc.HtlcAttempt messages
- [x] Wire-level custom message data attached to HTLCs in invoices and payments is persisted
- [x] Functional purity / existing functionality doesn't break

**Comment by guggero** [comment]
Fixed by https://github.com/lightninglabs/lightning-terminal/pull/879.
