### ISSUE TITLE
Add tests exercising fundchannel

### ISSUE THREAD

**Issue by dstadulis** [lightninglabs/lightning-terminal#868]
https://github.com/lightninglabs/lightning-terminal/pull/865 corrects the fundchannel functionality to allow a channel to be created of an amount that is less than the cumulative available asset amounts.

## MVP TODO
- [x] test whether multi-input asset funding of a custom channel works

## Test-dimension scope to consider:
Positive and negative tests exercising this functionality shall be added asserting channel funding given:
- Single, Multiple asset UTXOs
- A fund_channel size less than, equal, or greater than, the input amounts

**Comment by gijswijs** [comment]
#882 fixes this. I'm closing this issue.
