### ISSUE TITLE
View details of each channel

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/lightning-terminal#88]
In the channel list, LiT currently only displays a small subset of information about each one. It would be beneficial to display more information on a specific channel when clicked. This could be displayed as a modal, expandable row, or viewed in the top panel.

Additional details could include funding transaction id and date, send/receive totals, base fee rate, time lock, reserve amounts.

**Comment by levmi** [comment]
Included in Terminal UI/dated. Closing.
