### ISSUE TITLE
"Node is unconnectable" + Health red tag reading "Offline" for days (web dashboard)

### ISSUE THREAD

**Issue by GTCLive** [lightninglabs/lightning-terminal#900]
When I pair my Clearnet + Tor node with https://terminal.lightning.engineering and access the dashboard drop-down, it permanently claims the state of my node being "Node is unconnectable" with a Health red tag reading "Offline". This is false, and therefore a broken feature that requires fixing imo. 

Ironically, my node shows LIVE and perfectly healthy on several other explorers; 1ML.com, Amboss.space, Lightningnetwork.plus (to name only 3). Yet showing up offline in its own management dashboard and missing from its node explorer. 

Please fix!

**Comment by levmi** [comment]
How long has the node existed? Can you share what LND/litd version you are on?

**Comment by GTCLive** [comment]
Little less than a week, I'd say 5 or 6 days now. Has both announced and private channels. 

`$ git checkout v0.13.6-alpha`

**Comment by levmi** [comment]
And to be clear, this is on the dashboard when you're connecting using a pairing phrase? So, you can't accomplish actions like channel opens, etc.? Not just on the Terminal list which shows the list of nodes?

Thanks :)

**Comment by GTCLive** [comment]
Correct. Clearnet & Tor checks, can open/close chans, looping and everything's fine, look almost good to go!! Just this weird persistent "Offline" bug. Mind you I call it a bug because it clearly shows LIVE in several other explorers, and so not entirely sure what to make of this. Gotta broken on your side ;)

![Untitled-1](https://github.com/user-attachments/assets/f15dd6e2-18b0-416a-bc9f-eb0776f537ac)

**Comment by GTCLive** [comment]
Fwiw I'm getting a fairly recurrent log spam about this DONT_FORWARD set bit for a public channel. Wondering if this is what prevents LIT/LND nodes from being indexed in the terminal explorer and as a result showing offline. Just leaving this here, never know...

`2024-11-07 18:31:28.347 [WRN] HSWC: ChannelLink(a70a30fd...........41c2be7f79:0): received warning message from peer: chan_id=0000000000000000000000000000000000000000000000000000000000000000, err=Do not set DONT_FORWARD on public channel_updates (868562x1877x1)`
`2024-11-07 18:31:28.405 [WRN] HSWC: ChannelLink(a70a30fd...........41c2be7f79:0): received warning message from peer: chan_id=0000000000000000000000000000000000000000000000000000000000000000, err=Do not set DONT_FORWARD on public channel_updates (868816x3153x0)`
`2024-11-07 18:31:28.439 [WRN] HSWC: ChannelLink(a70a30fd...........41c2be7f79:0): received warning message from peer: chan_id=0000000000000000000000000000000000000000000000000000000000000000, err=Do not set DONT_FORWARD on public channel_updates (868864x2287x0)`
`2024-11-07 18:31:28.440 [WRN] HSWC: ChannelLink(a70a30fd...........41c2be7f79:0): received warning message from peer: chan_id=0000000000000000000000000000000000000000000000000000000000000000, err=Do not set DONT_FORWARD on public channel_updates (869007x887x0)`

**Comment by bitromortac** [comment]
That "offline" label says something about the long-term stability of your node and it updates only after you've been online consistently for a time span of two weeks. I think "Node is unconnectable" may be a wrong tool-tip for that. Every explorer has their own way of measuring this quality, which is why you may see discrepancies.

The warnings you see are unrelated, those are complaints from your peer that you forwarded channel updates that are not valid, but this can be addressed on the lnd side.

**Comment by GTCLive** [comment]
@bitromortac Thank you for the time taken. Ok, Two Weeks. Omg I didn't know. In that case, could I recommend (advise?) for the node status to be amended from "Node is Unconnectable" & "Red Offline" to let's say Pending or Awaiting Indexing or anything slightly more coherent with the actual node situation. And have this offline connectivity feature revised please, guys, c'on. 

It took me quite bit of time to set-up that node, that's actually my third attempt at it. What took the longest was that failed connectivity status in fact. From trying several VPNs, clearnet hosts, Tor configs, I tried everything possible in an attempt to establish a "Connected State" to Terminal. With that said, no thank you very much do not delete any of my data - most precious data on the internet atm... emotionally attached to it. I'm grateful for the offer though. 

Do close this issue/ticket if you believe the existing node state incoherence and contradiction should remain the way it is and continue confusing new users. That's your call.

**Comment by GTCLive** [comment]
@bitromortac Thank you for the time taken. Ok, Two Weeks. Omg I didn't know. In that case, could I recommend (advise?) for the node status to be amended from "Node is Unconnectable" & "Red Offline" to let's say Pending or Awaiting Indexing or anything slightly more coherent with the actual node situation. And have this offline connectivity feature revised please, guys, c'on.

It took me quite bit of time to set-up that node, that's actually my third attempt at it. What took the longest was that failed connectivity status in fact. From trying several VPNs, clearnet hosts, Tor configs, I tried everything possible in an attempt to establish a "Connected State" to Terminal. With that said, no thank you very much do not delete any of my data - most precious data on the internet atm, I am emotionally attached to it. I'm grateful for the offer though.

Please close this issue/ticket if you believe the existing node state incoherence and contradiction should remain the way it is and continue confusing new users. That's your call.

**Comment by levmi** [comment]
Thanks so much for the report. We'll be changing the language to "Evaluating Node" to better reflect what is happening in the background. We've created an issue on our internal repo to track the fix. I will close this issue given that :)
