### ISSUE TITLE
Update lnd.conf syntax in the README

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/lightning-terminal#97]
The README currently specifies the following configuration for the `lnd.conf` file.

```
[Application Options]
httpslisten=0.0.0.0:8000
uipassword=Pa55w0rd
lnd.debuglevel=debug

[Bitcoin]
lnd.bitcoin.active
lnd.bitcoin.testnet
lnd.bitcoin.node=neutrino

[Neutrino]
lnd.neutrino.addpeer=btcd-testnet.lightning.computer
lnd.neutrino.feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json

[Loop]
loop.loopoutmaxparts=5

[Faraday]
faraday.min_monitored=48h
```

The lines `lnd.bitcoin.active` and `lnd.bitcoin.testnet` are not valid. They must contain `=1` to specify a true value. These values can be ommitted on the command line, bu not in the config file.  

The README should be updated with the correct values.

**Comment by pinheadmz** [comment]
Hm even with the value I still get `/home/pi/.lnd/lnd.conf:24: unknown option: lnd.bitcoin.active`

**Comment by pinheadmz** [comment]
Ok actually I had some success converting my lnd.conf for litd, by removing ALL subcategory headers:

```
[Application Options]
httpslisten=0.0.0.0:8888
uipassword=XXXXXX
lnd.debuglevel=debug
lnd.maxpendingchannels=10
lnd.alias=XXXXXXXXX
lnd.externalip=XX.XX.XX.XX

; If the autopilot agent should be active or not. The autopilot agent will
; attempt to automatically open up channels to put your node in an advantageous
; position within the network graph.
lnd.autopilot.active=0

; The maximum number of channels that should be created.
lnd.autopilot.maxchannels=20

; The fraction of total funds that should be committed to automatic channel
; establishment. For example 0.6 means that 60% of the total funds available
; within the wallet should be used to automatically establish channels. The total
; amount of attempted channels will still respect the maxchannels param.
lnd.autopilot.allocation=1

lnd.bitcoin.active=1
lnd.bitcoin.mainnet=1
lnd.bitcoin.node=bitcoind
lnd.bitcoin.minhtlc=1

lnd.bitcoind.rpcuser=XXXXXXXX
lnd.bitcoind.rpcpass=XXXXXXXX
lnd.bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
lnd.bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

```

**Comment by jamaljsr** [comment]
It appears that the `[Bitcoin]` header is the culprit in causing the conf file to fail to load. I'll get this fixed in the README asap. Thank for the additional info.

**Comment by pfergi42** [comment]
Confirmed. I was able to comment out the [Bitcoin] header and got the error to go away.

**Comment by isuldor** [comment]
Perhaps litd should have its own configfile?  It's structured quite differently from `lnd.conf` at this point. At least that way it's clear to new users that a whole new config needs to be worked up.

**Comment by jamaljsr** [comment]
> Perhaps litd should have its own configfile?

Agreed. See https://github.com/lightninglabs/lightning-terminal/issues/73#issuecomment-659408128
